"""Core Paper 1 decks (after the first one in core.py)."""

CP1 = "01-core-component/01-core-paper-1.md"

DECKS = [
    {
        "area": "core",
        "file": "core/02-problem-solving-strategies-and-reflective-practice.pptx",
        "title": "Problem-Solving Strategies and Reflective Practice",
        "unit": "Core Paper 1",
        "spec": "1.3, 2.10",
        "pages": [CP1],
        "objectives": [
            "Compare top-down, bottom-up and modular problem-solving approaches.",
            "Use root cause analysis techniques such as the five whys.",
            "Explain the incident management process and the difference between an incident and a problem.",
            "Apply Kolb's and Gibbs' reflective cycles, concept mapping and design thinking to support issues.",
        ],
        "starter": "Your phone will not charge. List every possible cause you can think of. "
                   "How would you find out which one it really is?",
        "slides": [
            {"type": "cards", "title": "Three problem-solving approaches",
             "cards": [
                 ("Top-down", "Start with the whole problem and break it into smaller and smaller parts. "
                  "Good for planning a new system from a clear brief."),
                 ("Bottom-up", "Start with small, known components and combine them into a bigger solution. "
                  "Good when reliable parts already exist."),
                 ("Modularisation", "Split the solution into self-contained modules that can be built, "
                  "tested and reused separately."),
             ],
             "notes": "Ask which approach a technician would use to build a new office network (top-down) "
                      "versus fixing up an old one from spare kit (bottom-up)."},
            {"type": "process", "title": "The high-level problem-solving strategy",
             "steps": [
                 ("Define", "State exactly what the problem is."),
                 ("Gather", "Collect information from users, logs and systems."),
                 ("Analyse", "Look for causes and patterns in the information."),
                 ("Plan", "Decide on a plan of action."),
                 ("Implement", "Carry out the solution."),
                 ("Review", "Check the fix worked and nothing else broke."),
             ],
             "notes": "This strategy is the backbone of Task 2 in every Employer Set Project."},
            {"type": "cards", "title": "Root cause analysis",
             "cards": [
                 ("Five whys", "Keep asking 'why?' about each answer until you reach the underlying cause, "
                  "usually about five times."),
                 ("FMEA", "Failure Mode and Effects Analysis lists every way a component could fail and "
                  "the effect of each failure."),
                 ("Event Tree Analysis", "Starts from one initiating event and maps the possible outcomes "
                  "that could follow from it."),
                 ("Then act", "Once the root cause is found: log it, close it, or escalate it to a manager, "
                  "specialist or third party."),
             ],
             "notes": "Model the five whys: the website is down. Why? The server crashed. Why? It ran out "
                      "of disk space. Why? Logs were never cleared. Why? No maintenance task was set up."},
            {"type": "compare", "title": "Incidents and problems",
             "left": ("Digital incident", [
                 "A single unplanned event",
                 "Disrupts service operations",
                 "Reduces service quality",
                 "Example: users cannot log in this morning",
             ]),
             "right": ("Digital problem", [
                 "The underlying cause of one or more incidents",
                 "Found through root cause analysis",
                 "Fixing it stops incidents recurring",
                 "Example: an expired certificate on the login server",
             ]),
             "notes": "Students often mix these up. An incident is the symptom, a problem is the cause."},
            {"type": "process", "title": "The incident management process",
             "steps": [
                 ("Detection", "Report, record and prioritise the incident."),
                 ("Response", "Identify the owner, resolve and restore service, record the resolution."),
                 ("Intelligence", "Record lessons, identify the cause and share what was learned."),
             ],
             "caption": "Intelligence is the stage most often skipped, and the one that stops the same incident happening again."},
            {"type": "compare", "title": "Two reflective practice models",
             "left": ("Kolb's Experiential Learning Cycle", [
                 "Concrete experience: something happens",
                 "Reflective observation: think about what happened",
                 "Abstract conceptualisation: draw conclusions",
                 "Active experimentation: try the new idea",
             ]),
             "right": ("Gibbs' Reflective Cycle", [
                 "Description: what happened?",
                 "Feelings: what were you thinking?",
                 "Evaluation: what was good and bad?",
                 "Analysis: what sense can you make of it?",
                 "Conclusion: what else could you have done?",
                 "Action plan: what will you do next time?",
             ]),
             "notes": "Both are used after a support issue to improve future practice. Gibbs is more "
                      "structured and includes feelings, which helps with difficult customer situations."},
            {"type": "cards", "title": "Concept mapping and design thinking",
             "cards": [
                 ("Concept mapping", "Put the main idea in the centre, then link concepts (hardware, software, "
                  "people, information, processes) using verb labels such as 'stores' or 'uses'."),
                 ("Design thinking", "Empathise, define, ideate, prototype, get user feedback, then repeat. "
                  "It keeps the user at the centre of the solution."),
             ],
             "notes": "Concept map symbols are listed on the Diagram notation page of the wiki."},
        ],
        "quiz": [
            ("Which approach starts with the whole problem and breaks it down?", "Top-down."),
            ("What is the difference between an incident and a problem?",
             "An incident is a single unplanned disruption; a problem is its underlying cause."),
            ("Name the three stages of incident management.", "Detection, response, intelligence."),
            ("What does FMEA stand for?", "Failure Mode and Effects Analysis."),
            ("What is the final stage of Gibbs' Reflective Cycle?", "Action plan."),
        ],
        "activity": {
            "title": "Five whys on a real fault",
            "time": "20 minutes",
            "format": "Small groups",
            "steps": [
                "Scenario: staff in one office keep losing their Wi-Fi connection every afternoon.",
                "Use the five whys to reach a believable root cause.",
                "Decide whether to log, close or escalate it, and to whom.",
                "Write a short Gibbs reflection as the technician who fixed it.",
            ],
            "success": [
                "Each 'why' follows logically from the last",
                "Root cause is a cause, not a symptom",
                "Escalation decision is justified",
                "All six Gibbs stages are covered",
            ],
            "notes": "Possible root causes: interference from a microwave used at lunch, DHCP lease pool too small, "
                     "access point overheating in afternoon sun.",
        },
        "exit": [
            "Give one example of a digital incident and its possible underlying problem.",
            "When would modularisation be a good approach?",
            "Which reflective model would you choose after a stressful call, and why?",
        ],
    },
    {
        "area": "core",
        "file": "core/03-networks-cabling-and-unified-communications.pptx",
        "title": "Network Infrastructure, Cabling and Unified Communications",
        "unit": "Core Paper 1",
        "spec": "2.1, 2.2, 2.3",
        "pages": [CP1],
        "objectives": [
            "Interpret routing table data and TCP/IP configuration from console tools.",
            "Explain what a firewall does and how ALLOW and BLOCK rules take precedence.",
            "Compare cable types and Ethernet standards on bandwidth and length.",
            "Explain VoIP, SIP, codecs and the network metrics that affect call quality.",
        ],
        "starter": "Open a command prompt and type ipconfig (or ifconfig on Linux or macOS). "
                   "What do you think each line of the output tells you?",
        "slides": [
            {"type": "table", "title": "Reading a routing table",
             "header": ["Field", "What it tells you"],
             "widths": [2, 6],
             "rows": [
                 ["Network ID", "The destination network the route leads to"],
                 ["Subnet mask", "Which part of the address identifies the network"],
                 ["Next hop", "The next router the packet is sent to"],
                 ["Interface", "Which network interface the packet leaves through"],
                 ["Static or dynamic", "Whether the route was entered by hand or learned from a routing protocol"],
             ],
             "notes": "Show a real routing table with 'route print' on Windows or 'ip route' on Linux."},
            {"type": "bullets", "title": "Console tools and firewalls",
             "bullets": [
                 "ipconfig / ifconfig: shows IP address, subnet mask, default gateway and DNS servers.",
                 "Firewall: filters traffic in and out of a network or device using rules.",
                 "Rules: each rule ALLOWs or BLOCKs traffic by address, port or application.",
                 "Precedence: rules are checked in order, and the first matching rule usually wins.",
                 "Admin access: secure it with strong credentials and restrict where it can be reached from.",
             ],
             "callout": "Put specific rules above general ones. A 'block all' rule at the top would stop "
                        "every rule below it from ever being reached.",
             "notes": "Demonstrate ordering with two rules: ALLOW port 443 from anywhere, then BLOCK all."},
            {"type": "cards", "title": "Cable types",
             "cards": [
                 ("UTP", "Unshielded twisted pair. Cheap and flexible; the standard for office LANs."),
                 ("STP", "Shielded twisted pair. Extra shielding reduces interference in electrically noisy areas."),
                 ("Coaxial", "Copper core with a braided shield. Used for broadband and TV connections."),
                 ("Fibre optic", "Sends light, not electricity. Very high bandwidth over long distances and immune to interference."),
             ]},
            {"type": "table", "title": "Ethernet cable standards",
             "header": ["Standard", "Typical bandwidth", "Max length", "Trade-off"],
             "widths": [1.5, 2, 1.6, 4],
             "rows": [
                 ["CAT 5e", "Up to 1 Gbps", "100 m", "Cheapest; fine for most desktops"],
                 ["CAT 6", "Up to 10 Gbps (up to about 55 m)", "100 m", "Better crosstalk protection, costs more"],
                 ["CAT 7", "Up to 10 Gbps", "100 m", "Fully shielded, thicker and harder to install"],
             ],
             "caption": "Ethernet is the family of wired LAN standards these cables are built for.",
             "notes": "Check the latest values in the specification if a question asks for exact figures."},
            {"type": "cards", "title": "Unified communications",
             "cards": [
                 ("VoIP", "Voice over IP carries phone calls as data packets over a network."),
                 ("SIP", "Session Initiation Protocol sets up, manages and ends VoIP calls and video sessions."),
                 ("Codecs", "Compress and decompress media. MPEG-4 for video, MP3 for lossy audio, FLAC for lossless audio."),
             ],
             "notes": "SIP is the signalling that starts and ends the call; VoIP is the voice data itself."},
            {"type": "cards", "title": "What affects call quality",
             "cards": [
                 ("Speed", "How fast data is transferred."),
                 ("Bandwidth", "How much data can be carried at once."),
                 ("Latency", "The delay before data arrives. High latency causes talk-over."),
                 ("Jitter", "Variation in latency. Causes choppy, robotic audio."),
                 ("Packet loss", "Packets that never arrive. Causes gaps and dropped words."),
             ]},
        ],
        "quiz": [
            ("What does the next hop field in a routing table show?", "The next router a packet is sent to."),
            ("Which cable type is immune to electrical interference?", "Fibre optic."),
            ("What is the maximum length of a CAT 6 Ethernet run?", "100 metres."),
            ("What does SIP do?", "Sets up, manages and ends VoIP and video sessions."),
            ("Which network metric causes choppy, robotic-sounding calls?", "Jitter."),
        ],
        "activity": {
            "title": "Diagnose the bad VoIP line",
            "time": "15 minutes",
            "format": "Pairs",
            "steps": [
                "A sales team complains that calls keep breaking up and people talk over each other.",
                "Identify which network metrics could explain each symptom.",
                "Suggest two tests you would run to confirm your theory.",
                "Recommend one cabling or configuration change and justify it.",
            ],
            "success": [
                "Links talk-over to latency",
                "Links breaking up to jitter or packet loss",
                "Tests are realistic, e.g. ping or a VoIP quality tool",
                "Recommendation is justified",
            ],
        },
        "exit": [
            "What would ipconfig tell you if a PC cannot reach the internet?",
            "Why must firewall rules be placed in the right order?",
            "Which codec would you pick to archive a recording without losing quality?",
        ],
    },
    {
        "area": "core",
        "file": "core/04-supporting-and-testing-systems.pptx",
        "title": "Supporting and Testing Systems",
        "unit": "Core Paper 1",
        "spec": "2.4, 2.5",
        "pages": [CP1],
        "objectives": [
            "Select hardware, operating systems and software that meet a user's needs.",
            "Interpret fault indicators and technical documentation to diagnose problems.",
            "Compare testing methods and choose suitable ones.",
            "Create test data and a test plan, and judge whether results are believable.",
        ],
        "starter": "A graphic designer and a receptionist both need a new PC. "
                   "What would you choose differently for each, and why?",
        "slides": [
            {"type": "cards", "title": "Matching systems to user needs",
             "cards": [
                 ("Hardware", "Cores, memory, storage, clock speed and connectivity. Match them to the workload."),
                 ("Operating system", "Graphical or text based, multi-tasking, single or multi-user, or a virtual machine."),
                 ("Software", "Database, spreadsheet, word processor, presentation, communication or browser."),
             ],
             "notes": "Students must be able to select, configure and test these, and justify their choices."},
            {"type": "cards", "title": "Fault indicators",
             "cards": [
                 ("Error numbers", "A code that can be looked up in documentation, e.g. a Windows stop code."),
                 ("Error messages", "Text describing what went wrong. Read the whole message, not just the title."),
                 ("Beep codes", "Patterns of beeps at start-up, often pointing to RAM or graphics faults."),
                 ("Blink codes", "Patterns of flashing LEDs, common on laptops and printers."),
             ],
             "notes": "Beep and blink codes differ between manufacturers, so always check the technical documentation."},
            {"type": "table", "title": "Testing methods",
             "header": ["Method", "What it checks"],
             "widths": [2, 6],
             "rows": [
                 ["Unit / integration", "One component alone, then components working together"],
                 ["System / acceptance", "The whole system, then whether it meets the user's requirements"],
                 ["Boundary", "Values at the edge of what is allowed"],
                 ["Performance / load / stress", "Speed under normal use, heavy use and beyond its limits"],
                 ["Usability", "How easy real users find it"],
                 ["Regression", "That a change has not broken something that used to work"],
                 ["Closed box / open box", "Testing without, or with, knowledge of the internal code"],
             ],
             "notes": "Concept testing (checking an idea before building it) is also in the specification. "
                      "Components are tested before integration so faults are easier to locate."},
            {"type": "cards", "title": "Types of test data",
             "cards": [
                 ("Valid", "Normal data that should be accepted. Age: 25."),
                 ("Invalid", "Data of the right type that should be rejected. Age: 150."),
                 ("Boundary", "Data at the edge of the range. Age: 0 and 120."),
                 ("Erroneous", "Data of the wrong type entirely. Age: 'twenty'."),
             ]},
            {"type": "process", "title": "Structure of a test plan",
             "steps": [
                 ("Identify tests", "List what will be tested."),
                 ("Describe purpose", "Say why each test matters."),
                 ("Test data", "Choose the data to use."),
                 ("Expected result", "Predict what should happen."),
                 ("Actual result", "Record what really happened."),
             ],
             "notes": "Macros and scripts can automate repeated tests."},
            {"type": "bullets", "title": "Are the results believable?",
             "bullets": [
                 "Logical reasoning: were the inputs unbiased and relevant, and do the results make sense?",
                 "Subject matter expert: ask someone with expertise to verify the results.",
                 "Test plan: compare actual results against the expected results you wrote down first.",
             ],
             "callout": "Always write the expected result before you run the test. Otherwise it is too easy "
                        "to convince yourself the actual result was what you wanted."},
        ],
        "quiz": [
            ("Give two examples of fault indicators.", "Any two of: error numbers, error messages, beep codes, blink codes."),
            ("What does regression testing check?", "That a change has not broken existing functionality."),
            ("An age field accepts 0 to 120. Give a boundary test value.", "0 or 120."),
            ("What is the difference between closed box and open box testing?",
             "Closed box tests without knowledge of the internal code; open box uses that knowledge."),
            ("Why are components tested before integration?", "So faults can be found and located more easily."),
        ],
        "activity": {
            "title": "Write a test plan",
            "time": "25 minutes",
            "format": "Individual",
            "steps": [
                "A booking form asks for a name, an email address and a number of guests from 1 to 8.",
                "Write a test plan with at least eight tests.",
                "Include valid, invalid, boundary and erroneous data.",
                "Fill in the expected result for every test before swapping with a partner.",
            ],
            "success": [
                "All five test plan columns completed",
                "All four test data types used",
                "Boundaries at 1 and 8 tested",
                "Expected results are precise",
            ],
        },
        "exit": [
            "What hardware spec matters most for a video editor?",
            "What is erroneous data?",
            "Name one way to check that test results are accurate.",
        ],
    },
    {
        "area": "core",
        "file": "core/05-project-management-and-risk-assessment.pptx",
        "title": "Project Management and Risk Assessment",
        "unit": "Core Paper 1",
        "spec": "2.8, 2.9",
        "pages": [CP1],
        "objectives": [
            "Build and interpret a 5 by 5 risk matrix.",
            "Describe what risk assessment documentation should record.",
            "Compare Waterfall and Agile project methodologies.",
            "Interpret and draw Gantt, PERT, Kanban, precedence and critical path diagrams.",
        ],
        "starter": "You are installing 30 new PCs in a school over half term. What could go wrong? "
                   "Which of those risks worries you most?",
        "slides": [
            {"type": "table", "title": "The 5 by 5 risk matrix",
             "header": ["Likelihood \\ Severity", "Negligible", "Marginal", "Moderate", "Critical", "Catastrophic"],
             "widths": [2.4, 1.3, 1.3, 1.3, 1.3, 1.5],
             "rows": [
                 ["Frequent (5)", "5", "10", "15", "20", "25"],
                 ["Probable (4)", "4", "8", "12", "16", "20"],
                 ["Occasional (3)", "3", "6", "9", "12", "15"],
                 ["Remote (2)", "2", "4", "6", "8", "10"],
                 ["Improbable (1)", "1", "2", "3", "4", "5"],
             ],
             "caption": "Risk score = likelihood x severity. Higher scores need action first.",
             "notes": "Severity runs 1 (negligible) to 5 (catastrophic). Ask students to place three risks from the starter on the grid."},
            {"type": "bullets", "title": "Risk assessment documentation",
             "bullets": [
                 "A description of the risk",
                 "Who or what could be harmed, and how",
                 "Mitigations already in place",
                 "Further mitigation needed",
                 "Who is responsible, and the due date",
             ],
             "callout": "Risk assessments exist to ensure continuity of service, health and safety, and regulatory compliance."},
            {"type": "compare", "title": "Waterfall and Agile",
             "left": ("Waterfall", [
                 "Linear stages completed in order",
                 "Requirements fixed at the start",
                 "Easy to plan, budget and document",
                 "Hard to change once a stage is finished",
                 "Suits projects with clear, stable requirements",
             ]),
             "right": ("Agile", [
                 "Short iterations delivering working pieces",
                 "Requirements evolve with feedback",
                 "Frequent contact with the customer",
                 "Harder to predict final cost and date",
                 "Suits projects where needs will change",
             ])},
            {"type": "cards", "title": "Project management techniques",
             "cards": [
                 ("Gantt chart", "Bars on a timeline showing when each task starts and ends."),
                 ("PERT chart", "Network of tasks with optimistic, likely and pessimistic time estimates."),
                 ("Precedence table", "Lists each task and the tasks that must finish before it."),
                 ("Kanban", "Board of cards moving through columns such as To do, Doing, Done."),
                 ("Critical Path Analysis", "Finds the longest chain of dependent tasks: the shortest possible project length."),
             ],
             "notes": "Task 1 of the Employer Set Project asks students to produce a Gantt chart, so give this plenty of practice."},
            {"type": "bullets", "title": "Finding the critical path",
             "bullets": [
                 "List every task with its duration and dependencies (a precedence table).",
                 "Draw the tasks as a network in dependency order.",
                 "Add up the duration along every route from start to finish.",
                 "The longest route is the critical path.",
                 "A delay to any task on it delays the whole project.",
             ],
             "callout": "Tasks not on the critical path have float: spare time they can slip without delaying the finish."},
        ],
        "quiz": [
            ("A risk is 'probable' and 'critical'. What is its score?", "4 x 4 = 16."),
            ("Name three things a risk assessment should record.",
             "Any three of: description, who/what could be harmed, how, existing mitigations, further mitigation, owner, due date."),
            ("Which methodology suits a project whose requirements will change?", "Agile."),
            ("What does a Gantt chart show?", "When each task starts and finishes on a timeline."),
            ("What happens if a task on the critical path is delayed?", "The whole project is delayed."),
        ],
        "activity": {
            "title": "Plan the PC rollout",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "Tasks: order kit (5 days), image PCs (3), remove old PCs (1), install desks and cabling (2), install new PCs (2), test (1).",
                "Build a precedence table for the tasks.",
                "Draw a Gantt chart and find the critical path.",
                "Score the three biggest risks on the 5 by 5 matrix.",
            ],
            "success": [
                "Dependencies are realistic",
                "Gantt chart is to scale",
                "Critical path identified with its total length",
                "Each risk has a mitigation and an owner",
            ],
        },
        "exit": [
            "What is the highest possible score on a 5 by 5 matrix?",
            "Give one drawback of Waterfall.",
            "What does float mean in critical path analysis?",
        ],
    },
    {
        "area": "core",
        "file": "core/06-data-fundamentals.pptx",
        "title": "Data Fundamentals",
        "unit": "Core Paper 1",
        "spec": "3.1 to 3.6",
        "pages": [CP1],
        "objectives": [
            "Distinguish between data, information and knowledge.",
            "Describe sources of data and how organisations use it.",
            "Classify data as quantitative or qualitative and choose suitable data types.",
            "Compare common data formats and storage structures.",
        ],
        "starter": "37.8. Is that data or information? What would you need to add to make it useful?",
        "slides": [
            {"type": "process", "title": "Data, information and knowledge",
             "steps": [
                 ("Data", "Raw facts and figures with no context. 37.8"),
                 ("Information", "Data given context and meaning. A patient's temperature is 37.8 C."),
                 ("Knowledge", "Understanding applied to information. 37.8 C is a mild fever, so monitor them."),
             ],
             "notes": "Link back to the starter."},
            {"type": "cards", "title": "Where data comes from",
             "cards": [
                 ("Humans", "Surveys and forms."),
                 ("AI and machine learning", "Generated predictions. Watch for feedback loops that reinforce errors."),
                 ("Sensors", "Temperature, accelerometer, vibration, sound, light, pressure."),
                 ("IoT devices", "Smart thermostats, lights, security cameras, trackers."),
                 ("Transactions", "Customer, membership, timing and basket data."),
             ],
             "notes": "Data's value depends on its quantity, timeframe, source and veracity, and it must be handled ethically."},
            {"type": "bullets", "title": "How organisations use data",
             "bullets": [
                 "Pattern analysis: spotting trends in sales or faults",
                 "System performance monitoring: load, outages, throughput, status",
                 "User monitoring: how staff and customers use systems",
                 "Targeted marketing: personalised offers",
                 "Threat and opportunity assessment",
             ],
             "callout": "Data is transformed in three ways: manipulating it, analysing it and processing it."},
            {"type": "compare", "title": "Data taxonomy",
             "left": ("Quantitative (structured)", [
                 "Discrete: whole counts, e.g. number of tickets",
                 "Continuous: measured values, e.g. CPU temperature",
                 "Categorical: fixed groups, e.g. priority high, medium, low",
             ]),
             "right": ("Qualitative (unstructured)", [
                 "Free text, images, audio and video",
                 "Stored and retrieved as a single object",
                 "Or codified into structured data, e.g. tagging feedback as positive or negative",
             ])},
            {"type": "table", "title": "Data types",
             "header": ["Type", "Holds", "Example"],
             "widths": [1.5, 4, 3],
             "rows": [
                 ["Integer", "Whole numbers", "Number of users: 42"],
                 ["Real", "Numbers with decimals", "Download speed: 72.5"],
                 ["Character", "A single symbol", "Grade: B"],
                 ["String", "Text", "Hostname: SRV-01"],
                 ["Boolean", "True or false", "Account locked: True"],
                 ["Date", "A calendar date or time", "Last login: 03/09/2026"],
                 ["Blob", "Binary large object", "A photo or PDF file"],
             ]},
            {"type": "table", "title": "Data formats",
             "header": ["Format", "Description", "Typical use"],
             "widths": [1.4, 4, 3.2],
             "rows": [
                 ["CSV", "Values separated by commas, one record per line", "Exporting spreadsheet data"],
                 ["JSON", "Key and value pairs in nested objects", "Web APIs and config files"],
                 ["XML", "Data wrapped in named tags", "Document and data exchange"],
                 ["Text file", "Plain unformatted text", "Logs and notes"],
                 ["ASCII", "7-bit character set, 128 characters", "Basic English text"],
                 ["UTF-8", "Unicode encoding covering every language", "Web pages and modern text"],
             ]},
            {"type": "cards", "title": "Structures for storing data",
             "cards": [
                 ("Metadata", "Data about data: author, date created, file size. Gives context."),
                 ("File based", "Data kept in individual files, simple but hard to share and search."),
                 ("Directory based", "Files organised into folders."),
                 ("Hierarchy based", "Data arranged in parent and child levels, like a tree."),
             ]},
        ],
        "quiz": [
            ("What turns data into information?", "Adding context and meaning."),
            ("Is 'CPU temperature' discrete or continuous data?", "Continuous."),
            ("Which data type would store 'Account locked: yes or no'?", "Boolean."),
            ("Which format is commonly used by web APIs?", "JSON."),
            ("What is metadata?", "Data that describes other data, such as author or date created."),
        ],
        "activity": {
            "title": "Design a helpdesk ticket record",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "List ten fields a helpdesk ticket should store.",
                "Choose a data type for each field and justify it.",
                "Classify each field as quantitative or qualitative.",
                "Write one example ticket in JSON and the same ticket as a CSV row.",
            ],
            "success": [
                "Every field has a sensible data type",
                "At least one Boolean and one date",
                "JSON is correctly nested",
                "CSV header matches the fields",
            ],
        },
        "exit": [
            "Give your own example of data, information and knowledge.",
            "Why might AI-generated data be risky?",
            "When would you choose CSV over JSON?",
        ],
    },
    {
        "area": "core",
        "file": "core/07-data-quality-systems-and-analysis.pptx",
        "title": "Data Quality, Systems and Analysis",
        "unit": "Core Paper 1",
        "spec": "2.6, 3.7 to 3.12",
        "pages": [CP1],
        "objectives": [
            "Apply validation checks and spreadsheet functions to interrogate data.",
            "Explain the 6 Vs of Big Data and methods of data quality assurance.",
            "Describe data wrangling, data entry errors and how to reduce them.",
            "Compare data models, access mechanisms and data analysis tools.",
        ],
        "starter": "A customer typed their date of birth as 31/02/2008. How could the system have stopped this?",
        "slides": [
            {"type": "cards", "title": "Validation checks",
             "cards": [
                 ("Presence", "A value has been entered."),
                 ("Length", "The right number of characters, e.g. a postcode."),
                 ("Range", "Between allowed limits, e.g. 1 to 8 guests."),
                 ("Type", "The right data type, e.g. a number."),
                 ("Format", "Matches a pattern, e.g. an email address."),
             ],
             "notes": "Validation checks data is sensible, not that it is correct. 01/01/2000 passes validation even if it is the wrong birthday."},
            {"type": "table", "title": "Interrogating data in a spreadsheet",
             "header": ["Technique", "Example"],
             "widths": [3, 5],
             "rows": [
                 ["Sort, order and filter by field", "Show only tickets with priority High"],
                 ["SUM, MIN, MAX, AVERAGE", "=AVERAGE(D2:D100) for average fix time"],
                 ["IF", "=IF(D2>48,\"Breach\",\"OK\") to flag SLA breaches"],
                 ["COUNTIF", "=COUNTIF(C2:C100,\"Printer\") to count printer faults"],
                 ["Import from text files", "Load a CSV log into a worksheet for analysis"],
             ]},
            {"type": "cards", "title": "The 6 Vs of Big Data",
             "cards": [
                 ("Volume", "The sheer amount of data."),
                 ("Variety", "Many types: text, images, sensor readings."),
                 ("Variability", "Meaning and flow change over time."),
                 ("Velocity", "How fast data arrives and must be processed."),
                 ("Veracity", "How accurate and trustworthy it is."),
                 ("Value", "What useful insight it gives."),
             ],
             "notes": "Quality assurance methods: validation, verification, reliability, consistency, integrity and redundancy. Maintenance also depends on time, skills and cost."},
            {"type": "process", "title": "Data wrangling",
             "steps": [
                 ("Structure", "Put raw data into a usable shape."),
                 ("Clean", "Remove errors and duplicates."),
                 ("Validate", "Check the data meets rules."),
                 ("Enrich", "Add useful extra data."),
                 ("Output", "Deliver it for analysis."),
             ],
             "caption": "Core functions of a data system: input, search, save, integrate, organise (index), output and a feedback loop."},
            {"type": "compare", "title": "Data entry errors",
             "left": ("Types of error", [
                 "Transcription: copying wrongly, e.g. typing 'Smtih'",
                 "Transposition: swapping characters, e.g. 1234 becomes 1243",
             ]),
             "right": ("Ways to reduce them", [
                 "Input validation",
                 "Double-entry verification",
                 "Drop-down menus",
                 "Pre-filled fields",
             ])},
            {"type": "cards", "title": "Data models",
             "cards": [
                 ("Hierarchical", "Parent and child tree. Fast for one path, poor for many-to-many links."),
                 ("Network", "Records can have many parents. Flexible but complex to build."),
                 ("Relational", "Tables of rows and columns linked by keys. The most common today."),
             ],
             "notes": "Students must be able to draw each: blocks, arrows and labels for hierarchical and network; tables, rows, columns and labels for relational. Choice depends on access efficiency, storage efficiency and implementation complexity."},
            {"type": "compare", "title": "Access and analysis",
             "left": ("Access across platforms", [
                 "Permissions: authorisation, privileges, access rights, rules",
                 "RBAC: access by job role",
                 "RuBAC: access by rules, e.g. time of day",
                 "APIs: controlled access for other software",
             ]),
             "right": ("Big Data analysis tools", [
                 "Data warehouse: structured, cleaned data from many sources",
                 "Data lake: raw data in any format",
                 "Data mart: a subset for one department",
                 "Data mining and reporting turn it into business intelligence",
             ]),
             "notes": "Business intelligence feeds financial planning and analysis and CRM."},
        ],
        "quiz": [
            ("Which validation check makes sure a field is not left empty?", "Presence check."),
            ("Typing 1243 instead of 1234 is what kind of error?", "Transposition error."),
            ("Which of the 6 Vs is about trustworthiness?", "Veracity."),
            ("Which data model uses linked tables?", "Relational."),
            ("What is the difference between a data warehouse and a data lake?",
             "A warehouse holds structured, cleaned data; a lake holds raw data in any format."),
        ],
        "activity": {
            "title": "Analyse a ticket log",
            "time": "30 minutes",
            "format": "Individual, in a spreadsheet",
            "steps": [
                "Import the ticket log CSV provided by your teacher (or make 20 rows of your own).",
                "Add validation to the priority and category columns.",
                "Use COUNTIF to count tickets by category, and AVERAGE for time to fix.",
                "Use IF to flag any ticket that took longer than 48 hours.",
                "Present your findings as one chart suited to a manager.",
            ],
            "success": [
                "Validation stops bad entries",
                "Formulas are correct and reusable",
                "Breaches flagged automatically",
                "Chart suits the audience",
            ],
            "notes": "If no CSV is available, students can generate one quickly; the skills are what matter.",
        },
        "exit": [
            "Why does validation not guarantee data is correct?",
            "Name two ways to reduce data entry errors.",
            "Which access mechanism would suit a hospital, and why?",
        ],
    },
]
