"""Core Paper 2 and Employer Set Project decks."""

CP2 = "01-core-component/02-core-paper-2.md"
ESP = "01-core-component/03-employer-set-projects.md"

DECKS = [
    {
        "area": "core",
        "file": "core/08-health-and-safety-in-digital-work.pptx",
        "title": "Health and Safety in Digital Work",
        "unit": "Core Paper 2",
        "spec": "4.1 (health and safety)",
        "pages": [CP2],
        "objectives": [
            "Describe employer duties under the Health and Safety at Work Act.",
            "Explain the manual handling, work at height and DSE regulations.",
            "Identify the main health and safety risks of digital work.",
            "Recommend suitable mitigations for each risk.",
        ],
        "starter": "Look around this room. List every hazard you can see that could hurt someone "
                   "working in IT here.",
        "slides": [
            {"type": "bullets", "title": "Health and Safety at Work Act",
             "bullets": [
                 "Provide a safe working environment",
                 "Train staff properly",
                 "Provide adequate welfare facilities",
                 "Give relevant information, instruction and supervision",
             ],
             "callout": "Employers carry the main duty, but employees must also take reasonable care of themselves and others.",
             "notes": "This is the umbrella law. The regulations on the next slides sit under it."},
            {"type": "cards", "title": "Key regulations",
             "cards": [
                 ("Manual handling", "Avoid hazardous lifting where possible. Otherwise assess the risk, give information on the load and its centre of gravity, and reduce the risk of injury."),
                 ("Work at height", "Plan and supervise the work, use competent people, do as much as possible from the ground, use suitable, stable equipment, protect against falling objects, plan for emergencies."),
                 ("Display screen equipment", "Assess workstations, reduce risks including regular breaks, provide eye tests on request, and give training and information."),
             ]},
            {"type": "table", "title": "Risks in digital work and how to reduce them",
             "header": ["Activity", "Risk", "Mitigation"],
             "widths": [2, 3.2, 3.6],
             "rows": [
                 ["Using DSE all day", "Eye strain, back and wrist pain", "Workstation assessment, breaks, eye tests"],
                 ["Working at height", "Falls, dropped tools", "Training, correct ladders or towers, supervision"],
                 ["Cable installation", "Trips, cuts, electric shock", "Safe environment, PPE, isolate power"],
                 ["Manual handling", "Back injury from servers or boxes", "Trolleys, team lifts, training"],
             ],
             "notes": "The four mitigation themes from the specification: training, safe environment, safety equipment and supervision."},
            {"type": "terms", "terms": [
                ("DSE", "display screen equipment, such as monitors and laptops."),
                ("Risk assessment", "identifying hazards and deciding how to control them."),
                ("PPE", "personal protective equipment, such as gloves or hard hats."),
                ("Competent person", "someone with the training and experience to do the task safely."),
            ]},
        ],
        "quiz": [
            ("Name two duties employers have under the Health and Safety at Work Act.",
             "Any two of: safe environment, training, welfare provision, information, instruction and supervision."),
            ("What must an employer provide on request under the DSE regulations?", "An eye test."),
            ("What is the first rule of the Work at Height Regulations?", "Avoid working at height where possible; do as much as possible from the ground."),
            ("Give one mitigation for manual handling risks.", "Trolleys, team lifts or manual handling training."),
        ],
        "activity": {
            "title": "Risk assess a server room move",
            "time": "20 minutes",
            "format": "Small groups",
            "steps": [
                "Your team is moving three rack servers and re-cabling a comms cabinet on a mezzanine floor.",
                "Identify at least five hazards.",
                "Link each one to the law or regulation that applies.",
                "Suggest a mitigation for each.",
            ],
            "success": [
                "Covers lifting, height and electrical hazards",
                "Correct regulation named for each",
                "Mitigations are practical",
            ],
        },
        "exit": [
            "Which regulation covers lifting a server?",
            "Why do DSE users need regular breaks?",
            "Name one hazard of installing cabling in a ceiling.",
        ],
    },
    {
        "area": "core",
        "file": "core/09-digital-legislation-and-professional-guidelines.pptx",
        "title": "Digital Legislation and Professional Guidelines",
        "unit": "Core Paper 2",
        "spec": "4.1 (legislation), 4.2",
        "pages": [CP2],
        "objectives": [
            "Explain the purpose of data protection law and the Computer Misuse Act.",
            "Describe equality, intellectual property and electrical waste legislation.",
            "Explain how codes of conduct and industry standards shape professional behaviour.",
            "Describe the purpose of acceptable use policies and whistleblowing procedures.",
        ],
        "starter": "A technician fixing a laptop finds a folder of customers' bank details. "
                   "What should they do? What laws might apply?",
        "slides": [
            {"type": "bullets", "title": "Data Protection Act and UK GDPR",
             "bullets": [
                 "Purpose: protect people's personal data and control how organisations use it.",
                 "Data must be processed fairly, lawfully and transparently, for specified purposes.",
                 "Only collect what is needed, keep it accurate, and do not keep it longer than necessary.",
                 "Keep it secure and respect people's rights over their data.",
             ],
             "callout": "Learn the eight data protection principles. They underpin almost every security decision in this course."},
            {"type": "cards", "title": "Computer Misuse Act 1990",
             "cards": [
                 ("Unauthorised access", "Accessing computer material without permission, e.g. guessing a colleague's password."),
                 ("Intent to commit further offences", "Unauthorised access in order to commit another crime, such as fraud."),
                 ("Unauthorised acts", "Acts that impair a computer's operation, e.g. spreading malware."),
             ],
             "notes": "Consequences fall on both employee and company, which is why staff awareness training matters."},
            {"type": "cards", "title": "Other key legislation",
             "cards": [
                 ("Equality", "Nine protected characteristics. Direct and indirect discrimination, harassment and victimisation, with time limits for action."),
                 ("Intellectual property", "Unregistered designs, registered designs and patents protect creators' work."),
                 ("WEEE Regulations", "Electrical waste must be disposed of safely and in an environmentally responsible way."),
                 ("International law", "Some offences cross borders, e.g. law in cyberspace and around surveillance."),
             ]},
            {"type": "compare", "title": "Guidelines that shape professional behaviour",
             "left": ("Codes of conduct", [
                 "From organisations, professional bodies (BCS, IAP, CIISec) and government",
                 "Follow policy, procedure and law",
                 "Work with competence and integrity",
                 "Meet deadlines and communicate well",
                 "Maintain confidentiality and trust",
             ]),
             "right": ("Industry standards bodies", [
                 "ISO: international standards",
                 "WCAG and W3C: web accessibility and web standards",
                 "IETF: internet protocols",
                 "EIA/TIA and IEEE: cabling and networking",
                 "BS and PCI Security Standards Council",
             ])},
            {"type": "compare", "title": "Acceptable use and whistleblowing",
             "left": ("Acceptable use policy (AUP)", [
                 "Permitted and prohibited activities",
                 "Working practices, including confidentiality",
                 "Communication etiquette",
                 "Sanctions and penalties for breaches",
             ]),
             "right": ("Whistleblowing procedure", [
                 "A safe way to report wrongdoing",
                 "Protects the person reporting",
                 "Lets problems be fixed before harm is done",
                 "Supports legal and ethical compliance",
             ])},
        ],
        "quiz": [
            ("What is the purpose of the Data Protection Act?", "To protect personal data and control how organisations use it."),
            ("Guessing a colleague's password to read their email breaks which law?", "The Computer Misuse Act 1990."),
            ("How many protected characteristics are there under equality legislation?", "Nine."),
            ("What does WEEE cover?", "Safe and environmentally responsible disposal of electrical and electronic waste."),
            ("Name two things an AUP sets out.", "Any two of: permitted and prohibited activities, working practices, etiquette, sanctions."),
        ],
        "activity": {
            "title": "Which law applies?",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Your teacher will give you six workplace scenarios (or write your own).",
                "For each, name the law or guideline that applies.",
                "Explain the impact on the organisation, society and the individual.",
                "Rank the scenarios from most to least serious and justify the order.",
            ],
            "success": [
                "Correct law identified each time",
                "Impact covers all three groups",
                "Ranking is justified",
            ],
            "notes": "Scenario ideas: old PCs sent to landfill; a job advert asking for 'young' applicants; "
                     "copying a rival's product design; an employee installing a keylogger; a manager ignoring a data breach; "
                     "a website unusable with a screen reader.",
        },
        "exit": [
            "Name one offence under the Computer Misuse Act.",
            "Why do professional bodies publish codes of conduct?",
            "Why is whistleblowing important?",
        ],
    },
    {
        "area": "core",
        "file": "core/10-the-business-context.pptx",
        "title": "The Business Context",
        "unit": "Core Paper 2",
        "spec": "5.1, 5.2, 5.3",
        "pages": [CP2],
        "objectives": [
            "Describe business sectors, business models and stakeholders.",
            "Explain how digital systems add value to each part of a business.",
            "Describe the user needs and quality expectations digital systems must meet.",
            "Explain the risks and impacts of using digital systems.",
        ],
        "starter": "Think of a business you use every week. What digital systems does it rely on? "
                   "What would happen if they all stopped for a day?",
        "slides": [
            {"type": "cards", "title": "The business environment",
             "cards": [
                 ("Sectors", "Private (SME, large enterprise, NGO), public, and voluntary or charity (not for profit)."),
                 ("Business models", "B2C sells to consumers, B2B to other businesses, B2M to a broad mass market."),
                 ("Internal stakeholders", "Owners, directors and employees."),
                 ("External stakeholders", "Customers, suppliers, shareholders, outsourced services, investors and government."),
             ],
             "notes": "Organisations exist to provide a service or a product."},
            {"type": "table", "title": "Digital value across the business",
             "header": ["Area", "How digital systems help"],
             "widths": [2, 6],
             "rows": [
                 ["Sales and marketing", "Market research, social media, online selling, personalisation, analytics"],
                 ["Research and development", "Enables unique products and services"],
                 ["HR", "Staff records, performance management, training records"],
                 ["Operations", "Communication, automation, remote working, intranets, document sharing"],
                 ["Management", "Real-time KPI monitoring"],
                 ["Logistics and finance", "Automated stock control; lower costs, more revenue, up-to-date reporting"],
             ]},
            {"type": "cards", "title": "User needs and quality expectations",
             "cards": [
                 ("Functionality", "Does what users need, effectively."),
                 ("Fewer pain points", "Fast response times, simple tasks."),
                 ("Accessibility", "Usable by everyone."),
                 ("Compatibility", "Works with legacy, future and external systems."),
                 ("Availability", "Minimal downtime and future-proofed."),
                 ("Support", "Effective end-user support and easy installation."),
             ]},
            {"type": "compare", "title": "Risks and impacts of digital systems",
             "left": ("Risks", [
                 "Security breaches: loss of confidentiality, integrity or availability",
                 "Privacy breaches of personal or business information",
                 "Regulatory or legal non-compliance",
                 "Audience exclusion through bias or poor UX",
                 "Rival technologies and technical failures",
             ]),
             "right": ("Impacts", [
                 "Legal action",
                 "Fines",
                 "Reputational damage",
                 "Loss of licence to practise",
                 "Loss of business",
             ])},
        ],
        "quiz": [
            ("Give an example of a public sector organisation.", "Any, e.g. the NHS, a council, a state school."),
            ("What does B2B mean?", "Business to business."),
            ("Is a supplier an internal or external stakeholder?", "External."),
            ("Give one way digital systems add value to HR.", "Staff records, performance management or training records."),
            ("Name two impacts of a data breach.", "Any two of: legal action, fines, reputational damage, loss of licence, loss of business."),
        ],
        "activity": {
            "title": "Digital audit of a local business",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Choose a local business, e.g. a gym, dentist or takeaway.",
                "Identify its sector, business model and stakeholders.",
                "Map the digital systems it uses to each business area.",
                "Identify its top three digital risks and their likely impact.",
            ],
            "success": [
                "Stakeholders split into internal and external",
                "At least four business areas covered",
                "Risks linked to realistic impacts",
            ],
        },
        "exit": [
            "What is the difference between a public and a voluntary organisation?",
            "Name one quality expectation users have of a system.",
            "Which impact of a breach do you think is hardest to recover from?",
        ],
    },
    {
        "area": "core",
        "file": "core/11-technical-change-management.pptx",
        "title": "Technical Change Management",
        "unit": "Core Paper 2",
        "spec": "5.4",
        "pages": [CP2],
        "objectives": [
            "Identify internal and external triggers for change.",
            "Describe how organisations respond to change.",
            "Explain the stages of the change management process, including the role of the CAB.",
            "Assess the feasibility of a digital project.",
        ],
        "starter": "Your college is moving all its files to the cloud next month. "
                   "Who needs to know? What could go wrong?",
        "slides": [
            {"type": "compare", "title": "Triggers for change",
             "left": ("Internal triggers", [
                 "Restructuring, expansion or downsizing",
                 "New strategic objectives: diversification, rebranding, new features",
                 "Crises: natural disasters, terrorism, cyber attacks",
                 "System failure or data corruption",
             ]),
             "right": ("External triggers (PESTLE)", [
                 "Political: new government, conflict",
                 "Economic: recession, inflation, competitors",
                 "Social: demographics, remote working",
                 "Technological: new tech, obsolescence, zero-days",
                 "Legal: new legislation",
                 "Environmental: sustainability, pandemics",
             ])},
            {"type": "bullets", "title": "How organisations respond",
             "bullets": [
                 "New or amended policies",
                 "Changed business processes: staffing, delivery schedules, opening hours",
                 "New, next-generation or updated products and services",
                 "Back-end or customer-facing digital systems",
                 "Improved training, or restructuring",
             ],
             "callout": "The Change Advisory Board (CAB) prioritises, reviews and approves change requests, monitors progress and gives feedback."},
            {"type": "process", "title": "The change management process (part 1)",
             "steps": [
                 ("Identify type", "New system or an amendment?"),
                 ("CAB review", "Prioritise, review and approve the request."),
                 ("Set objectives", "Use SMARTER objectives."),
                 ("Forecast impact", "Identify what the change will affect."),
                 ("Allocate resources", "Budget, time, staff, hardware and software."),
                 ("Communicate", "Share risks and impact with stakeholders."),
             ],
             "notes": "SMARTER: specific, measurable, achievable, realistic, time-bound, evaluated, reviewed."},
            {"type": "process", "title": "The change management process (part 2)",
             "steps": [
                 ("Configure", "Integrate with legacy systems, keep service running."),
                 ("Test fully", "Reproducible results in a proper test environment."),
                 ("Implement", "Parallel, phased, direct or pilot."),
                 ("Document", "Traceability, decisions logged, manuals kept."),
                 ("Plan rollback", "Backups and a recovery plan."),
                 ("Train and monitor", "Training needs, post-implementation review, version control."),
             ]},
            {"type": "table", "title": "Implementation methods",
             "header": ["Method", "How it works", "Trade-off"],
             "widths": [1.5, 3.8, 3.5],
             "rows": [
                 ["Direct", "Old system switched off, new one on", "Fast and cheap, but high risk"],
                 ["Parallel", "Both systems run side by side", "Safe fallback, but double the work"],
                 ["Phased", "Introduced one part at a time", "Lower risk, but takes longer"],
                 ["Pilot", "One site or team tries it first", "Problems found early, but slow to roll out"],
             ]},
            {"type": "cards", "title": "Is the project feasible?",
             "cards": [
                 ("Benefits and drawbacks", "Savings against the cost of change; impact on productivity, communication, security and reputation."),
                 ("Risks", "Resistance to change, misuse of new systems, not enough support or knowledge, disruption during rollout."),
                 ("Constraints", "Budget, time, and human and technological resources."),
             ]},
        ],
        "quiz": [
            ("Give one internal and one external trigger for change.", "E.g. internal: expansion; external: new legislation."),
            ("What does the CAB do?", "Prioritises, reviews and approves change requests, monitors the process and gives feedback."),
            ("What does the second R in SMARTER stand for?", "Reviewed."),
            ("Which implementation method runs old and new systems together?", "Parallel."),
            ("Why plan for rollback?", "So the system can be restored if the change fails."),
        ],
        "activity": {
            "title": "Write a change request",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Scenario: a dental practice is replacing paper records with a cloud booking system.",
                "Write SMARTER objectives for the change.",
                "Choose an implementation method and justify it.",
                "Write a rollback plan and a communication plan for staff and patients.",
            ],
            "success": [
                "All seven SMARTER elements present",
                "Method choice considers risk to patients",
                "Rollback plan names what is backed up and where",
            ],
        },
        "exit": [
            "Which implementation method is riskiest, and why?",
            "What is the purpose of a post-implementation review?",
            "Name one constraint on a digital project.",
        ],
    },
    {
        "area": "core",
        "file": "core/12-digital-support-roles-and-communication.pptx",
        "title": "Digital Support Roles and Communication",
        "unit": "Core Paper 2",
        "spec": "5.5",
        "pages": [CP2],
        "objectives": [
            "Describe responsibilities, roles and skills across the four occupational areas.",
            "Identify routes into digital support and security.",
            "Choose communication techniques suited to an audience.",
            "Meet the interaction needs of end users, managers and peers.",
        ],
        "starter": "What is the difference between first-line and third-line support? Guess before we look.",
        "slides": [
            {"type": "cards", "title": "Four occupational areas",
             "cards": [
                 ("Digital infrastructure", "Install, test and maintain components, keep systems available, recover and restore, troubleshoot and escalate. Roles: service desk, first to fourth-line support, server support."),
                 ("Network cabling", "Install, terminate, test and certify copper and fibre, fit racks and cabinets, produce cable route maps. Roles: cabling installer, network surveyor, installation engineer."),
                 ("Digital support", "Hardware and software support, user accounts, training users, asset registers, SOPs. Roles: helpdesk, first-line support, desktop support technician."),
                 ("Digital communications", "Install, test and maintain integrated communication systems, manage availability and performance, apply security."),
             ]},
            {"type": "compare", "title": "Skills and routes in",
             "left": ("Skills employers want", [
                 "Problem-solving and analytical thinking",
                 "Using digital, logging and diagnostic tools",
                 "Communication and active listening",
                 "Prioritisation and teamwork",
                 "Customer service and upskilling",
             ]),
             "right": ("Routes into the industry", [
                 "Further education, such as this T Level",
                 "Apprenticeships",
                 "Higher education",
                 "Professional courses and vendor certifications",
                 "Professional recognition",
             ])},
            {"type": "bullets", "title": "Communication techniques",
             "bullets": [
                 "Channels: incident tickets, system update notifications, forums.",
                 "Language: clear and concise, matched to the audience's size, knowledge and the detail they need.",
                 "Techniques: troubleshooting questions, active listening, reading body language, open questions.",
                 "Harder conversations: negotiation and conflict de-escalation.",
             ],
             "callout": "Explain it to a user as you would to a friend who is not technical. Save the jargon for colleagues."},
            {"type": "table", "title": "Meeting different interaction needs",
             "header": ["Audience", "What they need"],
             "widths": [2.2, 6],
             "rows": [
                 ["Clients and end users", "Verbal support, written updates, training, remote support, screen sharing"],
                 ["Managers", "Escalation routes, progress reports, presentations"],
                 ["Peers and colleagues", "Sharing best practice, knowledge, training and collaboration"],
             ]},
        ],
        "quiz": [
            ("Name two roles in network cabling installation.", "Any two of: cabling installer, network surveyor, network analyst, network installation engineer."),
            ("What is active listening?", "Fully concentrating on, understanding and responding to what the speaker says."),
            ("What do managers usually need from a support technician?", "Escalation routes, progress reports and presentations."),
            ("Give two routes into the industry.", "Any two of: FE, apprenticeships, HE, professional courses, professional recognition."),
        ],
        "activity": {
            "title": "Role play a support call",
            "time": "20 minutes",
            "format": "Threes: user, technician, observer",
            "steps": [
                "The user has lost a morning's work and is frustrated.",
                "The technician uses open questions and active listening to find the problem.",
                "The observer notes good techniques and any jargon used.",
                "Swap roles and repeat with a new problem.",
            ],
            "success": [
                "Technician stays calm and de-escalates",
                "Uses open questions first",
                "Explains the fix without jargon",
            ],
        },
        "exit": [
            "Which occupational area interests you most, and why?",
            "Give an example of an open question to ask a user.",
            "How would you explain a phishing email to a non-technical manager?",
        ],
    },
    {
        "area": "core",
        "file": "core/13-emerging-issues-and-technologies.pptx",
        "title": "Emerging Issues and Technologies",
        "unit": "Core Paper 2",
        "spec": "6.1, 6.2",
        "pages": [CP2],
        "objectives": [
            "Explain how digital technology affects organisational culture and society.",
            "Describe digital inclusion and the characteristics that affect it.",
            "Evaluate the impact of emerging technologies on organisations, individuals and society.",
        ],
        "starter": "Name one job that did not exist ten years ago, and one that might disappear in the next ten. Why?",
        "slides": [
            {"type": "compare", "title": "Impact of digital technologies",
             "left": ("On organisational culture", [
                 "New ways of communicating",
                 "Higher expectations of productivity and availability",
                 "More monitoring of staff",
                 "Remote, hybrid and in-office working",
                 "Automation, including AI",
             ]),
             "right": ("On society", [
                 "Job losses and changing skills",
                 "Less human decision-making and empathy",
                 "Privacy: digital footprint and surveillance",
                 "Digital isolation for some; better access to information for others",
                 "Generative AI and globalisation",
             ])},
            {"type": "bullets", "title": "Digital inclusion",
             "bullets": [
                 "Fair access needs suitable hardware, software and connectivity.",
                 "Follow best-practice codes and public sector accessibility regulations.",
                 "Consider age, digital and literacy skills, internal or external audience.",
                 "Consider cultural issues, including bias built into digital systems.",
                 "Consider additional and accessibility needs.",
             ],
             "callout": "Professional development keeps you competent, employable and up to date with standards as technology changes."},
            {"type": "cards", "title": "Emerging technologies (1)",
             "cards": [
                 ("Storage and processing", "Growing demand for storage; quantum computing could solve problems classical computers cannot."),
                 ("Internet of Things", "Edge computing, extra network load, industrial, smart city and home uses."),
                 ("Artificial intelligence", "Generative AI and machine learning."),
                 ("Extended reality", "Augmented and virtual reality for training, design and support."),
             ]},
            {"type": "cards", "title": "Emerging technologies (2)",
             "cards": [
                 ("Open source", "Free to use and change, with community support."),
                 ("Blockchain", "Tamper-resistant shared ledgers."),
                 ("3D printing and drones", "New ways to make and deliver things."),
                 ("Autonomous machines", "Self-driving cars and robotic assembly."),
                 ("Environmental impact", "Rare metals, energy use and disposal."),
             ],
             "notes": "Students should be able to judge how these technologies interrelate, e.g. AI plus drones plus IoT."},
        ],
        "quiz": [
            ("Give two ways digital technology has changed organisational culture.", "Any two, e.g. remote working, staff monitoring, automation."),
            ("What is digital isolation?", "Being left out because of a lack of skills, equipment, connectivity or resistance to change."),
            ("What is edge computing?", "Processing data close to where it is collected, e.g. on IoT devices, rather than in a central data centre."),
            ("Give one environmental impact of emerging technology.", "Rare metal use, energy consumption or disposal."),
        ],
        "activity": {
            "title": "Tech pitch and critique",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Each group is given one emerging technology.",
                "Prepare a one-minute pitch on its benefits to organisations.",
                "Another group responds with its risks to individuals and society.",
                "The class votes on whether benefits outweigh risks.",
            ],
            "success": [
                "Covers organisations, individuals and society",
                "Considers inclusion and the environment",
                "Uses real examples",
            ],
        },
        "exit": [
            "Which emerging technology will most affect IT support jobs?",
            "Name one characteristic that affects digital inclusion.",
            "Why does professional development matter in this industry?",
        ],
    },
    {
        "area": "core",
        "file": "core/14-hardware-and-software.pptx",
        "title": "Hardware and Software",
        "unit": "Core Paper 2",
        "spec": "7.1, 7.2",
        "pages": [CP2],
        "objectives": [
            "Identify types of computer and their hardware components.",
            "Compare storage types, including RAID, NAS and SAN.",
            "Describe the five operating system types.",
            "Describe common utility and application software.",
        ],
        "starter": "A smartwatch, a gaming PC and a server all contain a processor. "
                   "How do you think their processors differ?",
        "slides": [
            {"type": "cards", "title": "Types of computer",
             "cards": [
                 ("Personal computers", "Desktops and laptops for individual users."),
                 ("Mobile devices", "Phones and tablets: low power, long battery life."),
                 ("Servers", "Provide services to many users; built for reliability."),
                 ("Embedded devices", "Computers inside other products, e.g. a washing machine."),
             ]},
            {"type": "table", "title": "Hardware components",
             "header": ["Component", "Key points"],
             "widths": [2.2, 6],
             "rows": [
                 ["Processor", "Cores, clock speed, cache; mobile processors trade speed for battery life"],
                 ["Main memory", "RAM is volatile working memory; ROM holds start-up instructions"],
                 ["Motherboard and GPU", "Connects everything; GPU handles graphics and parallel work"],
                 ["Network interfaces", "Connected via PCI or USB"],
                 ["Cooling", "Air or liquid"],
                 ["Input, output and sensors", "Keyboards, displays, temperature and motion sensors"],
             ]},
            {"type": "cards", "title": "Secondary storage",
             "cards": [
                 ("Magnetic, solid state, optical", "Hard disks are cheap per GB; SSDs are fast; optical discs are portable and cheap."),
                 ("RAID 1", "Mirroring: two identical copies. Survives one disk failure."),
                 ("RAID 5", "Striping with parity across three or more disks. Survives one disk failure."),
                 ("RAID 10", "Mirrors that are striped. Fast and resilient, but needs four or more disks."),
                 ("NAS", "Network attached storage: a file server box on the network."),
                 ("SAN", "Storage area network: a dedicated high-speed network of block storage."),
             ]},
            {"type": "table", "title": "Operating system types",
             "header": ["Type", "Features", "Example use"],
             "widths": [1.6, 4, 3],
             "rows": [
                 ["Batch", "Non-interactive, high volume, scheduled", "Overnight payroll"],
                 ["Multitasking", "Concurrent running, time-slicing, interrupts", "Desktop PCs"],
                 ["Real-time", "Instant response for monitoring and control", "Traffic lights, card payments"],
                 ["Network", "Resource sharing, user management", "Windows Server"],
                 ["Mobile", "Low processing needs, long battery life", "Android, iOS"],
             ]},
            {"type": "compare", "title": "Utility and application software",
             "left": ("Utilities", [
                 "File management",
                 "Defragmenters",
                 "File compression",
                 "Package managers",
                 "Protection software",
                 "Backup software",
             ]),
             "right": ("Applications", [
                 "Word processors",
                 "Spreadsheets",
                 "Databases",
                 "Email",
                 "Project management software",
             ]),
             "notes": "Utilities maintain the computer; applications let users do their work."},
        ],
        "quiz": [
            ("Which type of memory is volatile?", "RAM."),
            ("What does RAID 1 do?", "Mirrors data onto two disks."),
            ("What is the difference between NAS and SAN?", "NAS is a file storage device on the network; SAN is a dedicated high-speed network of block storage."),
            ("Which OS type would control an aircraft's systems?", "Real-time."),
            ("Is a defragmenter a utility or an application?", "A utility."),
        ],
        "activity": {
            "title": "Spec a machine",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Your teacher assigns a user: a video editor, a small office file server, or a warehouse scanner.",
                "Choose the computer type, processor, memory and storage.",
                "Choose an operating system type and three pieces of software.",
                "Justify each choice against the user's needs.",
            ],
            "success": [
                "Hardware matches the workload",
                "RAID level justified for the server",
                "OS type is appropriate",
            ],
        },
        "exit": [
            "Why might a server use RAID 5?",
            "What makes a mobile OS different from a desktop OS?",
            "Name two utility programs.",
        ],
    },
    {
        "area": "core",
        "file": "core/15-networks.pptx",
        "title": "Networks",
        "unit": "Core Paper 2",
        "spec": "7.3",
        "pages": [CP2],
        "objectives": [
            "Compare network types, topologies and models.",
            "Describe the layers of the OSI and TCP/IP models.",
            "Explain packet structure, packet switching and error checking.",
            "Match common protocols to their purpose and explain bandwidth and latency.",
        ],
        "starter": "When you load a web page, how many different devices do you think your request passes through?",
        "slides": [
            {"type": "compare", "title": "Why network, and at what scale?",
             "left": ("Benefits and drawbacks", [
                 "Share files, printers and internet access",
                 "Central management and backups",
                 "But: cost of equipment and expertise",
                 "But: malware and faults can spread",
             ]),
             "right": ("Network types", [
                 "PAN: personal area, e.g. Bluetooth",
                 "LAN: one building or site",
                 "MAN: across a town or city",
                 "WAN: across countries, e.g. the internet",
             ])},
            {"type": "cards", "title": "Topologies and models",
             "cards": [
                 ("Star", "Every device connects to a central switch. One cable fault affects one device."),
                 ("Mesh", "Devices connect to many others. Very resilient, but costly."),
                 ("Tree", "Stars connected in a hierarchy."),
                 ("Logical vs physical", "How data flows versus how cables are laid out."),
                 ("Client-server and thin client", "Servers provide services; thin clients rely on the server to do the processing."),
                 ("Peer-to-peer", "Every device is equal and shares resources."),
             ],
             "notes": "Components: servers, clients, routers, switches and the internet connection or backbone. Connectivity can be wired (copper, fibre) or wireless (access points)."},
            {"type": "table", "title": "The OSI and TCP/IP models",
             "header": ["OSI layer", "Job", "TCP/IP layer"],
             "widths": [2, 4.5, 2],
             "rows": [
                 ["7 Application", "Services for user applications", "Application"],
                 ["6 Presentation", "Formatting, encryption, compression", "Application"],
                 ["5 Session", "Opens and manages sessions", "Application"],
                 ["4 Transport", "Reliable delivery, ports", "Transport"],
                 ["3 Network", "Logical addressing and routing", "Internet"],
                 ["2 Data link", "MAC addresses, frames", "Network"],
                 ["1 Physical", "Cables and signals", "Network"],
             ]},
            {"type": "bullets", "title": "Data packets",
             "bullets": [
                 "Header: source and destination address, packet number, protocol.",
                 "Payload: the actual data being sent.",
                 "Trailer: error checking data, such as a CRC.",
                 "Packet switching: packets take different routes and are reassembled in order.",
                 "Packet loss: congestion, faulty hardware or interference.",
             ],
             "callout": "A cyclic redundancy check (CRC) lets the receiver detect packets damaged on the way. Damaged packets are requested again."},
            {"type": "table", "title": "Common protocols",
             "header": ["Group", "Protocols", "Purpose"],
             "widths": [1.6, 2.6, 4.4],
             "rows": [
                 ["Web", "HTTP, HTTPS", "Transfer web pages; HTTPS encrypts them"],
                 ["Mail", "SMTP, POP, IMAP", "Send mail; download it; or keep it on the server"],
                 ["Routing", "RIP, OSPF", "Routers share routes with each other"],
                 ["Application", "FTP, SFTP", "Transfer files; SFTP securely"],
                 ["Application", "DHCP, DNS", "Assign IP addresses; turn names into IP addresses"],
             ],
             "caption": "Bandwidth is how much data can be sent at once; latency is the delay. Both affect performance."},
        ],
        "quiz": [
            ("Which network type covers a single building?", "LAN."),
            ("Which OSI layer handles routing?", "Layer 3, the network layer."),
            ("What is a CRC used for?", "Detecting errors in transmitted packets."),
            ("Which protocol turns a domain name into an IP address?", "DNS."),
            ("What is the difference between bandwidth and latency?", "Bandwidth is capacity; latency is delay."),
        ],
        "activity": {
            "title": "Follow the packet",
            "time": "20 minutes",
            "format": "Groups of seven",
            "steps": [
                "Each student is one OSI layer.",
                "Pass a 'message' down the layers on the sending side, each adding its own header note.",
                "Pass it up the layers on the receiving side, each removing its header.",
                "Discuss which layer would notice each of these faults: unplugged cable, wrong IP, blocked port.",
            ],
            "success": [
                "Layers are in the right order",
                "Each layer's job is described correctly",
                "Faults matched to the right layer",
            ],
        },
        "exit": [
            "Why is a star topology popular in offices?",
            "Which layer do switches work at?",
            "Name the protocol you would use to send an email.",
        ],
    },
    {
        "area": "core",
        "file": "core/16-virtual-cloud-and-resilient-environments.pptx",
        "title": "Virtual, Cloud and Resilient Environments",
        "unit": "Core Paper 2",
        "spec": "7.4, 7.5, 7.6",
        "pages": [CP2],
        "objectives": [
            "Describe virtual machines, hypervisors and the benefits and drawbacks of virtualisation.",
            "Compare private and public cloud and the IaaS, PaaS and SaaS models.",
            "Explain methods to make a digital environment resilient.",
        ],
        "starter": "If your college's server room flooded tonight, what would still work tomorrow morning? What would not?",
        "slides": [
            {"type": "compare", "title": "Virtual environments",
             "left": ("Components and features", [
                 "Virtual machines: PCs, switches, routers, servers",
                 "Type 1 hypervisor runs directly on hardware",
                 "Type 2 hypervisor runs on top of an OS",
                 "Features: isolation, emulation, portability, sharing",
             ]),
             "right": ("Benefits and drawbacks", [
                 "Cost-effective at scale and easy to manage",
                 "Resilient, better disaster recovery and testing",
                 "Possibly lower carbon footprint",
                 "But: extra load on hardware and slower execution",
                 "But: performance figures can be misleading",
             ])},
            {"type": "table", "title": "Cloud delivery models: who manages what?",
             "header": ["Model", "Client manages", "Provider manages"],
             "widths": [1.2, 3.7, 3.7],
             "rows": [
                 ["IaaS", "Applications, OS and middleware, runtime, data, user accounts", "Virtualisation and hardware"],
                 ["PaaS", "Applications, data, user accounts", "Hardware, virtualisation, OS and runtime"],
                 ["SaaS", "User accounts and data", "Everything else, including the application"],
             ],
             "caption": "Cloud can be private or public. Benefits: portability, elasticity, fewer storage limits, cost-effectiveness."},
            {"type": "cards", "title": "Making environments resilient",
             "cards": [
                 ("Patches and updates", "Planned, and in response to new vulnerabilities."),
                 ("Hardware replacement", "Rolling plans and secure disposal."),
                 ("Redundancy", "Duplicate data and systems so one failure is not fatal."),
                 ("Device hardening", "Remove unneeded ports, apps, permissions and access."),
                 ("Backups and recovery", "Onsite, offsite and cloud; hot, warm or cold sites."),
                 ("Standard procedures", "Training, induction and careful rollout of new systems."),
             ],
             "notes": "Benefits of resilience: better security, better reputation and less downtime."},
            {"type": "table", "title": "Hot, warm and cold sites",
             "header": ["Site", "What it has", "Recovery speed", "Cost"],
             "widths": [1.2, 4, 1.8, 1.4],
             "rows": [
                 ["Hot", "Fully equipped with live, up-to-date data", "Minutes to hours", "High"],
                 ["Warm", "Equipment in place, data needs restoring", "Hours to days", "Medium"],
                 ["Cold", "Space and power only", "Days to weeks", "Low"],
             ]},
        ],
        "quiz": [
            ("What is the difference between a Type 1 and Type 2 hypervisor?", "Type 1 runs directly on hardware; Type 2 runs on an operating system."),
            ("In SaaS, what does the client manage?", "User accounts and data."),
            ("What is device hardening?", "Removing unneeded ports, apps, permissions and access to reduce vulnerabilities."),
            ("Which disaster recovery site is fastest to switch to?", "A hot site."),
        ],
        "activity": {
            "title": "Choose a cloud model",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Three clients: a start-up building its own web app; a school wanting email; a company that needs full control of its servers.",
                "Recommend IaaS, PaaS or SaaS for each.",
                "Explain what each client would still be responsible for.",
                "Suggest one resilience measure for each.",
            ],
            "success": [
                "Model matches the level of control needed",
                "Responsibilities stated correctly",
                "Resilience measure is realistic",
            ],
        },
        "exit": [
            "Give one drawback of virtualisation.",
            "Which cloud model gives the client the most control?",
            "Why use offsite backups?",
        ],
    },
    {
        "area": "core",
        "file": "core/17-security-threats-and-vulnerabilities.pptx",
        "title": "Security Threats and Vulnerabilities",
        "unit": "Core Paper 2",
        "spec": "8.1, 8.2",
        "pages": [CP2],
        "objectives": [
            "Identify the confidential information organisations hold and why it must be protected.",
            "Describe technical and human threats.",
            "Describe technical and physical vulnerabilities.",
            "Explain the impacts of a successful attack.",
        ],
        "starter": "You receive a text saying your parcel could not be delivered, with a link to rebook. "
                   "What makes it suspicious?",
        "slides": [
            {"type": "compare", "title": "Why confidentiality matters",
             "left": ("What organisations hold", [
                 "HR data: salaries and staff details",
                 "Commercial data: clients, IP, sales, contracts",
                 "Access information: passwords, MFA, PINs, biometrics",
             ]),
             "right": ("If it is not protected", [
                 "Regulatory non-compliance",
                 "Loss of trust and reputational damage",
                 "Fines, refunds, lost contracts",
                 "Legal action and reduced security",
             ])},
            {"type": "cards", "title": "Technical threats",
             "cards": [
                 ("Botnets and DoS / DDoS", "Networks of hijacked devices flooding a service until it fails."),
                 ("Malicious hacking", "Hacktivists, nation states, organised crime. Brute force, SQL injection, cross-site scripting, buffer overflow."),
                 ("Malware", "Viruses, worms, keyloggers, ransomware, spyware, remote access trojans."),
                 ("Social engineering", "Phishing, spear phishing, smishing, vishing, pharming, watering holes, USB baiting."),
                 ("DNS attacks", "Redirecting traffic to fake sites."),
                 ("Open Wi-Fi", "Unsecured networks that let attackers intercept traffic."),
             ]},
            {"type": "table", "title": "Human threats and responses",
             "header": ["Threat", "Mitigation"],
             "widths": [3, 5],
             "rows": [
                 ["Human error", "File properties, confirmation boxes, staff training"],
                 ["Malicious employees", "Immediate removal and account suspension"],
                 ["Disguised criminals", "Visitor escorts and ID checks"],
                 ["Poor cyber hygiene", "Lock unattended PCs, never write passwords down, use a password manager"],
             ]},
            {"type": "compare", "title": "Vulnerabilities",
             "left": ("Technical", [
                 "Weak encryption",
                 "Poor password policy",
                 "No multi-factor authentication",
                 "Out-of-date hardware, software and firmware",
                 "Legacy compatibility issues and zero-day bugs",
             ]),
             "right": ("Physical", [
                 "Poor access control and tailgating",
                 "Shoulder surfing and vandalism",
                 "Environmental risk at the location",
                 "Hardware that is not rugged enough",
                 "Natural disasters",
             ]),
             "notes": "Impacts of a successful attack: loss or leaking of sensitive data, unauthorised access, data corruption, service disruption, unauthorised physical access."},
            {"type": "terms", "terms": [
                ("Phishing", "mass fraudulent emails that trick people into giving away details."),
                ("Spear phishing", "phishing targeted at one person or organisation."),
                ("Smishing / vishing", "phishing by text message / by phone call."),
                ("Pharming", "redirecting users from a real website to a fake one."),
                ("Zero-day", "a flaw exploited before a patch exists."),
                ("Tailgating", "following an authorised person through a secure door."),
            ]},
        ],
        "quiz": [
            ("What is the difference between phishing and spear phishing?", "Phishing is mass; spear phishing is targeted."),
            ("What does ransomware do?", "Encrypts or blocks data and demands payment to release it."),
            ("Give one mitigation for disguised criminals.", "Visitor escorts or ID checks."),
            ("What is a zero-day vulnerability?", "A flaw that attackers exploit before a patch is available."),
            ("Name two impacts of a successful attack.", "Any two of: data loss or leaks, unauthorised access, data corruption, service disruption."),
        ],
        "activity": {
            "title": "Spot the phish",
            "time": "15 minutes",
            "format": "Pairs",
            "steps": [
                "Your teacher shows six messages: some genuine, some phishing, smishing or vishing scripts.",
                "Decide which are malicious.",
                "Highlight every warning sign you can find.",
                "Write one tip for staff that would have stopped each attack.",
            ],
            "success": [
                "All malicious messages identified",
                "Warning signs named, e.g. spoofed domain, urgency",
                "Tips are clear and practical",
            ],
        },
        "exit": [
            "Which type of data would a competitor most want to steal?",
            "What is tailgating?",
            "Why are out-of-date systems a vulnerability?",
        ],
    },
    {
        "area": "core",
        "file": "core/18-threat-mitigation-cia-and-iaaa.pptx",
        "title": "Threat Mitigation, the CIA Triad and IAAA",
        "unit": "Core Paper 2",
        "spec": "8.3, 8.4",
        "pages": [CP2],
        "objectives": [
            "Describe a range of threat mitigation techniques.",
            "Explain internet security processes such as firewall rules and network segregation.",
            "Explain how confidentiality, integrity and availability reinforce each other.",
            "Describe the four stages of the IAAA model.",
        ],
        "starter": "Your bank app asks for your password and then a code from a text message. "
                   "Why does it bother with both?",
        "slides": [
            {"type": "cards", "title": "Threat mitigation techniques",
             "cards": [
                 ("Protect devices", "Security settings, anti-malware, device hardening, updates to software, firmware and drivers."),
                 ("Control access", "User access policies, software access control, MFA, password managers."),
                 ("Protect data", "Encryption (hashing, symmetric, asymmetric) and full, incremental or differential backups."),
                 ("Protect networks", "Intrusion detection, VPNs, air gaps, API certification."),
                 ("People", "Staff vetting and training."),
                 ("Test", "Port scanning and penetration testing (ethical hacking)."),
             ]},
            {"type": "compare", "title": "Internet security processes",
             "left": ("Firewall configuration", [
                 "Inbound and outbound rules",
                 "Traffic type rules",
                 "Application rules",
                 "IP address rules",
             ]),
             "right": ("Network protection", [
                 "Segregation: virtual, physical or offline",
                 "Network monitoring",
                 "Port scanning to find open ports",
             ])},
            {"type": "cards", "title": "The CIA triad",
             "cards": [
                 ("Confidentiality", "Controlling who can access data."),
                 ("Integrity", "Making sure data has not been tampered with. Partly achieved by keeping it confidential."),
                 ("Availability", "Making sure data is accessible and usable when needed. Partly achieved by maintaining integrity."),
             ],
             "notes": "The three properties reinforce each other rather than standing alone."},
            {"type": "process", "title": "The IAAA model",
             "steps": [
                 ("Identification", "Recognise who someone claims to be: username, card, or biometric."),
                 ("Authentication", "Verify that claim: password, MFA or biometrics."),
                 ("Authorisation", "Allow only what they are permitted: role-based access, access control lists."),
                 ("Accountability", "Trace actions back to the user: audit logs and activity monitoring."),
             ]},
        ],
        "quiz": [
            ("What are the three types of encryption named in the specification?", "Hashing, symmetric and asymmetric."),
            ("What is an air gap?", "Physically isolating a system from other networks."),
            ("Which part of the CIA triad is breached if data is altered without permission?", "Integrity."),
            ("Which IAAA stage checks what a logged-in user is allowed to do?", "Authorisation."),
            ("How does an audit log support accountability?", "It records actions so they can be traced to a user."),
        ],
        "activity": {
            "title": "Defend the small business",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "A 20-person accountancy firm has one server, shared Wi-Fi, no backups and a shared admin password.",
                "Identify five threats to the business.",
                "Choose a mitigation for each and link it to C, I or A.",
                "Design a simple IAAA process for staff logging in to the server.",
            ],
            "success": [
                "Each mitigation matches its threat",
                "CIA links are correct",
                "All four IAAA stages included",
            ],
        },
        "exit": [
            "Give one example of multi-factor authentication.",
            "Which CIA property does a DDoS attack target?",
            "Why is a shared admin password bad for accountability?",
        ],
    },
    # ------------------------------------------------------------------ ESP
    {
        "area": "core",
        "file": "core/19-employer-set-project-overview.pptx",
        "title": "The Employer Set Project",
        "unit": "Core Component",
        "spec": "Employer Set Project, all pathways",
        "pages": [ESP],
        "objectives": [
            "Explain the weighting and conditions of the Employer Set Project.",
            "Describe what happens in the pre-task and in each assessed task.",
            "Compare the three ESP pathways.",
            "Plan how to prepare for each task.",
        ],
        "starter": "The ESP is worth 20% of your whole qualification. What do you think employers most want to see "
                   "from you in a project like this?",
        "slides": [
            {"type": "bullets", "title": "What is the ESP?",
             "bullets": [
                 "Worth 40% of the core and 20% of the whole qualification.",
                 "Externally set, taken under supervised, controlled conditions.",
                 "Assesses the six core skills together, in one connected project.",
                 "Three pathways: Digital Infrastructure and Network Cabling, Cyber Security, and Digital Support Technician.",
             ],
             "callout": "Every task is linked to English, maths and digital competencies such as E4, M6 or D2. "
                        "They show exactly which skills each task develops."},
            {"type": "process", "title": "The same shape for every pathway",
             "steps": [
                 ("Pre-task", "Research the industry context. Not assessed."),
                 ("Task 1", "Plan the project: Gantt chart, resource and cost plan, rationale."),
                 ("Task 2", "Find and fix defects in a simulation or support tickets."),
                 ("Task 3", "Design a solution for a client and a third party."),
                 ("Task 4a", "Develop the solution: robust, secure, organised, user-friendly."),
                 ("Task 4b", "Reflective evaluation against the brief."),
             ]},
            {"type": "table", "title": "The three pathways",
             "header": ["Pathway", "Task 2", "Task 3 design"],
             "widths": [2.4, 3.2, 3.2],
             "rows": [
                 ["Digital Infrastructure and Network Cabling", "Fix defects in a network simulation", "Network diagram with annotations"],
                 ["Cyber Security", "Fix security defects in a network simulation", "Layered security plan"],
                 ["Digital Support Technician", "Support tickets plus a simulation, using root cause analysis", "Needs analysis"],
             ],
             "notes": "Simulations are usually Cisco Packet Tracer files."},
            {"type": "cards", "title": "What Task 4a looks for",
             "cards": [
                 ("Robustness", "Resilience and redundancy: backups, fallbacks, UPS."),
                 ("Security", "Anti-malware and firewall configuration, user roles and permissions, hardening, air gaps."),
                 ("Organisation", "Server configuration, node deployment, media, subnetting."),
                 ("User experience", "End-user devices, connections, back-end systems, access and availability."),
             ]},
            {"type": "bullets", "title": "How to prepare",
             "bullets": [
                 "Practise Gantt charts and cost plans until they are quick.",
                 "Get fluent in Packet Tracer: ping, tracert, device configuration, subnetting.",
                 "Practise structured troubleshooting and documenting each test.",
                 "Practise drawing clear network diagrams with correct symbols and IP addresses.",
                 "Write reflections using a model such as Gibbs.",
             ],
             "callout": "Document as you go. Marks come from the evidence you record, not just from fixing the fault."},
        ],
        "quiz": [
            ("What percentage of the total qualification is the ESP?", "20%."),
            ("What two planning documents does Task 1 require, apart from the rationale?", "A Gantt chart and a resource and cost plan."),
            ("What does the Cyber Security pathway produce in Task 3?", "A security plan."),
            ("Name the four considerations in Task 4a.", "Robustness, security, organisation and user experience."),
        ],
        "activity": {
            "title": "Mini ESP: Task 2 practice",
            "time": "40 minutes",
            "format": "Individual",
            "steps": [
                "Open the practice Packet Tracer file from your teacher, which contains three faults.",
                "Use ping and tracert to locate each fault.",
                "Fix each one and record the test before and after.",
                "Write two sentences explaining each root cause.",
            ],
            "success": [
                "All three faults found and fixed",
                "Each test is recorded with expected and actual results",
                "Root causes explained clearly",
            ],
            "notes": "Build a small network with a wrong gateway, a wrong subnet mask and a shut-down switch port.",
        },
        "exit": [
            "Which ESP task do you feel least ready for?",
            "What evidence should you record in Task 2?",
            "Name one thing to include in a reflective evaluation.",
        ],
    },
]
