"""Cyber Security specialism decks."""

CS1 = "02-occupational-specialisms/cyber-security/01-security-procedures-and-controls.md"
CS2 = "02-occupational-specialisms/cyber-security/02-remediation-and-risk-assessment.md"
CS3 = "02-occupational-specialisms/cyber-security/03-sources-of-knowledge.md"

DECKS = [
    {
        "area": "cyber",
        "file": "cyber-security/01-governance-itsm-and-frameworks.pptx",
        "title": "Security Governance, ITSM and Frameworks",
        "unit": "Cyber Security Content Area 1",
        "spec": "1.1, 1.2, 1.7, 1.8, 1.10, 1.24",
        "pages": [CS1],
        "objectives": [
            "Explain the purpose of information security governance and the six IT governance principles.",
            "Describe the core ITSM processes and the ITIL service lifecycle.",
            "Describe frameworks and standards that support an ISMS.",
            "Assess whether a security request is valid.",
        ],
        "starter": "A manager emails the helpdesk asking for admin rights 'just for today'. What questions should you ask before saying yes?",
        "slides": [
            {"type": "bullets", "title": "Why governance?",
             "bullets": [
                 "Investigate, control, communicate and report cyber risk.",
                 "Provide a security framework: defined roles, policies and security activities.",
                 "Manage compliance with law and standards such as ISO 27001, data protection and FOI.",
                 "Align organisational priorities with reducing cyber threats.",
             ],
             "callout": "Governance decides who is responsible for security and how it is checked. Without it, controls exist but nobody owns them."},
            {"type": "cards", "title": "Six IT governance principles",
             "cards": [
                 ("Responsibility", "Everyone understands their security role, e.g. asset owner, data controller."),
                 ("Strategy", "Secure by design, planning for future needs like cloud."),
                 ("Acquisition", "Every purchase evaluated for risk, benefit and cost."),
                 ("Performance", "Enough capability to guarantee confidentiality, integrity and availability."),
                 ("Conformance", "IT use complies with legislation and regulation."),
                 ("Human behaviour", "Technical and non-technical controls both considered."),
             ]},
            {"type": "cards", "title": "IT service management (ITSM) processes",
             "cards": [
                 ("Service requests", "Handle and track queries and incidents, e.g. reporting a suspected cyber incident."),
                 ("Knowledge management", "Keep documentation current, e.g. standard hardened builds."),
                 ("IT asset management", "Track hardware, software and configuration in a CMDB."),
                 ("Problem and incident", "Root cause analysis and coordinated response."),
                 ("Change management", "Changes agreed and recorded, e.g. a new firewall rule."),
             ]},
            {"type": "process", "title": "The ITIL service lifecycle",
             "steps": [
                 ("Strategy", "Align services with business objectives."),
                 ("Design", "Design services for people, process, product and partners."),
                 ("Transition", "Build and deploy with managed change."),
                 ("Operation", "Fulfil requests, resolve failures, run routine tasks."),
                 ("Improvement", "Continual service improvement."),
             ]},
            {"type": "table", "title": "Frameworks and standards for an ISMS",
             "header": ["Name", "Purpose"],
             "widths": [2.6, 6],
             "rows": [
                 ["COBIT", "Governance and management of IT"],
                 ["SOC 2", "Assesses security, availability, integrity, confidentiality and privacy controls"],
                 ["NIST", "Helps organisations manage cyber risk"],
                 ["ISO 27001", "Establish, implement, maintain and improve an ISMS"],
                 ["ISO/IEC 38500", "Framework for IT governance"],
                 ["Cyber Essentials (Plus)", "Government-backed accreditation scheme"],
                 ["PCI DSS", "Reduces payment card fraud"],
             ],
             "notes": "An ISMS (information security management system) creates policies such as an information security policy and an AUP."},
            {"type": "cards", "title": "Assessing a security request",
             "cards": [
                 ("Origin", "Where did the request really come from?"),
                 ("Reason", "Is there a genuine business need?"),
                 ("Requestor", "What is their status and current permission level?"),
                 ("Sensitivity", "Would it expose personal data?"),
                 ("New risk", "What risk would it introduce?"),
                 ("Compliance", "Does it meet regulatory requirements?"),
             ]},
        ],
        "quiz": [
            ("Which governance principle says every purchase must be evaluated for risk?", "Acquisition."),
            ("What is a CMDB used for?", "Tracking IT assets and their configuration."),
            ("Name the five stages of the ITIL lifecycle.", "Strategy, design, transition, operation, continual improvement."),
            ("Which standard is used to certify an ISMS?", "ISO 27001."),
            ("Give three things to check before approving a security request.", "Any three of: origin, reason, requestor, sensitivity, new risk, compliance."),
        ],
        "activity": {
            "title": "Request triage",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Your teacher gives you five security requests (e.g. open a firewall port, grant admin rights, share a folder externally).",
                "Assess each against the six request factors.",
                "Approve, reject or escalate each one.",
                "Write a short, professional reply to each requestor.",
            ],
            "success": [
                "Every factor considered",
                "Decisions are justified",
                "Replies are polite and clear",
            ],
        },
        "exit": [
            "Which ITSM process would handle adding a new firewall rule?",
            "Why does governance need defined roles?",
            "What is the difference between a framework and a standard?",
        ],
    },
    {
        "area": "cyber",
        "file": "cyber-security/02-secure-design-and-layered-protection.pptx",
        "title": "Secure Design and Layered Protection",
        "unit": "Cyber Security Content Area 1",
        "spec": "1.3, 1.4, 1.5, 1.6, 1.23",
        "pages": [CS1],
        "objectives": [
            "Describe protection methods for hardware, operating systems, networks, software and cloud.",
            "Apply the five secure design aims to network infrastructure.",
            "Identify OS components that support an investigation.",
            "Explain core terms: CIA, IAAA, defence in depth, reliability and assurance.",
        ],
        "starter": "A castle has a moat, walls, a gate, guards and a keep. How is that like protecting a network?",
        "slides": [
            {"type": "table", "title": "Protection methods by layer",
             "header": ["Layer", "Methods"],
             "widths": [1.8, 7],
             "rows": [
                 ["Hardware", "Hardware protection, device hardening, locked cages, CCTV, key-card doors"],
                 ["Operating system", "Patches with snapshot rollback, OS hardening"],
                 ["Network", "Segmentation to limit lateral movement, monitoring, network hardening, firewalls"],
                 ["Software", "Anti-malware, SSO, MFA, RMM, vulnerability scanning, PAM, application firewalls"],
                 ["Cloud", "Log auditing, access controls, MFA including a 'somewhere you are' factor"],
             ],
             "notes": "This is defence in depth: if one layer fails, the next still protects the system."},
            {"type": "cards", "title": "Five secure design aims",
             "cards": [
                 ("Establish the context", "Adopt zero trust, define acceptable risk, map where sensitive data lives."),
                 ("Make compromise difficult", "Reduce the attack surface, use proven solutions, audit operations."),
                 ("Make disruption difficult", "Build resilience and scalability, plan for third-party failure."),
                 ("Make detection easier", "Collect logs, keep monitoring separate from operations, learn what normal looks like."),
                 ("Reduce the impact", "Segment networks, test recovery, separate duties, anonymise data."),
             ]},
            {"type": "compare", "title": "Operating systems and investigation",
             "left": ("OS types and functions", [
                 "Client: Windows, macOS, Linux",
                 "Mobile: Android, iOS",
                 "Server: Windows Server, Linux",
                 "Functions: security, memory, processor, device and file management",
             ]),
             "right": ("Useful evidence sources", [
                 "Windows registry",
                 "Linux configuration files",
                 "macOS library and preference files",
                 "Network and traffic logs",
                 "File system: NTFS, FAT32, exFAT, APFS, ext4",
                 "Running processes",
             ])},
            {"type": "compare", "title": "Physical and virtual servers",
             "left": ("Physical servers", [
                 "Applications run directly on hardware",
                 "Full access to hardware resources",
             ]),
             "right": ("Virtualisation", [
                 "Virtual servers: many isolated OS instances on one machine",
                 "Containers: portable packages holding only what an app needs",
                 "Isolation adds security and portability",
             ])},
            {"type": "terms", "terms": [
                ("Confidentiality", "access restricted to authorised users."),
                ("Integrity", "data cannot be changed without authorisation."),
                ("Availability", "authorised users can access data when needed."),
                ("IAAA", "identification, authentication, authorisation, accountability."),
                ("Defence in depth", "layered security so one failure does not compromise everything."),
                ("Assurance", "confirming that security requirements have actually been met."),
            ]},
        ],
        "quiz": [
            ("What does segmentation limit?", "Lateral movement of attackers or malware."),
            ("What is zero trust?", "Never trusting any user or device by default, even inside the network."),
            ("Where would you look for configuration evidence on a Windows PC?", "The registry."),
            ("What is a container?", "An isolated, portable package holding only what an application needs to run."),
            ("Define defence in depth.", "Layered security so a single failure does not compromise the whole system."),
        ],
        "activity": {
            "title": "Layer up",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Draw a simple network for a GP surgery: reception PCs, a server, Wi-Fi and cloud records.",
                "Add at least one protection at each of the five layers.",
                "Mark where logs would be collected.",
                "Explain how an attacker who phishes a receptionist would be stopped or detected.",
            ],
            "success": [
                "All five layers protected",
                "Logging separate from operational systems",
                "Attack path clearly explained",
            ],
        },
        "exit": [
            "Which secure design aim does network segmentation support?",
            "Name one file system and the OS that uses it.",
            "Why keep monitoring systems separate from operational ones?",
        ],
    },
    {
        "area": "cyber",
        "file": "cyber-security/03-security-controls-and-disaster-recovery.pptx",
        "title": "Security Controls and Disaster Recovery",
        "unit": "Cyber Security Content Area 1",
        "spec": "1.11 to 1.16",
        "pages": [CS1],
        "objectives": [
            "Explain the purpose and importance of a disaster recovery plan.",
            "Describe the stages of implementing a DRP.",
            "Give physical, technical and procedural examples of preventative, corrective and compensating controls.",
            "Select and apply controls to protect personal, physical and environmental security.",
        ],
        "starter": "A fire alarm goes off in the server room. What should happen in the next ten minutes, and who decides?",
        "slides": [
            {"type": "bullets", "title": "Why have a DRP?",
             "bullets": [
                 "A formal document for responding to natural disasters, power cuts, cyber attacks and other disruption.",
                 "Minimises MTTR and interruption to normal operations.",
                 "Limits damage and economic impact.",
                 "Sets up alternative ways of working in advance.",
                 "Reveals gaps, such as untrained staff.",
             ],
             "callout": "A DRP written during a disaster is too late. The plan's value comes from deciding things calmly beforehand."},
            {"type": "process", "title": "Implementing a DRP",
             "steps": [
                 ("Define scope", "Environmental, organisational, departmental, individual."),
                 ("Gather", "Outage history, inventories, contacts."),
                 ("Risk assess", "Likelihood and impact on business as usual."),
                 ("Create", "Systems, staff roles, budget."),
                 ("Approve", "Sign-off."),
                 ("Test", "Scope, frequency, run, review, amend."),
                 ("Improve", "Audits and gap analysis."),
             ]},
            {"type": "table", "title": "Three control types in cyber security",
             "header": ["Control", "Physical", "Technical", "Procedural"],
             "widths": [1.7, 2.5, 2.5, 2.5],
             "rows": [
                 ["Preventative", "Locks, barriers, guards, biometrics, CCTV", "Firewalls, allow and deny lists, sandboxing, hardening", "Separation of duties, RBAC"],
                 ["Corrective", "Sprinklers, gas suppression", "Patching, disconnecting or quarantining infected systems", "SOPs, invoking the DRP"],
                 ["Compensating", "Segregation of duties, key-code access logs", "Encryption", "Awareness training, simulated attacks, monitoring SOPs"],
             ]},
            {"type": "process", "title": "Protecting personal, physical and environmental security",
             "steps": [
                 ("Review the risk", "Gather logs, security events and user reports."),
                 ("Select controls", "Preventative, corrective or compensating."),
                 ("Apply them", "Put the controls in place."),
                 ("Comply", "Follow the law (e.g. DPA 2018) and organisational policy."),
             ]},
        ],
        "quiz": [
            ("Give two reasons a DRP is important.", "Any two, e.g. minimises MTTR, limits damage, prepares alternatives, finds gaps."),
            ("What comes after creating the DRP?", "Getting it approved (sign-off)."),
            ("Quarantining a virus is which type of control?", "Corrective."),
            ("Give a technical compensating control.", "Encryption."),
        ],
        "activity": {
            "title": "Tabletop DR exercise",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "Scenario: a burst pipe floods the ground floor server room of a small council office.",
                "Walk through the first four hours minute by minute.",
                "Identify which controls worked, failed or were missing.",
                "List three amendments to the DRP.",
            ],
            "success": [
                "Actions follow a logical order",
                "Controls classified correctly",
                "Amendments are specific",
            ],
        },
        "exit": [
            "Why must a DRP be tested?",
            "Name one preventative control for a server room.",
            "What is a compensating control for?",
        ],
    },
    {
        "area": "cyber",
        "file": "cyber-security/04-cryptography-and-digital-certificates.pptx",
        "title": "Cryptography and Digital Certificates",
        "unit": "Cyber Security Content Areas 1 and 2",
        "spec": "1.9, 1.17 to 1.20, 2.22",
        "pages": [CS1, CS2],
        "objectives": [
            "Explain the purpose and characteristics of cryptography, including hashing.",
            "Compare symmetric and asymmetric encryption and where each is used.",
            "Describe digital certificates, their features and types.",
            "Describe how a certificate is generated and managed.",
        ],
        "starter": "Why does a website show a padlock? What do you think it actually proves?",
        "slides": [
            {"type": "cards", "title": "What cryptography provides",
             "cards": [
                 ("Confidentiality", "Only intended recipients can decrypt the data."),
                 ("Integrity", "Data cannot be changed in transit without detection (HMAC)."),
                 ("Authenticity", "The recipient can verify the sender with a digital signature."),
                 ("Non-repudiation", "The sender cannot deny writing the message (MAC)."),
             ],
             "notes": "When transmitting data: identify its CIA requirements, use asymmetric encryption to prevent eavesdropping, and verify it with these cryptographic properties."},
            {"type": "compare", "title": "Encryption and hashing",
             "left": ("Encryption", [
                 "Reversible with the right key",
                 "Symmetric: one shared key, fast, e.g. card payments and data at rest",
                 "Asymmetric: public and private key pair, e.g. email and TLS",
             ]),
             "right": ("Hashing", [
                 "One way: cannot be reversed",
                 "Fixed-length output",
                 "Used to store passwords",
                 "Any change to the input changes the hash",
             ])},
            {"type": "compare", "title": "Encryption tools as risk mitigation",
             "left": ("Data in transit", [
                 "TLS: end-to-end encryption for email, web and messaging",
                 "SSL: the legacy protocol TLS replaced",
                 "Both rely on asymmetric encryption",
             ]),
             "right": ("Data at rest (DARE)", [
                 "Full Disk Encryption (FDE): protects a stolen laptop",
                 "File-Based Encryption (FBE): protects individual files and folders",
                 "Both rely on symmetric encryption",
             ])},
            {"type": "cards", "title": "Digital certificates",
             "cards": [
                 ("Purpose", "Prove the authenticity of a device, server or user using asymmetric cryptography."),
                 ("Features", "Holder name, serial number, expiry date, holder's public key, issuer's signature."),
                 ("Types", "Server-side (client checks server), client-side (client proves itself), code signing (OS checks software)."),
             ]},
            {"type": "process", "title": "Generating a certificate",
             "steps": [
                 ("Key pair", "Generate a public and private key."),
                 ("CSR", "Create a Certificate Signing Request."),
                 ("CA signs", "A trusted Certificate Authority issues and signs it."),
                 ("Install", "Install it on the server or client."),
             ],
             "caption": "Management tools monitor expiry, revoke early, auto-renew, audit deployment and diagnose certificate problems."},
        ],
        "quiz": [
            ("Why is hashing used for passwords rather than encryption?", "It is one way, so the stored hash cannot be turned back into the password."),
            ("Which type of encryption protects a stolen laptop's drive?", "Symmetric, via full disk encryption."),
            ("What does a digital signature prove?", "The authenticity of the sender."),
            ("What is a CSR?", "A Certificate Signing Request sent to a Certificate Authority."),
            ("Name two features of a digital certificate.", "Any two of: holder name, serial number, expiry, public key, issuer signature."),
        ],
        "activity": {
            "title": "Inspect and hash",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Open a secure website and view its certificate details.",
                "Record the issuer, expiry date, key type and certificate type.",
                "Use a hashing tool to hash a short sentence, then change one letter and hash it again.",
                "Explain what each result shows about integrity.",
            ],
            "success": [
                "Certificate details recorded accurately",
                "Hash change observed and explained",
                "Correct use of key terms",
            ],
        },
        "exit": [
            "What is the difference between TLS and SSL?",
            "Which property does HMAC provide?",
            "Why must certificates be monitored for expiry?",
        ],
    },
    {
        "area": "cyber",
        "file": "cyber-security/05-cyber-law-and-ethics.pptx",
        "title": "Cyber Law and Ethics",
        "unit": "Cyber Security Content Area 1",
        "spec": "1.21, 1.22",
        "pages": [CS1],
        "objectives": [
            "Describe the legislation that applies to cyber security work.",
            "Explain the UK Cyber Security Council Code of Ethics.",
            "Explain the BCS code of conduct.",
            "Apply legal and ethical thinking to workplace scenarios.",
        ],
        "starter": "You find a colleague's password written on a sticky note. You could log in and prove how insecure it is. Should you?",
        "slides": [
            {"type": "table", "title": "Legislation for cyber security (1)",
             "header": ["Law", "What it means for cyber security"],
             "widths": [3.2, 5.4],
             "rows": [
                 ["Data Protection Act 2018", "Protect personal data, detect security events, minimise incident impact"],
                 ["Computer Misuse Act 1990", "Criminalises unauthorised access, access with intent, modification, and supplying tools"],
                 ["Investigatory Powers Act 2016", "Authorises law enforcement to obtain communications data"],
                 ["Human Rights Act 1998", "Protects human rights; binds all public authorities"],
                 ["Telecommunications (Security) Act 2021", "Providers must prevent, remedy and disclose security compromises"],
             ]},
            {"type": "table", "title": "Legislation for cyber security (2)",
             "header": ["Law", "What it means for cyber security"],
             "widths": [3.2, 5.4],
             "rows": [
                 ["Freedom of Information Act 2000", "Exempts some security bodies, such as the NCSC, from disclosure"],
                 ["NIS Regulations 2018", "Security baseline for essential services and digital service providers"],
                 ["Official Secrets Act 1989", "Protects security and intelligence information"],
                 ["Wireless Telegraphy Act 2006", "Regulates wireless devices; criminalises unauthorised interception"],
             ]},
            {"type": "cards", "title": "UK Cyber Security Council Code of Ethics",
             "cards": [
                 ("Credibility", "Be accountable and act ethically."),
                 ("Integrity", "Be honest and obey the law."),
                 ("Professionalism", "Share knowledge, base practice on evidence, correct misinformation."),
                 ("Responsibility and respect", "Take ownership, safeguard data, declare conflicts of interest, champion inclusion."),
             ]},
            {"type": "cards", "title": "BCS code of conduct",
             "cards": [
                 ("Make IT for everyone", "Share professional information."),
                 ("Show what you know", "Work within your competence, keep learning, know the law."),
                 ("Respect the organisation", "Due care, no disclosures for personal gain, do not exploit inexperience."),
                 ("Keep IT professional", "Uphold the profession, raise standards, support colleagues."),
             ]},
        ],
        "quiz": [
            ("Which Act makes supplying hacking tools an offence?", "The Computer Misuse Act 1990."),
            ("Which regulations set a security baseline for operators of essential services?", "The Network and Information Systems (NIS) Regulations 2018."),
            ("Which Act criminalises intercepting someone else's Wi-Fi traffic?", "The Wireless Telegraphy Act 2006."),
            ("Name two principles of the UK Cyber Security Council Code of Ethics.", "Any two of: credibility, integrity, professionalism, responsibility and respect."),
        ],
        "activity": {
            "title": "Ethics dilemmas",
            "time": "20 minutes",
            "format": "Small groups",
            "steps": [
                "Discuss the starter dilemma and three more from your teacher.",
                "For each, name any law that would be broken.",
                "Name the ethical principle that guides the right action.",
                "Agree what a professional would actually do.",
            ],
            "success": [
                "Laws named accurately",
                "Ethical principles applied, not just opinions",
                "Actions are realistic and professional",
            ],
            "notes": "Dilemma ideas: finding a vulnerability in a supplier's website; being asked to monitor a colleague's email; a friend asking you to recover their ex's social media password.",
        },
        "exit": [
            "What makes 'ethical hacking' legal?",
            "Why must you declare a conflict of interest?",
            "Which Act gives the NCSC an exemption from FOI requests?",
        ],
    },
    {
        "area": "cyber",
        "file": "cyber-security/06-threats-threat-actors-and-intelligence.pptx",
        "title": "Threats, Threat Actors and Threat Intelligence",
        "unit": "Cyber Security Content Areas 2 and 3",
        "spec": "2.2, 2.3, 3.8",
        "pages": [CS2, CS3],
        "objectives": [
            "Recognise social engineering, denial of service, malware and password attacks and their indicators.",
            "Describe threat actors and their motivations.",
            "Explain the value of threat intelligence.",
            "Describe cyber security impacts on critical national infrastructure.",
        ],
        "starter": "Who do you think is most likely to attack a school's network: a nation state, a criminal gang or a student? Why?",
        "slides": [
            {"type": "table", "title": "Social engineering",
             "header": ["Attack", "How it works", "Warning signs"],
             "widths": [1.8, 3.4, 3.4],
             "rows": [
                 ["Phishing", "Mass fraudulent messages", "Spoofed domains, poor writing, urgency, attachments"],
                 ["Spear phishing", "Targeted at one person", "Personal details used to build trust"],
                 ["Vishing", "Fraudulent phone calls", "Pressure; claims to be HMRC or the bank"],
                 ["Smishing", "Fraudulent texts", "Suspicious links"],
                 ["Shoulder surfing", "Watching someone type credentials", "Someone standing too close"],
                 ["Dumpster diving", "Searching discarded paperwork", "Unshredded documents in bins"],
             ]},
            {"type": "cards", "title": "Malware",
             "cards": [
                 ("Virus", "Spreads and damages data or software."),
                 ("Adware", "Unwanted ads, browser changes, slow performance."),
                 ("Ransomware", "Blocks, deletes or encrypts data for payment."),
                 ("Trojan", "Disguised as legitimate software."),
                 ("Botnet", "Network of compromised devices under attacker control."),
                 ("Spyware", "Hides and steals sensitive data."),
             ],
             "notes": "Most malware is spotted through scan reports, slower devices or unusual behaviour."},
            {"type": "table", "title": "Other attacks and how to spot them",
             "header": ["Attack", "Indicators"],
             "widths": [2.6, 6],
             "rows": [
                 ["DoS / DDoS", "Degraded performance, traffic spikes, repeated requests from one source, outages"],
                 ["Zero-day", "Vendor statistics, unusual scanning, ML-based monitoring, odd interaction patterns"],
                 ["Brute force / dictionary", "More network activity, repeated failed logins from one IP"],
                 ["Man in the middle", "Browser security warnings, repeated unexpected disconnections"],
             ]},
            {"type": "cards", "title": "Threat actors",
             "cards": [
                 ("Cyber criminals", "Financial gain through ransomware, social engineering and malware."),
                 ("Insiders", "Current or former staff misusing access for revenge or gain."),
                 ("Nation states", "Political gain: stealing data, damaging infrastructure."),
                 ("Terrorists", "Disruption for a cause."),
                 ("Hacktivists", "Exposing perceived wrongdoing."),
                 ("Script kiddies", "Inexperienced attackers looking for a challenge."),
             ],
             "notes": "Threat intelligence gathers information to analyse and prioritise threats: finding unknown threats, revealing motivations and supporting fast mitigation decisions."},
            {"type": "cards", "title": "Critical national infrastructure",
             "cards": [
                 ("Energy and water", "Power cuts, surges, loss of gas or water supply, flooding."),
                 ("Finance", "Failed payments and interrupted transfers."),
                 ("Healthcare", "Compromised patient records, disrupted treatment."),
                 ("Communications", "Service loss, eavesdropping, impersonation."),
                 ("Government and defence", "Interrupted policy and reduced defence capability."),
                 ("Transport and supply", "Disrupted travel, emergency dispatch, food and raw materials."),
             ]},
        ],
        "quiz": [
            ("What is the difference between vishing and smishing?", "Vishing is by phone call; smishing is by text message."),
            ("Which malware disguises itself as legitimate software?", "A trojan."),
            ("Give one sign of a brute force attack.", "Repeated failed logins from one IP address."),
            ("Which threat actor misuses authorised access?", "An insider."),
            ("Give one impact of an attack on healthcare infrastructure.", "Compromised patient records or disrupted treatment."),
        ],
        "activity": {
            "title": "Threat profile",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Choose an organisation: a hospital, a football club, or an online retailer.",
                "Identify the three most likely threat actors and their motives.",
                "For each actor, name the attack they would most likely use and its indicators.",
                "Rank the threats by likelihood and severity.",
            ],
            "success": [
                "Motives match the organisation",
                "Indicators are specific",
                "Ranking is justified",
            ],
        },
        "exit": [
            "Which threat actor worries you most for a small business, and why?",
            "What is a zero-day attack?",
            "How does threat intelligence help defenders?",
        ],
    },
    {
        "area": "cyber",
        "file": "cyber-security/07-vulnerability-assessment-and-penetration-testing.pptx",
        "title": "Vulnerability Assessment and Penetration Testing",
        "unit": "Cyber Security Content Area 2",
        "spec": "2.4, 2.5, 2.6, 2.8, 2.9, 2.17",
        "pages": [CS2],
        "objectives": [
            "Describe the stages of a vulnerability assessment and how to scope it.",
            "Use CVEs and CVSS scores to research vulnerabilities.",
            "Compare the strengths and weaknesses of vulnerability assessment tools.",
            "Describe the stages of a penetration test and make evidence-based recommendations.",
        ],
        "starter": "A scanner reports 400 vulnerabilities on your network. You have one day. Where do you start?",
        "slides": [
            {"type": "process", "title": "Vulnerability assessment stages",
             "steps": [
                 ("Identify", "Scan and analyse logs for anomalies."),
                 ("Analyse", "Is it exploitable? How severe?"),
                 ("Identify risk", "Prioritise by associated risk."),
                 ("Remediate", "Update or remove the affected hardware or software."),
                 ("Mitigate", "Apply countermeasures; escalate what remains."),
             ],
             "caption": "Scoping defines the in-scope systems, access needed and vulnerabilities tested. Evaluation classifies each finding's risk and business impact."},
            {"type": "compare", "title": "CVEs and CVSS",
             "left": ("Common Vulnerabilities and Exposures", [
                 "A public list of known vulnerabilities",
                 "Published by vendors and testers",
                 "Each has a unique ID, e.g. CVE-2024-12345",
             ]),
             "right": ("Working with a CVE", [
                 "Research it and score it with CVSS (0 to 10)",
                 "Score reflects impact, exploitability and severity",
                 "Identify affected systems and possible mitigations",
                 "Implement the mitigation",
             ])},
            {"type": "table", "title": "Types of risk assessment",
             "header": ["Type", "Looks for"],
             "widths": [2.2, 6.4],
             "rows": [
                 ["Host based", "Vulnerabilities, configuration and patch status of workstations and servers"],
                 ["Network based", "Possible network attacks and vulnerable systems"],
                 ["Wireless based", "Rogue access points and insecure wireless configuration"],
                 ["Application based", "Known software flaws and misconfigurations, e.g. SQL injection"],
             ]},
            {"type": "table", "title": "Scanning tools: strengths and weaknesses",
             "header": ["Tool", "Finds", "Limitations"],
             "widths": [2, 3.6, 3.4],
             "rows": [
                 ["Infrastructure scanners", "Missing patches, weak passwords, exposed services, missing hardening", "Only known issues; may be inaccurate; can affect live services"],
                 ["Web app scanners", "SQL injection, broken authentication, data exposure, weak encryption", "False positives and negatives; uses resources"],
                 ["Software scanners", "Missing updates and patches, vendor checks", "Need regular updates; business impact hard to judge"],
             ]},
            {"type": "process", "title": "Penetration testing stages",
             "steps": [
                 ("Plan and scope", "Rules of engagement, timing, legal and contractual limits."),
                 ("Reconnaissance", "Topology, OS and applications."),
                 ("Scanning", "Open ports and services."),
                 ("Vulnerability assessment", "Test for exploitable flaws."),
                 ("Exploitation", "Attempt access within agreed limits."),
                 ("Reporting", "Findings and remediation advice."),
             ]},
            {"type": "cards", "title": "Making recommendations",
             "cards": [
                 ("Impact", "Business, operational and infrastructure impact."),
                 ("Cost", "The cost of acting against the cost of not acting."),
                 ("Severity and scope", "Vulnerability type, CVE priority and Proof of Concept results."),
                 ("Resources and time", "People, money, technology and reporting deadlines."),
             ],
             "notes": "Recommendations must be documented logically and pitched in the right technical language for the audience."},
        ],
        "quiz": [
            ("What does CVSS measure, and on what scale?", "The severity of a vulnerability, from 0 to 10."),
            ("Which assessment type would find a rogue access point?", "Wireless based."),
            ("Give one weakness of infrastructure scanners.", "Only find known issues, may be inaccurate, or can affect live services."),
            ("What is agreed in the planning and scoping stage of a pen test?", "Rules of engagement, timing, and legal and contractual boundaries."),
            ("What is a Proof of Concept?", "A demonstration confirming that a vulnerability can really be exploited."),
        ],
        "activity": {
            "title": "Prioritise the findings",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Your teacher provides a list of ten scanner findings with CVSS scores and affected systems.",
                "Rank them for remediation, considering CVSS and business impact.",
                "Choose remediate, mitigate or accept for the top five.",
                "Write a short summary for a non-technical manager.",
            ],
            "success": [
                "Ranking considers more than the CVSS score alone",
                "Actions suit each finding",
                "Summary is jargon-free",
            ],
            "notes": "Include a high CVSS finding on an isolated test box and a medium one on the payment server to show why context matters.",
        },
        "exit": [
            "Why might you fix a CVSS 6 before a CVSS 9?",
            "What is the difference between a vulnerability scan and a pen test?",
            "Name one type of web application vulnerability.",
        ],
    },
    {
        "area": "cyber",
        "file": "cyber-security/08-risk-analysis-and-risk-response.pptx",
        "title": "Risk Analysis and Risk Response",
        "unit": "Cyber Security Content Area 2",
        "spec": "2.7, 2.10, 2.12 to 2.16, 2.18",
        "pages": [CS2],
        "objectives": [
            "Describe the impacts of an exploited vulnerability and types of organisational risk.",
            "Use RTO, RPO, MTBF, MTTD and MTTR to assess impact.",
            "Carry out qualitative and quantitative threat analysis, including ALE.",
            "Conduct a security risk assessment and choose a risk response.",
        ],
        "starter": "A laptop worth 1,000 pounds is stolen twice a year. How much should the company spend each year to prevent it?",
        "slides": [
            {"type": "cards", "title": "Impacts of an exploited vulnerability",
             "cards": [
                 ("Property and resources", "Damage to equipment and systems."),
                 ("Financial loss", "Direct costs and lost business."),
                 ("Reputation", "Loss of customer trust."),
                 ("Fines and prosecution", "e.g. an ICO fine after a data breach."),
                 ("Operations", "Disrupted services."),
                 ("People", "Physical or psychological harm; identity theft."),
             ]},
            {"type": "table", "title": "Organisational risk types",
             "header": ["Risk", "Meaning", "Managed through"],
             "widths": [2.2, 3, 3.6],
             "rows": [
                 ["Compliance", "Not following policy", "Monitoring, compliance controls, exception reports"],
                 ["Safety", "Harm to people, property or environment", "Checks for human error, maintenance audits"],
                 ["Information security", "Data lost, stolen or compromised", "Access control, traffic monitoring, device management, training"],
             ],
             "notes": "Critical systems: look for single points of failure and mission essential functions. Threat factors: environmental, manmade internal and manmade external."},
            {"type": "cards", "title": "Measures of impact",
             "cards": [
                 ("RTO", "Time to recover to an acceptable state."),
                 ("RPO", "Tolerable amount of data loss."),
                 ("MTBF", "How often an asset is likely to fail."),
                 ("MTTD", "Mean Time To Detect: how efficient detection is."),
                 ("MTTR", "Mean Time To Repair a failed system."),
             ]},
            {"type": "compare", "title": "Qualitative and quantitative analysis",
             "left": ("Qualitative", [
                 "RAG rating of business risk",
                 "Fault tree analysis",
                 "FMECA",
                 "CRAMM: scope, evaluate, recommend countermeasures",
                 "FAIR: Factor Analysis of Information Risk",
             ]),
             "right": ("Quantitative", [
                 "Cost overrun and resource use",
                 "SLE x ARO = ALE",
                 "Starter example: 1,000 x 2 = 2,000 pounds a year",
                 "CVSS scores",
             ])},
            {"type": "process", "title": "Conducting a security risk assessment",
             "steps": [
                 ("Identify", "Find potential risks."),
                 ("Score", "Likelihood x severity = risk score and RAG rating."),
                 ("Weigh up", "Asset value against mitigation cost."),
                 ("Control", "A proportionate response."),
                 ("Record", "Document the findings."),
                 ("Review", "Test controls regularly and audit suppliers."),
             ]},
            {"type": "cards", "title": "Risk responses",
             "cards": [
                 ("Accept", "No further mitigation available, or residual risk remains."),
                 ("Transfer", "Pass the risk to another party, e.g. insurance."),
                 ("Avoid", "Change the project or system scope."),
                 ("Mitigate", "Reduce severity or likelihood with controls."),
             ]},
        ],
        "quiz": [
            ("What is the formula for ALE?", "SLE x ARO = ALE."),
            ("What does MTTD measure?", "How quickly threats are detected, on average."),
            ("What is a single point of failure?", "A component whose failure would stop the whole system."),
            ("Which risk type covers not following policy?", "Compliance risk."),
            ("Buying insurance is which risk response?", "Transfer."),
        ],
        "activity": {
            "title": "Risk assess a LAN device",
            "time": "30 minutes",
            "format": "Pairs",
            "steps": [
                "Choose a device: a network printer, a wireless access point or a file server.",
                "Identify five risks and score each for likelihood and severity.",
                "Calculate the ALE for one risk using realistic figures.",
                "Choose a response for each risk and explain how you would review it.",
            ],
            "success": [
                "Scores lead to RAG ratings",
                "ALE calculation is correct",
                "Responses are proportionate",
            ],
        },
        "exit": [
            "If SLE is 5,000 and ARO is 0.5, what is the ALE?",
            "When is accepting a risk sensible?",
            "What is a mission essential function?",
        ],
    },
    {
        "area": "cyber",
        "file": "cyber-security/09-incident-management-and-forensics.pptx",
        "title": "Incident Management and Digital Forensics",
        "unit": "Cyber Security Content Area 2",
        "spec": "2.1, 2.19, 2.20",
        "pages": [CS2],
        "objectives": [
            "Describe the five-stage compliance model for computer forensics.",
            "Describe the stages of incident and event management.",
            "Escalate a security incident while preserving evidence.",
        ],
        "starter": "You spot ransomware encrypting files on a colleague's PC. Do you switch it off, unplug the network cable, or do something else? Why?",
        "slides": [
            {"type": "process", "title": "Forensic compliance model",
             "steps": [
                 ("Identification", "What evidence exists, where and how it is stored."),
                 ("Preservation", "Isolate and secure it in order, without tampering."),
                 ("Analysis", "Reconstruct fragments and draw evidence-based conclusions."),
                 ("Documentation", "Record every finding and every step."),
                 ("Presentation", "Report to the right body, e.g. law enforcement."),
             ],
             "notes": "The purpose of forensics is to gather legitimate evidence. If evidence is tampered with, it may not be usable."},
            {"type": "process", "title": "Incident and event management",
             "steps": [
                 ("Identify", "Via service desk, phone, email, SMS or chat."),
                 ("Log", "Manually or automatically by monitoring."),
                 ("Manage", "Raise a ticket, assign, categorise by impact."),
                 ("Prioritise", "Urgency, SLAs, escalation; report crimes and breaches."),
                 ("Resolve", "Workaround or permanent fix."),
                 ("Close", "Confirm and write an incident report."),
                 ("Document", "Store records per data protection law."),
             ],
             "notes": "Crimes are reported to the police and personal data breaches to the ICO."},
            {"type": "bullets", "title": "The incident report",
             "bullets": [
                 "Executive summary",
                 "Discovery and investigation",
                 "Impact",
                 "Mitigation",
                 "Recommendations and any ongoing risk",
             ],
             "callout": "Write the executive summary last, and for a manager who will only read that part."},
            {"type": "process", "title": "Escalating while preserving evidence",
             "steps": [
                 ("Record", "Date, time and description of the incident."),
                 ("Act", "e.g. isolate the device from the network."),
                 ("Preserve", "Copy the relevant log files."),
                 ("Escalate", "Pass to the right person or authority."),
             ],
             "caption": "Isolating rather than powering off keeps evidence in memory that would otherwise be lost."},
        ],
        "quiz": [
            ("What is the second stage of the forensic compliance model?", "Preservation."),
            ("Who should a personal data breach be reported to?", "The ICO."),
            ("Name three sections of an incident report.", "Any three of: executive summary, discovery and investigation, impact, mitigation, recommendations, ongoing risk."),
            ("Why isolate a device rather than switch it off?", "To stop the spread while preserving evidence held in memory."),
        ],
        "activity": {
            "title": "Handle the incident",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "Scenario: at 09:40 a finance clerk reports a pop-up demanding bitcoin. Two shared drives are now unreadable.",
                "Work through each incident management stage and record your actions.",
                "List the evidence you would preserve and how.",
                "Write the executive summary of the incident report.",
            ],
            "success": [
                "Stages in the correct order",
                "Evidence preserved before remediation",
                "ICO reporting considered",
                "Summary is clear to a manager",
            ],
        },
        "exit": [
            "Why must forensic evidence be preserved in chronological order?",
            "What is the difference between a workaround and a permanent fix?",
            "When must the police be informed?",
        ],
    },
    {
        "area": "cyber",
        "file": "cyber-security/10-mitigation-backups-and-compliance.pptx",
        "title": "Mitigation, Backups, Policies and Compliance",
        "unit": "Cyber Security Content Area 2",
        "spec": "2.11, 2.21, 2.23, 2.24, 2.25",
        "pages": [CS2],
        "objectives": [
            "Match privacy-breach threats to mitigations.",
            "Apply the five NCSC Cyber Essentials controls.",
            "Compare backup types, including immutable backups.",
            "Describe organisational policies and how compliance is monitored.",
        ],
        "starter": "Ransomware often tries to delete backups before encrypting files. How could you stop it?",
        "slides": [
            {"type": "table", "title": "Mitigating privacy-breach threats",
             "header": ["Threat", "Mitigation"],
             "widths": [3, 5.6],
             "rows": [
                 ["Social engineering", "Raise awareness of current scams"],
                 ["Unmanaged devices", "Company policy restricting their use"],
                 ["Untrained staff", "Training and SOPs"],
                 ["Insider threats", "Access controls, monitoring, segregation of duties"],
                 ["Unpatched applications", "Make sure updates are applied"],
                 ["Third parties", "Supplier due diligence"],
                 ["Improper disposal", "Secure wiping and DPA 2018 compliance"],
             ]},
            {"type": "cards", "title": "Applying Cyber Essentials",
             "cards": [
                 ("Boundary firewalls", "Restrict traffic flowing in and out."),
                 ("Secure configuration", "Enable only the functions needed."),
                 ("Malware protection", "Current anti-malware and regular scans."),
                 ("Security updates", "Keep patches current."),
                 ("Access control", "Least privilege, with PAM for super-user and privileged accounts."),
             ]},
            {"type": "table", "title": "Backup types",
             "header": ["Type", "Description"],
             "widths": [2, 6.6],
             "rows": [
                 ["Full", "Complete copy of all data"],
                 ["Incremental", "Changes since the last backup of any type"],
                 ["Differential", "Changes since the last full backup"],
                 ["Mirror", "Exact live copy, including deletions"],
                 ["Immutable", "Cannot be changed, overwritten or deleted: a defence against ransomware"],
             ],
             "caption": "Criteria: frequency, source, destination, storage medium and location, retention period and regular restore testing."},
            {"type": "cards", "title": "Policies that support risk mitigation",
             "cards": [
                 ("Data", "Data protection, data retention, asset classification."),
                 ("Access", "Access control, password, acceptable use."),
                 ("Devices", "Mobile device, BYOD, asset disposal."),
                 ("Resilience", "Backup policy, incident response procedure, information security policy."),
             ]},
            {"type": "bullets", "title": "Monitoring compliance",
             "bullets": [
                 "Audit processes and policies to check they are current, e.g. review the information security policy.",
                 "Improve them where needed.",
                 "Compare and check the accuracy of processes, logs and incident reports.",
                 "Comply with relevant ISO standards.",
             ],
             "callout": "A policy nobody checks is a wish, not a control."},
        ],
        "quiz": [
            ("What makes a backup immutable?", "It cannot be changed, overwritten or deleted."),
            ("What is PAM used for?", "Managing privileged (elevated) access such as super-user accounts."),
            ("Give a mitigation for insider threats.", "Access controls, monitoring unusual activity or segregation of duties."),
            ("Name four organisational policies.", "Any four from the list, e.g. AUP, password, BYOD, backup."),
            ("Why test restoring backups?", "To prove the backups actually work."),
        ],
        "activity": {
            "title": "Ransomware-proof the backups",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "A design agency backs up to a USB drive left plugged in to the server.",
                "Explain why this would fail against ransomware.",
                "Design a new backup strategy using the backup criteria.",
                "Write the backup policy rules staff must follow.",
            ],
            "success": [
                "Includes an immutable or offline copy",
                "All six criteria addressed",
                "Restore testing is scheduled",
            ],
        },
        "exit": [
            "Which Cyber Essentials control relates to least privilege?",
            "Why is a USB backup left plugged in risky?",
            "How often should an information security policy be reviewed?",
        ],
    },
]
