"""Digital Infrastructure specialism decks."""

DI2 = "02-occupational-specialisms/digital-infrastructure/02-physical-and-virtual-infrastructure.md"

DECKS = [
    {
        "area": "di",
        "file": "digital-infrastructure/01-network-design-addressing-and-transmission.pptx",
        "title": "Network Design, Addressing and Transmission",
        "unit": "Digital Infrastructure Content Area 2",
        "spec": "2.1, 2.2",
        "pages": [DI2],
        "objectives": [
            "Explain resilience principles: high availability, clustering, load balancing and segmentation.",
            "Explain Quality of Service and convert between number systems for addressing.",
            "Compare copper, fibre and wireless transmission and their risks.",
            "Describe IPv4 subnetting and IPv6 address types.",
        ],
        "starter": "A company's single web server crashes every Black Friday. Suggest two ways to keep the website up.",
        "slides": [
            {"type": "cards", "title": "Designing for resilience",
             "cards": [
                 ("High availability", "Primary and secondary systems, so one can take over."),
                 ("Clustering", "Several servers act as one: redundancy and scalability."),
                 ("Load balancing", "Spreads traffic across servers."),
                 ("Segmentation", "Splits networks, systems and data to limit the impact of a problem."),
             ],
             "notes": "QoS (Quality of Service) guarantees a level of service for important traffic such as VoIP."},
            {"type": "table", "title": "Number systems for addressing",
             "header": ["System", "Base", "Example (decimal 255)", "Used for"],
             "widths": [1.6, 1, 2.6, 3.4],
             "rows": [
                 ["Binary", "2", "11111111", "Subnet masks and IP calculations"],
                 ["Decimal", "10", "255", "Dotted decimal IPv4 addresses"],
                 ["Hexadecimal", "16", "FF", "IPv6 addresses and MAC addresses"],
                 ["Octal", "8", "377", "Linux file permissions"],
             ]},
            {"type": "compare", "title": "Transmission media",
             "left": ("Copper and fibre", [
                 "Copper carries electrical signals",
                 "Fibre carries light",
                 "Risks: tampering and signal loss",
                 "Separate copper from power cables to avoid EMI, static and crosstalk",
                 "Use shielding or planned parallel runs (BS EN 50174)",
             ]),
             "right": ("Wireless", [
                 "802.11b, g and n",
                 "Wi-Fi 5 (802.11ac)",
                 "Wi-Fi 6 and 6E (802.11ax)",
                 "Wi-Fi 7 (802.11be)",
                 "Each generation raises speed and capacity",
             ])},
            {"type": "compare", "title": "IPv4 and IPv6",
             "left": ("IPv4", [
                 "32-bit address, e.g. 192.168.1.10",
                 "Subnet mask splits network and host, e.g. /24",
                 "Subnetting divides a network into smaller ones",
                 "Private ranges, e.g. 10.0.0.0/8",
             ]),
             "right": ("IPv6", [
                 "128-bit address in hexadecimal",
                 "Unicast: one interface",
                 "Multicast: a group",
                 "Anycast: the nearest of a group",
                 "Link-local and global addresses",
             ]),
             "notes": "Practise: how many hosts does a /26 give? (2 to the power 6, minus 2 = 62)."},
        ],
        "quiz": [
            ("What does load balancing do?", "Spreads traffic across several servers."),
            ("Convert decimal 255 to binary.", "11111111."),
            ("Why keep data cables away from power cables?", "To avoid electromagnetic interference."),
            ("How many bits in an IPv6 address?", "128."),
            ("How many usable hosts in a /24 subnet?", "254."),
        ],
        "activity": {
            "title": "Subnet the office",
            "time": "25 minutes",
            "format": "Individual",
            "steps": [
                "You have 192.168.10.0/24 for an office with four departments of up to 50 devices each.",
                "Choose a subnet mask that gives four subnets.",
                "Write the network address, first and last host and broadcast for each.",
                "Suggest which resilience principle would protect the file server.",
            ],
            "success": [
                "Uses /26 correctly",
                "Ranges do not overlap",
                "Resilience choice is justified",
            ],
        },
        "exit": [
            "What is the difference between clustering and high availability?",
            "Convert 1010 binary to decimal.",
            "Name one improvement in Wi-Fi 6 over Wi-Fi 5.",
        ],
    },
    {
        "area": "di",
        "file": "digital-infrastructure/02-infrastructure-components-and-cabling.pptx",
        "title": "Infrastructure Components and Cabling",
        "unit": "Digital Infrastructure Content Area 2",
        "spec": "2.3, 2.15",
        "pages": [DI2],
        "objectives": [
            "Describe the purpose of common network and end-user devices.",
            "Compare storage options, including RAID levels, NAS and SAN.",
            "Describe cabling, connectors, antennas and test equipment.",
            "Make and test a UTP cable to TIA/EIA standards.",
        ],
        "starter": "What is the difference between a hub, a switch and a router? Have a guess before we look.",
        "slides": [
            {"type": "table", "title": "Network devices",
             "header": ["Device", "What it does"],
             "widths": [2.6, 6],
             "rows": [
                 ["Firewall (NGFW / UTM)", "Filters traffic; next-generation and unified threat management add deeper inspection"],
                 ["Router", "Forwards packets between networks"],
                 ["Switch", "Connects devices in a LAN and sends frames only to the right port"],
                 ["Hub / bridge", "Hub repeats to every port; bridge joins two segments"],
                 ["Wireless access point / extender", "Provides and extends Wi-Fi coverage"],
                 ["Modem / media converter", "Connects to the ISP; converts between copper and fibre"],
             ]},
            {"type": "cards", "title": "Storage",
             "cards": [
                 ("HDD, SSD, removable", "Cheap capacity, fast solid state, or portable media."),
                 ("NAS and SAN", "File storage on the network, or a dedicated block storage network."),
                 ("Block and object", "Raw blocks for databases; objects with metadata for cloud storage."),
                 ("RAID 0 and 1", "0 stripes for speed with no redundancy; 1 mirrors for safety."),
                 ("RAID 5 and 10", "5 uses parity across three or more disks; 10 mirrors and stripes."),
             ]},
            {"type": "cards", "title": "Wired and wireless technology",
             "cards": [
                 ("UTP cabling", "Straight-through or crossover, wired to TIA/EIA-568A or B."),
                 ("Connectors", "RJ45 for Ethernet, RJ11 for telephone."),
                 ("Cable types", "Copper Cat5e and Cat6, or fibre optic."),
                 ("Protocols", "PPP, software-defined networking, WPA1, 2 and 3."),
                 ("Antennas", "Omni-directional, directional, patch, yagi and dipole."),
                 ("Test equipment", "Tone generator and probe, cable tester, tracing kit, test plans."),
             ],
             "notes": "Also in 2.3: cloud service models (IaaS, PaaS, SaaS), scripting for automation, network monitoring and capacity management."},
            {"type": "process", "title": "Making and testing a UTP cable",
             "steps": [
                 ("Plan", "Decide the purpose and calculate the length."),
                 ("Choose", "Straight-through or crossover."),
                 ("Prepare", "Strip and order the wires to 568A or 568B."),
                 ("Crimp", "Fit 8P8C (RJ45) connectors with a crimper."),
                 ("Test", "Check wiremap and continuity against TIA/EIA."),
             ]},
        ],
        "quiz": [
            ("What does a switch do that a hub does not?", "Sends frames only to the port of the destination device."),
            ("Which RAID level offers no redundancy?", "RAID 0."),
            ("Which connector is used for Ethernet?", "RJ45 (8P8C)."),
            ("What is a crossover cable?", "A cable wired 568A at one end and 568B at the other."),
            ("Which antenna type sends signal in all directions?", "Omni-directional."),
        ],
        "activity": {
            "title": "Make a patch lead",
            "time": "40 minutes",
            "format": "Practical, individual",
            "steps": [
                "Measure and cut a 1 metre length of Cat6 UTP.",
                "Terminate both ends to TIA/EIA-568B.",
                "Test it with a cable tester and record the wiremap result.",
                "If it fails, find the fault, re-terminate and retest.",
            ],
            "success": [
                "Correct colour order at both ends",
                "Jacket crimped inside the connector",
                "Test result recorded",
                "Safe use of tools",
            ],
            "notes": "Wear eye protection when cutting. Keep offcuts for fault-finding practice.",
        },
        "exit": [
            "When would you choose RAID 10 over RAID 5?",
            "What does a media converter do?",
            "What does a wiremap test check?",
        ],
    },
    {
        "area": "di",
        "file": "digital-infrastructure/03-servers-virtualisation-and-operating-systems.pptx",
        "title": "Servers, Virtualisation and Operating Systems",
        "unit": "Digital Infrastructure Content Area 2",
        "spec": "2.6 to 2.9, 2.23",
        "pages": [DI2],
        "objectives": [
            "Compare physical servers, self-hosted and cloud-hosted virtual servers, and containers.",
            "Describe types of operating system used in digital infrastructure.",
            "Explain virtualisation concepts and applications.",
        ],
        "starter": "Why might a company pay monthly for a server in the cloud instead of buying one for its own office?",
        "slides": [
            {"type": "table", "title": "Server options",
             "header": ["Option", "Advantages", "Disadvantages"],
             "widths": [2.2, 3.4, 3.4],
             "rows": [
                 ["Physical server", "Full access to resources, full customisation", "Expensive, harder to maintain and scale, needs space"],
                 ["Self-hosted virtual", "Cost control, scalable, supports HA and clustering", "High upfront cost, resilience is expensive"],
                 ["Cloud-hosted virtual", "Scales easily, built-in redundancy, third-party support", "Subscription cost, complex setup"],
                 ["Containers", "Lightweight, portable, consistent, cheap", "Less secure if misconfigured, less OS flexibility, needs expertise"],
             ]},
            {"type": "compare", "title": "Operating systems",
             "left": ("Types", [
                 "Desktop: Windows, macOS",
                 "Mobile: Android, iOS",
                 "Server: Linux, Windows Server",
             ]),
             "right": ("What they share", [
                 "A user interface and personalisation",
                 "Resource management",
                 "A platform for applications",
                 "They differ in features, UX and purpose",
             ])},
            {"type": "cards", "title": "Virtualisation concepts",
             "cards": [
                 ("Partitioning", "Many virtual resources from one physical resource, or one from many."),
                 ("Isolation", "Each virtual machine is separated from the others."),
                 ("Encapsulation", "A whole VM is saved as files that can be copied or moved."),
                 ("Hardware independence", "VMs run on any host with a compatible hypervisor."),
             ]},
            {"type": "cards", "title": "Applications of virtualisation",
             "cards": [
                 ("Network", "Virtual switches, routers and networks."),
                 ("Server", "Many servers on one host."),
                 ("Desktop", "Users' desktops hosted centrally."),
                 ("Operating system", "Several OSs on one machine."),
                 ("Data", "One view of data held in many places."),
             ]},
        ],
        "quiz": [
            ("Give one disadvantage of a physical server.", "E.g. expensive, hard to scale, needs physical space."),
            ("Why are containers lightweight?", "They carry only what the application needs and share the host OS kernel."),
            ("What does encapsulation mean in virtualisation?", "The whole VM is stored as files that can be moved or copied."),
            ("Name a server operating system.", "Linux or Windows Server."),
        ],
        "activity": {
            "title": "Build a virtual lab",
            "time": "40 minutes",
            "format": "Pairs, on a lab PC",
            "steps": [
                "Install a Type 2 hypervisor or use the one provided.",
                "Create two VMs: a server OS and a client OS.",
                "Put them on the same virtual network and test connectivity with ping.",
                "Take a snapshot, make a change, then roll back.",
            ],
            "success": [
                "Both VMs boot",
                "Ping succeeds both ways",
                "Snapshot rollback demonstrated",
            ],
        },
        "exit": [
            "Which server option suits a start-up with no IT room?",
            "Name one risk of containers.",
            "What is desktop virtualisation?",
        ],
    },
    {
        "area": "di",
        "file": "digital-infrastructure/04-network-services-remote-access-and-installation.pptx",
        "title": "Network Services, Remote Access and Installation",
        "unit": "Digital Infrastructure Content Area 2",
        "spec": "2.10 to 2.14",
        "pages": [DI2],
        "objectives": [
            "Describe client-server network services including AD DS, Group Policy, DHCP, DNS and LDAP.",
            "Compare remote access methods and set up a simple VPN.",
            "Install, configure, test and maintain network components.",
        ],
        "starter": "When you log on to a college PC, your desktop and drives appear however you sit. How does it know who you are?",
        "slides": [
            {"type": "table", "title": "Client-server network services",
             "header": ["Service", "Purpose"],
             "widths": [2.4, 6.2],
             "rows": [
                 ["AD DS", "Centrally manages users, devices and groups in organisational units (OUs)"],
                 ["Group Policy", "GPOs applied to OUs push settings and files to users and devices"],
                 ["DHCP", "Assigns IP addresses to clients"],
                 ["DNS", "Translates hostnames into IP addresses"],
                 ["LDAP", "Protocol for directory authentication"],
                 ["File, print, web, mail, app, DB servers", "Shared storage, printing, filtered web access, email and data"],
             ]},
            {"type": "cards", "title": "Remote access methods",
             "cards": [
                 ("VPN", "A private, encrypted tunnel to the network."),
                 ("RDP", "Remote desktop: processing stays on the host machine."),
                 ("LOM", "Lights-out management: administer a server even when it is off."),
                 ("SSH", "A secure encrypted connection between two hosts, usually command line."),
             ]},
            {"type": "compare", "title": "Setting up a simple VPN",
             "left": ("Server side", [
                 "Enable the VPN service",
                 "Set IP addressing and DNS",
                 "Manage authentication",
                 "Set user permissions",
             ]),
             "right": ("Client side", [
                 "Create the connection",
                 "Set the destination IP or FQDN",
                 "Set permissions and conditions",
                 "Test the connection",
             ])},
            {"type": "process", "title": "Install, configure, test, maintain",
             "steps": [
                 ("Install", "Servers, network devices, firewalls, load balancers, end-user devices."),
                 ("Configure", "Services like DNS and DHCP; correct ports and protocols; scripts."),
                 ("Back up", "Apply the backup policy."),
                 ("Test", "Functionality and performance; record results."),
                 ("Maintain", "Monitor, log, manage capacity, automate with scripts."),
             ]},
        ],
        "quiz": [
            ("What is an OU?", "An organisational unit: a container in Active Directory for users, groups and devices."),
            ("Which service gives a PC its IP address?", "DHCP."),
            ("What does DNS do?", "Translates hostnames into IP addresses."),
            ("Which remote access method works even when the server is powered off?", "Lights-out management (LOM)."),
            ("What must be set on the client side of a VPN?", "The connection, destination IP or FQDN, and permissions."),
        ],
        "activity": {
            "title": "Build a mini domain",
            "time": "50 minutes",
            "format": "Pairs, on VMs",
            "steps": [
                "Promote a Windows Server VM to a domain controller with DNS.",
                "Add DHCP with a small scope.",
                "Create two OUs with a user in each, and a GPO that sets a desktop wallpaper for one OU.",
                "Join a client VM to the domain and test both users.",
            ],
            "success": [
                "Client receives an address from DHCP",
                "Both users log on",
                "GPO applies to the right OU only",
                "Each step tested and recorded",
            ],
            "notes": "Could be split over two lessons. A Linux alternative is Samba with isc-dhcp-server.",
        },
        "exit": [
            "Why use Group Policy rather than configuring each PC by hand?",
            "When would you use SSH instead of RDP?",
            "What should you record after testing a new service?",
        ],
    },
    {
        "area": "di",
        "file": "digital-infrastructure/05-health-safety-and-esd.pptx",
        "title": "Health, Safety and ESD in Digital Infrastructure",
        "unit": "Digital Infrastructure Content Area 2",
        "spec": "2.4, 2.5",
        "pages": [DI2],
        "objectives": [
            "Explain how to prevent electrostatic discharge damage.",
            "Apply the risk management process to ESD.",
            "Describe the health and safety legislation that applies to infrastructure work.",
        ],
        "starter": "You feel a small shock when you touch a door handle. What would that same shock do to a stick of RAM?",
        "slides": [
            {"type": "bullets", "title": "Preventing electrostatic discharge",
             "bullets": [
                 "Limit movement while handling components.",
                 "Check temperature and humidity in the work area.",
                 "Use anti-static equipment: wrist straps, mats and bags.",
                 "Handle components by the edges and keep them in anti-static bags until needed.",
             ],
             "callout": "ESD damage is often invisible. A component can seem fine and fail weeks later.",
             "notes": "The specification links static build-up to humidity, so check the room's conditions as part of the risk assessment."},
            {"type": "process", "title": "Risk managing ESD",
             "steps": [
                 ("Identify", "Risks and their effect on people and kit."),
                 ("Assess", "Calculate probability and impact."),
                 ("Prioritise", "Rank the risks."),
                 ("Protect", "Apply ESD protection."),
                 ("Record", "Write up findings; comply with H&S law."),
             ]},
            {"type": "table", "title": "Health and safety legislation",
             "header": ["Legislation", "Example in infrastructure work"],
             "widths": [4, 4.6],
             "rows": [
                 ["Health and Safety at Work etc. Act 1974", "PPE and the employer's duty of care"],
                 ["Manual Handling Operations Regulations 1992", "Moving servers and network kit"],
                 ["Health and Safety (DSE) Regulations", "Screen time and workstation setup"],
                 ["COSHH Regulations 2002", "Chemicals, e.g. printer toner"],
                 ["Control of Major Accident Hazards Regulations 2015", "e.g. earthing"],
                 ["WEEE Directive 2013", "Disposing of hardware and network components"],
             ]},
        ],
        "quiz": [
            ("Name two pieces of anti-static equipment.", "Any two of: wrist strap, mat, anti-static bag."),
            ("Why is ESD damage dangerous even if nothing seems wrong?", "Components can be weakened and fail later."),
            ("Which regulations cover chemicals such as toner?", "COSHH Regulations 2002."),
            ("Which law covers disposing of old switches?", "WEEE Directive 2013."),
        ],
        "activity": {
            "title": "ESD risk assessment and RAM swap",
            "time": "30 minutes",
            "format": "Pairs, practical",
            "steps": [
                "Complete an ESD risk assessment for upgrading RAM in a lab PC.",
                "Set up the anti-static workstation.",
                "Remove and replace the RAM following your assessment.",
                "Record the outcome and any issues.",
            ],
            "success": [
                "Risk assessment completed before starting",
                "Wrist strap used correctly",
                "PC boots and detects the RAM",
            ],
        },
        "exit": [
            "Name one environmental factor that affects static.",
            "Which Act sets out the employer's duty of care?",
            "What should you do before opening a PC case?",
        ],
    },
    {
        "area": "di",
        "file": "digital-infrastructure/06-service-management-and-solution-lifecycle.pptx",
        "title": "Service Management and the Solution Lifecycle",
        "unit": "Digital Infrastructure Content Area 2",
        "spec": "2.16, 2.17, 2.20 to 2.22, 2.24",
        "pages": [DI2],
        "objectives": [
            "Describe ITSM principles and the ITIL service lifecycle.",
            "Describe the stages of the solution lifecycle.",
            "Explain DevOps principles and solution architecture.",
            "Apply continuous improvement to hardware and networks.",
        ],
        "starter": "Your phone gets a software update every few weeks. Why not wait and release one big update a year?",
        "slides": [
            {"type": "compare", "title": "ITSM and ITIL",
             "left": ("ITSM principles", [
                 "Co-create value through service relationships",
                 "Deliver a good customer experience",
                 "Consider the wider impact of change",
                 "Work across departments",
             ]),
             "right": ("ITIL lifecycle", [
                 "Service strategy",
                 "Service design",
                 "Service transition",
                 "Service operation",
                 "Continual service improvement",
             ])},
            {"type": "process", "title": "The solution lifecycle (SLC)",
             "steps": [
                 ("Discover", "Requirements, feasibility, concept."),
                 ("Design and develop", "Detailed design, prototype, build, integrate."),
                 ("Test and QA", "Functional and performance testing."),
                 ("Pre-production", "Sandbox testing and sign-off."),
                 ("Deploy", "Release, staged for high-impact changes."),
                 ("Monitor", "Evaluate and improve."),
                 ("Retire", "Decommission and migrate."),
             ],
             "notes": "Every stage should be applied safely and documented."},
            {"type": "compare", "title": "DevOps",
             "left": ("Principles", [
                 "Continuous integration and delivery",
                 "Microservices",
                 "Infrastructure as code",
                 "Collaboration and automated testing",
                 "Monitoring and logging",
             ]),
             "right": ("Benefits", [
                 "Faster delivery",
                 "Higher productivity",
                 "Better processes across teams",
                 "Scalability",
                 "Fewer errors",
             ])},
            {"type": "bullets", "title": "Solution architecture",
             "bullets": [
                 "Reuse and documentation matter.",
                 "Architecture applies to hardware, not just software.",
                 "Frameworks such as TOGAF give structure.",
                 "Solutions should align with the enterprise architecture.",
                 "Described through system, view, viewpoint, concern and stakeholder.",
             ],
             "callout": "Continuous improvement: identify affected hardware, measure performance, apply the right SLC stage, re-measure, review data and record findings."},
        ],
        "quiz": [
            ("Which ITIL stage builds and deploys services with managed change?", "Service transition."),
            ("What happens in the pre-production stage of the SLC?", "Sandbox testing and sign-off."),
            ("What is infrastructure as code?", "Defining and managing infrastructure through code and scripts rather than by hand."),
            ("Name an architecture framework.", "TOGAF."),
        ],
        "activity": {
            "title": "Plan a network upgrade through the SLC",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "Scenario: the college's Wi-Fi cannot cope with exam season.",
                "Plan the upgrade through every SLC stage.",
                "Decide how you will measure performance before and after.",
                "Identify one DevOps practice that would help.",
            ],
            "success": [
                "All SLC stages covered",
                "Performance measures are specific",
                "Staged rollout considered",
            ],
        },
        "exit": [
            "Why use a staged rollout for a high-impact change?",
            "Name two DevOps principles.",
            "What is the final stage of the solution lifecycle?",
        ],
    },
]
