"""Digital Support specialism decks."""

DS2 = "02-occupational-specialisms/digital-support/02-software-and-os-support.md"

DECKS = [
    {
        "area": "ds",
        "file": "digital-support/01-agile-values-and-methodologies.pptx",
        "title": "Agile Values and Methodologies",
        "unit": "Digital Support Content Area 2",
        "spec": "2.1, 2.2",
        "pages": [DS2],
        "objectives": [
            "State the four agile values.",
            "Describe Scrum, Kanban, DSDM, FDD, Crystal, Lean and XP.",
            "Choose an agile method to suit a support team's work.",
        ],
        "starter": "Your team has 40 support tickets and new ones arrive every hour. How would you decide what to work on next?",
        "slides": [
            {"type": "cards", "title": "The four agile values",
             "cards": [
                 ("Individuals and interactions", "over processes and tools."),
                 ("Working software", "over comprehensive documentation."),
                 ("Customer collaboration", "over contract negotiation."),
                 ("Responding to change", "over following a plan."),
             ],
             "notes": "The items on the right still matter; agile just values the items on the left more."},
            {"type": "cards", "title": "Agile methodologies (1)",
             "cards": [
                 ("Scrum", "Defined roles, events and artefacts; daily scrums; work in sprints."),
                 ("Kanban", "Board with work-in-progress limits; balances demand and capacity; shows bottlenecks."),
                 ("DSDM", "Fixes cost, quality and time; prioritises scope with MoSCoW."),
             ]},
            {"type": "cards", "title": "Agile methodologies (2)",
             "cards": [
                 ("Feature-driven development", "Plan, design and build one small feature at a time."),
                 ("Crystal", "Puts people and communication ahead of process and tools."),
                 ("Lean", "Eliminate waste, build in quality, create knowledge, defer commitment, deliver fast, respect people, optimise the whole."),
                 ("Extreme Programming", "Frequent short releases, checkpoints for new requirements, feedback loops."),
             ]},
            {"type": "table", "title": "MoSCoW prioritisation",
             "header": ["Priority", "Meaning", "Example for a new helpdesk system"],
             "widths": [1.6, 3, 4],
             "rows": [
                 ["Must have", "Essential; without it the project fails", "Log and track tickets"],
                 ["Should have", "Important but not vital", "Email notifications"],
                 ["Could have", "Nice to have if time allows", "Chatbot for common questions"],
                 ["Won't have (this time)", "Agreed to leave out for now", "Mobile app"],
             ]},
        ],
        "quiz": [
            ("Complete the value: responding to change over...", "Following a plan."),
            ("What is a WIP limit in Kanban?", "A cap on the number of items allowed in a column at once."),
            ("Which method uses MoSCoW?", "DSDM."),
            ("Name three Lean principles.", "Any three of the seven, e.g. eliminate waste, deliver fast, respect people."),
        ],
        "activity": {
            "title": "Run a Kanban board",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Draw a Kanban board with To do, In progress, Waiting on user and Done.",
                "Add the 12 ticket cards from your teacher.",
                "Set a WIP limit and play three 'rounds' of work, adding new tickets each round.",
                "Identify the bottleneck and suggest a fix.",
            ],
            "success": [
                "WIP limit respected",
                "Priorities are sensible",
                "Bottleneck identified with evidence",
            ],
        },
        "exit": [
            "Which agile method suits a helpdesk best, and why?",
            "What is a sprint?",
            "Give one 'Won't have' item for a project you know.",
        ],
    },
    {
        "area": "ds",
        "file": "digital-support/02-domains-email-and-remote-access.pptx",
        "title": "Domains, Email and Remote Access",
        "unit": "Digital Support Content Area 2",
        "spec": "2.4, 2.16 to 2.20",
        "pages": [DS2],
        "objectives": [
            "Describe the service functions that create a domain environment.",
            "Explain email protocols and configure on-premises and cloud email.",
            "Explain the purpose of remote access and VPNs.",
            "Configure a simple VPN.",
        ],
        "starter": "Your email arrives on your phone, laptop and the web, and they all stay in sync. How?",
        "slides": [
            {"type": "table", "title": "Service functions in a domain",
             "header": ["Service", "Purpose"],
             "widths": [2.6, 6],
             "rows": [
                 ["AD DS and Group Policy", "Manage users, devices and groups in OUs; GPOs push settings"],
                 ["DHCP", "Assigns IP addresses and network settings"],
                 ["DNS", "Resolves hostnames to IP addresses"],
                 ["File server / DFS", "Shared storage and permissions"],
                 ["Print server", "Shared printers"],
                 ["Mail server", "Inbound and outbound mail"],
                 ["Certificate authority", "Issues digital certificates"],
             ]},
            {"type": "table", "title": "Email protocols",
             "header": ["Protocol", "What it does"],
             "widths": [2, 6.6],
             "rows": [
                 ["POP3", "Downloads mail to local software"],
                 ["IMAP", "Keeps mail on the server, synced across devices"],
                 ["SMTP", "Sends mail across the internet"],
                 ["S/MIME", "Encrypts and signs email"],
                 ["SSL / TLS", "Encrypt the connection between mail server and client"],
             ],
             "caption": "Configuring email: follow corporate policy, set up profiles and signatures, choose a provider, protocol, MX record and mail domains."},
            {"type": "compare", "title": "Remote access and VPNs",
             "left": ("Remote access", [
                 "Work remotely as if on the network",
                 "Supports home working in a BCP",
                 "Desktop sharing",
                 "Remote support and fault diagnosis",
                 "Off-site working",
             ]),
             "right": ("VPNs", [
                 "Encrypt traffic and mask the client's IP",
                 "Choose port and security protocol",
                 "Set encryption and certificates",
                 "Configure authentication",
             ])},
            {"type": "process", "title": "Configuring a simple VPN",
             "steps": [
                 ("Enable", "Turn on the VPN service on the server."),
                 ("Address", "Set IP and DNS for the VPN interface."),
                 ("Access", "Manage authentication and permissions."),
                 ("Client", "Create the connection to the server's IP or FQDN."),
                 ("Test", "Connect and check access to resources."),
             ]},
        ],
        "quiz": [
            ("Which protocol keeps mail on the server?", "IMAP."),
            ("Which protocol sends email?", "SMTP."),
            ("What is an MX record?", "A DNS record that says which server receives mail for a domain."),
            ("What two things does a VPN do for privacy?", "Encrypts traffic and masks the client's IP address."),
            ("What does a certificate authority issue?", "Digital certificates."),
        ],
        "activity": {
            "title": "Set up a mail client",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Set up a test account in a desktop mail client using IMAP and SMTP with TLS.",
                "Record the server names and ports used.",
                "Explain why you chose IMAP over POP3 for a user with three devices.",
                "Add a corporate signature that follows a given policy.",
            ],
            "success": [
                "Mail sends and receives",
                "Encrypted ports used",
                "Choice of protocol justified",
            ],
        },
        "exit": [
            "Why might a remote worker need a VPN?",
            "What does S/MIME add to email?",
            "Name the DNS record used for mail.",
        ],
    },
    {
        "area": "ds",
        "file": "digital-support/03-devices-operating-systems-and-applications.pptx",
        "title": "Devices, Operating Systems and Applications",
        "unit": "Digital Support Content Area 2",
        "spec": "2.6 to 2.9",
        "pages": [DS2],
        "objectives": [
            "Describe the end-user devices and systems a support technician looks after.",
            "Describe OS types and application types.",
            "Check system requirements and install and configure applications and operating systems.",
        ],
        "starter": "A user says their new software 'will not install'. What would you check first?",
        "slides": [
            {"type": "cards", "title": "End-user devices",
             "cards": [
                 ("Desktops", "Thick clients that process locally, or thin clients that rely on a server."),
                 ("Cloud workspaces", "Free or licensed online desktops."),
                 ("Mobile devices", "Tablets, smartphones, wearables, e-readers."),
                 ("Peripherals", "Keyboards, monitors, printers, projectors, card readers, drives."),
                 ("IoT", "Smart building alarms, meters and lighting; smart TVs; autonomous vehicles."),
             ]},
            {"type": "compare", "title": "Operating systems and applications",
             "left": ("OS types", [
                 "End-user: Windows, macOS, Linux",
                 "Mobile: iOS, Android",
                 "Server: Windows Server, Linux",
             ]),
             "right": ("Application types", [
                 "Productivity: word processing, spreadsheets, diagrams",
                 "Web browsers",
                 "Collaboration: email, conferencing, VoIP, chat",
                 "Business: databases, CRM, ticketing, accounting",
                 "Development: CAD, IDE",
             ])},
            {"type": "compare", "title": "Checking requirements: storage",
             "left": ("HDD", [
                 "Cheap per gigabyte",
                 "Large capacity",
                 "Moving parts can break",
                 "Can overheat",
             ]),
             "right": ("SSD", [
                 "Much faster",
                 "No moving parts",
                 "Costs more per gigabyte",
                 "Smaller, suits compact devices",
             ]),
             "notes": "Also check RAM, processor, OS compatibility and network card. Consider permissions (least privilege) and the security impact on the device, network and data."},
            {"type": "process", "title": "Installing an operating system",
             "steps": [
                 ("Boot and partition", "Choose the boot drive; partition and format."),
                 ("Domain", "Join the domain."),
                 ("Region", "Set time, date, region and language."),
                 ("Drivers", "Install drivers."),
                 ("Update", "Apply updates, including over the network."),
                 ("Apps", "Install productivity software; migrate user data if upgrading."),
             ]},
        ],
        "quiz": [
            ("What is the difference between a thick and a thin client?", "A thick client processes locally; a thin client relies on a server."),
            ("Give two advantages of an SSD over an HDD.", "Faster; no moving parts."),
            ("Name two collaboration applications.", "Any two of: email client, video conferencing, VoIP, instant messaging, document sharing."),
            ("What should you check before installing software?", "System requirements: storage, RAM, processor, OS compatibility."),
        ],
        "activity": {
            "title": "Install and configure",
            "time": "45 minutes",
            "format": "Individual, on a VM",
            "steps": [
                "Check the VM meets the system requirements for the given OS.",
                "Install the OS with a sensible partition layout.",
                "Set region, language and time, then apply updates.",
                "Install a productivity suite and record every setting you chose.",
            ],
            "success": [
                "Requirements checked and recorded",
                "OS fully updated",
                "Clear installation log for a colleague to follow",
            ],
        },
        "exit": [
            "Which device type would you give a hot-desking call centre?",
            "Why use least privilege when installing software?",
            "What should you do before an in-place OS upgrade?",
        ],
    },
    {
        "area": "ds",
        "file": "digital-support/04-os-deployment-imaging-and-recovery.pptx",
        "title": "OS Deployment, Imaging and Recovery",
        "unit": "Digital Support Content Area 2",
        "spec": "2.10 to 2.15",
        "pages": [DS2],
        "objectives": [
            "Describe installation methods, boot methods, partitioning and file systems.",
            "Compare deployment methods and their advantages and disadvantages.",
            "Create and deploy disk images and explain their benefits.",
            "Explain the difference between system recovery and restoration.",
        ],
        "starter": "You have to set up 200 identical laptops by Monday. Doing each by hand takes an hour. What could you do instead?",
        "slides": [
            {"type": "cards", "title": "Deployment considerations",
             "cards": [
                 ("Installation methods", "Network, local (CD or USB), virtualised, cloud-based."),
                 ("Boot methods", "Internal drive, external media, or network boot (PXE, Netboot)."),
                 ("Partitioning", "Basic, dynamic, primary, extended, logical, GPT."),
                 ("File systems", "NTFS, exFAT, FAT32, ReFS, NFS, ext3, ext4, HFS, swap."),
             ],
             "notes": "Quick format is fast and files are easier to recover; full format scans for bad sectors, is slower and makes recovery harder."},
            {"type": "table", "title": "Deployment methods",
             "header": ["Method", "Advantage", "Disadvantage"],
             "widths": [2.2, 3.2, 3.2],
             "rows": [
                 ["Unattended", "Minimal technician input", "Answers must be prepared in advance"],
                 ["Thin imaging", "Flexible across varied devices", "More maintenance, harder to configure"],
                 ["Base image", "Easy to create at scale", "Harder to maintain, less flexible"],
                 ["In-place upgrade", "Keeps user profiles", "Compatibility risks, needs full OS media"],
                 ["Clean install", "Latest OS, simple", "Needs a backup first and takes time"],
                 ["Repair install", "Fixes without data loss", "Manual; may not fix every problem"],
                 ["Remote network install", "No physical access, scales well", "Limited by network speed; needs PXE setup"],
             ],
             "notes": "Multi-boot is also listed: several OSs on one device, but fiddly to set up and maintain."},
            {"type": "process", "title": "Creating and deploying a disk image",
             "steps": [
                 ("Base image", "Install and configure the OS, apps and drivers."),
                 ("Answer file", "Create the customisation file."),
                 ("Extras", "Add drivers and software."),
                 ("Distribute", "Put the image where devices can reach it."),
                 ("Deploy", "Push it to the devices."),
                 ("Maintain", "Keep versions and drivers updated."),
             ],
             "caption": "Benefits: fewer resources, consistent builds, lower support costs and quick restoration."},
            {"type": "compare", "title": "Recovery and restoration",
             "left": ("System recovery", [
                 "Fixes the system in its current state",
                 "Keeps files and folders",
                 "Try this first",
             ]),
             "right": ("System restoration", [
                 "Used when recovery fails",
                 "Reverts to an earlier state",
                 "Recent changes may be lost",
             ]),
             "notes": "Process: make sure data is backed up, boot into recovery tools, follow the steps, then test that the issue is fixed."},
        ],
        "quiz": [
            ("What does PXE allow?", "Booting a device over the network."),
            ("Give one advantage of thin imaging.", "Flexible and scales across varied devices."),
            ("Which format type scans for bad sectors?", "Full format."),
            ("What is an answer file?", "A file containing setup answers so installation runs unattended."),
            ("When would you use restoration instead of recovery?", "When recovery has failed to fix the system."),
        ],
        "activity": {
            "title": "Choose the deployment",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "Scenario A: 200 identical laptops for a school.",
                "Scenario B: 30 mixed devices for a design agency.",
                "Scenario C: one director's PC that will not boot, with irreplaceable files on it.",
                "Choose and justify a deployment or recovery method for each.",
            ],
            "success": [
                "Method suits scale and variety",
                "Data is protected in scenario C",
                "Advantages and disadvantages weighed",
            ],
        },
        "exit": [
            "Why keep disk images updated?",
            "What file system would you choose for a USB stick used on Windows and macOS?",
            "Name one risk of an in-place upgrade.",
        ],
    },
    {
        "area": "ds",
        "file": "digital-support/05-end-user-support-and-troubleshooting.pptx",
        "title": "End-User Support and Troubleshooting",
        "unit": "Digital Support Content Area 2",
        "spec": "2.5, 2.21 to 2.23, 2.28",
        "pages": [DS2],
        "objectives": [
            "Describe the functions of a service management system (CMS).",
            "Apply a structured troubleshooting method and document it.",
            "Describe support processes for end users.",
            "Monitor and operate information systems and maintain service delivery.",
        ],
        "starter": "A user rings: 'The internet is broken.' Write down the first three questions you would ask.",
        "slides": [
            {"type": "cards", "title": "What the CMS does",
             "cards": [
                 ("Incidents and requests", "Log, track, open and close tickets."),
                 ("Knowledge", "Collate support knowledge and spot training needs."),
                 ("Change", "Support the rollout of new systems."),
                 ("Configuration and assets", "Licences, hardware and software requests, decommissioning."),
             ]},
            {"type": "process", "title": "The troubleshooting method",
             "steps": [
                 ("Gather", "Investigate the request and likely causes."),
                 ("Analyse", "Rule out known fixes and causes."),
                 ("Test", "Test the remaining possibilities."),
                 ("Resolve", "Back up, fix, test, repeat until solved."),
                 ("Document", "Record cause and solution in the CMS."),
                 ("Prevent", "Apply controls so it does not recur."),
             ]},
            {"type": "cards", "title": "Support processes",
             "cards": [
                 ("Accounts", "Add and remove users, set access hours."),
                 ("Passwords", "Complexity, expiry, forced resets."),
                 ("Permissions", "Resource access, group policy, shared resources."),
                 ("Software", "Installation and deployment, connecting to remote resources."),
                 ("Faults", "Identify, escalate from first to third line, use known fixes."),
                 ("Knowledge", "Documentation, SOPs, asset management and auditing."),
             ]},
            {"type": "bullets", "title": "Monitoring and operating systems",
             "bullets": [
                 "Analyse performance of hardware, software, databases, networks and people.",
                 "Monitor security controls (firewalls, anti-virus) and network traffic.",
                 "Track licences and log and tag assets.",
                 "Create, update and communicate tickets; support users remotely.",
                 "Review user feedback critically.",
             ],
             "callout": "Record and summarise findings clearly using correct technical terms, so they can shape future policy."},
        ],
        "quiz": [
            ("What is the first step of the troubleshooting method?", "Gather information."),
            ("Why back up before implementing a fix?", "So data can be restored if the fix causes problems."),
            ("What is escalation?", "Passing an issue to a higher support line or specialist."),
            ("Name two CMS functions.", "Any two of: incident and request, knowledge, change, configuration and asset management."),
        ],
        "activity": {
            "title": "Helpdesk simulation",
            "time": "35 minutes",
            "format": "Pairs: user and technician, then swap",
            "steps": [
                "The user takes a fault card and describes only the symptoms.",
                "The technician follows the troubleshooting method, asking questions.",
                "The technician logs a full ticket: user, issue, steps, resolution, time taken.",
                "Swap roles with a new fault card.",
            ],
            "success": [
                "Method followed in order",
                "Ticket is complete and clear",
                "Preventive action suggested",
            ],
            "notes": "Fault card ideas: caps lock on, disconnected network cable, full mailbox, expired password, printer offline.",
        },
        "exit": [
            "Why document every fix in the CMS?",
            "When should a first-line technician escalate?",
            "What would you monitor to spot a failing network switch?",
        ],
    },
    {
        "area": "ds",
        "file": "digital-support/06-asset-version-and-mobile-device-management.pptx",
        "title": "Asset, Version and Mobile Device Management",
        "unit": "Digital Support Content Area 2",
        "spec": "2.24 to 2.26",
        "pages": [DS2],
        "objectives": [
            "Describe version control management, including patching and rollback.",
            "Describe the stages of the asset management process.",
            "Explain the purpose and features of mobile device management.",
            "Configure MDM settings for a device.",
        ],
        "starter": "A member of staff leaves a work phone on the bus. What would you want to be able to do from your desk?",
        "slides": [
            {"type": "compare", "title": "Version control management",
             "left": ("Installing and updating", [
                 "Fresh installs: OS, applications, utilities, licensing",
                 "Patches: system, driver, firmware, anti-malware, application",
                 "Deployed with network tools such as Group Policy",
             ]),
             "right": ("Controlling change", [
                 "Rollback procedures, e.g. a device driver or failed OS update",
                 "Testing before release",
                 "Release control across local and network installs",
             ])},
            {"type": "process", "title": "The asset management process",
             "steps": [
                 ("Identify and plan", "User and organisational needs, constraints, deployment strategy."),
                 ("Acquire and implement", "Source hardware and software, integrate it."),
                 ("Operate and maintain", "Track licences, respond to requests."),
                 ("Decommission and redeploy", "Retire old kit, manage joiners and leavers."),
             ]},
            {"type": "cards", "title": "Mobile Device Management (MDM)",
             "cards": [
                 ("Purpose", "Track, locate, secure and configure mobile devices: Wi-Fi, data, hotspot, Bluetooth, email."),
                 ("Applications", "Separate personal and work profiles; enforce policy."),
                 ("Remote management", "Remote wipe, disable features, restrict app stores and data, control backup."),
                 ("Security features", "Screen lock, encryption, password rules, login limits, MFA, authenticator apps."),
             ]},
        ],
        "quiz": [
            ("What is a rollback procedure?", "A way to return to the previous version if an update fails."),
            ("What happens at the decommissioning stage of asset management?", "Old assets are removed or retired and leaver profiles managed."),
            ("What does a remote wipe do?", "Erases a lost or stolen device remotely."),
            ("Give two MDM security features.", "Any two of: screen lock, encryption, password enforcement, login limits, MFA, authenticator apps."),
        ],
        "activity": {
            "title": "Write an MDM policy",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "A charity is giving 25 staff smartphones for fieldwork.",
                "Choose the MDM settings you would enforce and explain each.",
                "Decide which features to disable and why.",
                "Write the steps to follow when a phone is reported lost.",
            ],
            "success": [
                "Security and usability balanced",
                "Lost-device steps include remote wipe",
                "Personal data considered",
            ],
        },
        "exit": [
            "Why track software licences?",
            "What is the benefit of separating work and personal profiles?",
            "Name one thing to do when a staff member leaves.",
        ],
    },
    {
        "area": "ds",
        "file": "digital-support/07-digital-solutions-and-training-users.pptx",
        "title": "Digital Solutions and Training Users",
        "unit": "Digital Support Content Area 2",
        "spec": "2.3, 2.27, 2.29",
        "pages": [DS2],
        "objectives": [
            "Describe how digital technologies support each business function.",
            "Explain the benefits of a digital solution clearly to an audience.",
            "Choose training methods and tools for digital systems.",
        ],
        "starter": "Think of the last time you learned a new app. How did you learn it? What would have made it quicker?",
        "slides": [
            {"type": "table", "title": "Digital technologies across the business",
             "header": ["Function", "Technologies"],
             "widths": [2.4, 6.2],
             "rows": [
                 ["Finance", "Budget dashboards, invoicing, expense tracking"],
                 ["Sales and marketing", "CRM, social media tools"],
                 ["Operations", "Performance dashboards, ticketing"],
                 ["HR", "Personnel systems, digital training"],
                 ["Communications", "Video conferencing, email, collaboration platforms"],
                 ["R&D", "CAD, IDEs"],
             ],
             "caption": "For support teams this means more demand, more training needs and more emphasis on CPD."},
            {"type": "process", "title": "Explaining a digital solution",
             "steps": [
                 ("Analyse", "What is needed: information, services, products or transactions?"),
                 ("Identify", "The best-fit solution: systems, software or wider technology."),
                 ("Explain", "The benefit, clearly and concisely, pitched to the audience."),
             ]},
            {"type": "compare", "title": "Training users",
             "left": ("Methods", [
                 "Shadowing and desk-side support",
                 "Remote support",
                 "E-learning and simulation",
                 "VR, AR and smart boards",
                 "Gamified apps, e.g. Kahoot!, Padlet",
             ]),
             "right": ("Tools", [
                 "Crib sheets and smart sheets",
                 "Webinars and screencasts",
                 "VLEs and MLEs",
                 "Sandboxed practice environments",
                 "MOOCs",
             ])},
        ],
        "quiz": [
            ("Give a digital technology used in HR.", "Personnel systems or digital training."),
            ("What is a crib sheet?", "A short, quick-reference guide."),
            ("Why use a sandboxed environment for training?", "Users can practise without affecting live systems."),
            ("What should you consider when explaining a solution?", "The audience, and using clear, concise technical terms."),
        ],
        "activity": {
            "title": "Make a crib sheet and screencast",
            "time": "35 minutes",
            "format": "Individual",
            "steps": [
                "Choose a task: setting up MFA, sharing a file securely, or booking a meeting room.",
                "Write a one-page crib sheet for a non-technical user.",
                "Record a screencast of under two minutes showing the task.",
                "Get feedback from a partner and improve one thing.",
            ],
            "success": [
                "Steps are numbered and jargon-free",
                "Screenshots or recording match the steps",
                "Feedback acted on",
            ],
        },
        "exit": [
            "Which training method suits a busy manager?",
            "Why does CPD matter for support staff?",
            "How would you explain the benefit of a CRM to a sales team?",
        ],
    },
]
