"""Network Cabling specialism decks."""

NC2 = "02-occupational-specialisms/network-cabling/02-cabling-installation-and-testing.md"

DECKS = [
    {
        "area": "nc",
        "file": "network-cabling/01-signal-theory-and-data-transmission.pptx",
        "title": "Signal Theory and Data Transmission",
        "unit": "Network Cabling Content Area 2",
        "spec": "2.1, 2.7 to 2.10",
        "pages": [NC2],
        "objectives": [
            "Describe how data is represented, encapsulated and transmitted.",
            "Explain total internal reflection and single-mode and multi-mode fibre.",
            "Explain the causes of attenuation and the effects of poor fibre handling.",
            "Apply Ohm's law to copper cabling.",
        ],
        "starter": "Shine a torch down a long clear pipe. Why does less light come out of the far end?",
        "slides": [
            {"type": "bullets", "title": "Principles of data transmission",
             "bullets": [
                 "Data is represented as bits, bytes and packets.",
                 "Transmission is synchronous or asynchronous.",
                 "Links must handle error detection and correction, bandwidth limits, noise and compression.",
                 "Access methods: CSMA/CD on wired networks, CSMA/CA on wireless.",
                 "The NIC encapsulates data into frames, packets and datagrams with addresses and sequence numbers.",
             ],
             "callout": "Addressing: IPv4 (schemes, subnetting, masks) and IPv6 (address types)."},
            {"type": "compare", "title": "How fibre carries light",
             "left": ("Total internal reflection", [
                 "Light travels down the glass core",
                 "It reflects off the boundary with the cladding",
                 "Refraction principles keep it inside the core",
             ]),
             "right": ("Single-mode and multi-mode", [
                 "Single-mode: one ray, narrow core, long distance",
                 "Multi-mode: many rays, wider core, shorter distance",
             ])},
            {"type": "cards", "title": "Attenuation: losing signal over distance",
             "cards": [
                 ("Measured in dB", "Loss of signal strength along the cable."),
                 ("Absorption", "Light absorbed by particles in the glass; worse over distance."),
                 ("Scattering", "Light hits particles and is lost into the cladding."),
                 ("Bending", "Macrobends and microbends let light escape."),
             ],
             "notes": "Poor handling faults: dirty or damaged connectors (unreliable or no link), bending too tightly, and poor-quality cable or connectors."},
            {"type": "bullets", "title": "Ohm's law and copper cabling",
             "bullets": [
                 "V = I x R: voltage equals current times resistance.",
                 "More voltage gives more current.",
                 "More resistance gives less current.",
                 "Resistance rises with cable length, signal frequency and smaller cable size.",
             ],
             "callout": "Resistance is why copper has a maximum length: 90 m permanent link and 100 m total channel.",
             "notes": "Worked example: 12 V across 4 ohms gives 3 A. Double the resistance and the current halves."},
        ],
        "quiz": [
            ("What does CSMA/CD stand for?", "Carrier Sense Multiple Access with Collision Detection."),
            ("What keeps light inside a fibre core?", "Total internal reflection."),
            ("Which fibre type suits long distances?", "Single-mode."),
            ("Name two causes of attenuation.", "Any two of: absorption, scattering, macrobending, microbending."),
            ("Using V = I x R, what current flows with 10 V and 5 ohms?", "2 amps."),
        ],
        "activity": {
            "title": "Signal loss investigation",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Use the fibre loss figures given by your teacher for three links.",
                "Identify which link has a fault, and the most likely cause.",
                "Calculate current for three copper examples using Ohm's law.",
                "Explain why a 150 m copper run would be a problem.",
            ],
            "success": [
                "Faulty link found with evidence",
                "Calculations correct with units",
                "Maximum length explained using resistance",
            ],
        },
        "exit": [
            "Why is multi-mode fibre used for short runs?",
            "What happens to current if resistance increases?",
            "Name one way poor handling damages fibre.",
        ],
    },
    {
        "area": "nc",
        "file": "network-cabling/02-cable-media-connectors-and-standards.pptx",
        "title": "Cable Media, Connectors and Standards",
        "unit": "Network Cabling Content Area 2",
        "spec": "2.11 to 2.16",
        "pages": [NC2],
        "objectives": [
            "Compare copper and fibre media types and their uses.",
            "Explain the benefits of plenum-rated cable.",
            "Identify connectors, transceivers and termination points.",
            "Apply copper and fibre standards and termination methods.",
        ],
        "starter": "Why is most office cabling copper, but most links between buildings fibre?",
        "slides": [
            {"type": "compare", "title": "Copper and fibre",
             "left": ("Copper", [
                 "Durable, easy to handle, cheap to install",
                 "Can carry power (PoE)",
                 "Max 90 m permanent link, 100 m channel",
                 "UTP, STP, FTP, coaxial",
             ]),
             "right": ("Fibre", [
                 "Longer distances, higher bandwidth",
                 "Lightweight, less degradation",
                 "Limited by the laser quality at each end",
                 "Single-mode OS1/OS2; multi-mode OM3/OM4",
             ]),
             "notes": "Plenum-rated cable gives off less smoke and toxic fumes, burns less, keeps working at higher heat, and complies with the Construction Products Regulation (CPR)."},
            {"type": "cards", "title": "Connectors and transceivers",
             "cards": [
                 ("Copper connectors", "RJ-45, RJ-11, BNC, DB-9, DB-25, F-type."),
                 ("Fibre connectors", "LC, ST, SC, MT-RJ, MPO."),
                 ("Choosing a connector", "Mating type, locking (latch, screw, bayonet, APC or UPC), durability, size."),
                 ("Transceivers", "SFP, SFP+, GBIC, QSFP. Choose by duplex, bandwidth, WDM, rate and connector."),
             ]},
            {"type": "cards", "title": "Termination points",
             "cards": [
                 ("66 block", "Punch-down for telephone systems; 22 to 26 gauge wire; Cat3."),
                 ("110 block", "Higher speeds (Cat5 to Cat6a); replaced the 66 block."),
                 ("Patch panel", "Incoming cables terminate at the back; patch leads connect at the front."),
             ]},
            {"type": "table", "title": "Copper cable standards",
             "header": ["Cable", "Frequency (MHz)", "Max length", "Ethernet rate"],
             "widths": [1.5, 2.2, 1.8, 3],
             "rows": [
                 ["Cat5e", "100 (up to 350)", "100 m", "1 Gbps (1000BASE-T)"],
                 ["Cat6", "250 (up to 550)", "100 m", "1 or 10 Gbps"],
                 ["Cat6a", "500 (up to 550)", "100 m", "10 Gbps (10GBASE-T)"],
                 ["Cat7", "600", "100 m", "10 Gbps"],
                 ["RG59 / RG6 coax", "High / low bandwidth", "229 m / 305 m", "10 Mbps"],
             ],
             "notes": "The full tables for Cat3 and Cat5 and for fibre OM1 to OM4 by wavelength are on the wiki page."},
            {"type": "compare", "title": "Termination methods and standards",
             "left": ("Methods", [
                 "Patching to a patch panel",
                 "RJ45 for Ethernet",
                 "Fusion splicing: permanent, single-mode",
                 "Mechanical splicing: non-permanent, single or multi-mode",
             ]),
             "right": ("Standards", [
                 "TIA/EIA-568A and 568B pin-outs",
                 "Straight-through: same standard at both ends",
                 "Crossover: 568A at one end, 568B at the other",
                 "Ethernet: 100BaseT through 10GBaseT",
             ])},
        ],
        "quiz": [
            ("What is the maximum copper channel length?", "100 metres."),
            ("Which fibre connector is small and common in switches?", "LC."),
            ("What does plenum-rated cable reduce in a fire?", "Smoke and toxic fumes."),
            ("Which punch-down block supports Cat6?", "The 110 block."),
            ("What makes a crossover cable?", "568A at one end and 568B at the other."),
        ],
        "activity": {
            "title": "Spec the materials",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Scenario: a two-storey office with 40 desks and a link to a warehouse 400 m away.",
                "Choose cable types for the desks, riser and warehouse link.",
                "Choose connectors, transceivers and termination points.",
                "Justify each choice using the standards tables.",
            ],
            "success": [
                "Lengths stay within standards",
                "Fibre type suits the 400 m link",
                "Plenum cable considered where needed",
            ],
        },
        "exit": [
            "When would you use single-mode fibre?",
            "Name two copper connectors.",
            "What is the difference between fusion and mechanical splicing?",
        ],
    },
    {
        "area": "nc",
        "file": "network-cabling/03-structured-cabling-design-and-installation.pptx",
        "title": "Structured Cabling Design and Installation",
        "unit": "Network Cabling Content Area 2",
        "spec": "2.2 to 2.6, 2.25",
        "pages": [NC2],
        "objectives": [
            "Select tools and equipment for testing, terminating and access.",
            "Install and configure networking devices to a design specification.",
            "Describe what a network design specification contains.",
            "Install fixtures and fittings such as cabinets, racks and containment.",
        ],
        "starter": "You arrive at a new building to install a network. What documents would you want in your hand before you start?",
        "slides": [
            {"type": "cards", "title": "Tools and equipment",
             "cards": [
                 ("Testing", "Multimeter, tone generator and probe, OTDR, light source and power meter, spectrum analyser, continuity tester."),
                 ("Terminating", "Crimper, strippers, cutters, punch-down tool, fusion splicer, fibre cleaning and cleave tools."),
                 ("Access", "MEWPs, low-level access towers, step ladders."),
                 ("Fixtures", "Prebuilt or flat-pack cabinets, racks, trunking and containment."),
             ],
             "notes": "Students assess the job, select the right tool and use it safely per manufacturer guidance."},
            {"type": "process", "title": "Installing a networking device",
             "steps": [
                 ("Locate", "Find its position in the design spec."),
                 ("Check", "Equipment matches the spec."),
                 ("Fit", "Confirm space, power and cooling."),
                 ("Rack", "Mount the device."),
                 ("Test", "Check it works."),
                 ("Configure", "Set it up to the requirement."),
             ],
             "notes": "Devices include firewalls, routers, switches with SFP modules, access points, VoIP endpoints, CCTV and servers."},
            {"type": "cards", "title": "The network design specification",
             "cards": [
                 ("Statement of requirement", "What the customer needs."),
                 ("Bill of materials", "Every component and quantity."),
                 ("Design documents", "Floor plans, power and cooling, containment, cable routes."),
                 ("Installation admin", "Labelling, certification, warranty, performance declarations."),
                 ("Procedures and penalties", "How to install, and contractual penalties."),
                 ("Future proofing", "Room to grow."),
             ],
             "notes": "Design is shaped by logical and physical topology, standards, permanent links and channels, campus distribution and passive and active design."},
            {"type": "process", "title": "Installing fixtures and fittings",
             "steps": [
                 ("Interpret", "Read the cabling design spec."),
                 ("Survey", "Compare the site: space, power, cooling."),
                 ("Build", "Construct cabinets and racks per manufacturer guidance."),
                 ("Contain", "Add trunking and containment."),
                 ("Arrange and test", "Lay out kit to spec and test compliance."),
             ]},
        ],
        "quiz": [
            ("What does an OTDR test?", "Fibre links, locating faults and loss along the cable."),
            ("What is a bill of materials?", "A list of every component and quantity needed."),
            ("What three things must be checked before racking a device?", "Space, power and cooling."),
            ("What is a MEWP?", "A mobile elevating work platform."),
        ],
        "activity": {
            "title": "Read the design spec",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "Study the sample floor plan and statement of requirement from your teacher.",
                "Calculate cable lengths and quantities for each outlet.",
                "Produce a bill of materials.",
                "Flag three potential issues with the design.",
            ],
            "success": [
                "Lengths include slack and stay under 90 m",
                "Bill of materials is complete",
                "Issues are realistic and explained",
            ],
        },
        "exit": [
            "Why is future-proofing part of the design?",
            "Name one terminating tool for fibre.",
            "What goes on a label at a patch panel?",
        ],
    },
    {
        "area": "nc",
        "file": "network-cabling/04-testing-certification-and-troubleshooting.pptx",
        "title": "Testing, Certification and Troubleshooting",
        "unit": "Network Cabling Content Area 2",
        "spec": "2.17, 2.18, 2.26 to 2.29",
        "pages": [NC2],
        "objectives": [
            "Apply a troubleshooting process to cabling faults.",
            "Identify common physical and technical failures.",
            "Test and certify copper and fibre to recognised standards.",
            "Explain the consequences of poor workmanship.",
        ],
        "starter": "A new desk outlet only connects at 100 Mbps instead of 1 Gbps. What could cause that?",
        "slides": [
            {"type": "process", "title": "Troubleshooting process",
             "steps": [
                 ("Identify", "A fault, or found in routine monitoring."),
                 ("Diagnose", "Gather info, compare with past data, narrow down."),
                 ("Test", "Test the shortlist."),
                 ("Resolve", "Fix, document and prevent recurrence."),
             ],
             "caption": "Maintenance can be predictive (replace before failure) or reactive (run to failure)."},
            {"type": "compare", "title": "Common failures",
             "left": ("Physical", [
                 "Wrong cable type or pin-out",
                 "Open or short circuit",
                 "Bad port, bent pins, cable damage",
                 "Duplex or speed mismatch",
                 "Wrong containment",
             ]),
             "right": ("Technical", [
                 "Attenuation, latency, jitter",
                 "Crosstalk and EMI",
                 "Transceiver mismatch, TX/RX reversed",
                 "Bottlenecks and hardware errors",
                 "Spotted via CRC errors, lost packets, address conflicts",
             ])},
            {"type": "table", "title": "Testing standards",
             "header": ["Standard", "Covers"],
             "widths": [3, 5.6],
             "rows": [
                 ["TIA/EIA-568-B.2-1", "Cat6 transmission performance"],
                 ["TIA/EIA-568-B.1-10", "Augmented Cat6"],
                 ["TIA/EIA-TSB-155-A", "Cat6 support for 10GBASE-T"],
                 ["TIA-1152", "Field test instrument requirements"],
                 ["IEC 61935-1", "Reference measurement procedures"],
             ]},
            {"type": "compare", "title": "Certifying copper and fibre",
             "left": ("Copper", [
                 "Continuity tester, performance tester, certifier",
                 "Wiremap",
                 "Cable length",
                 "Near-end crosstalk (NEXT)",
             ]),
             "right": ("Fibre", [
                 "OLTS, light source and power meter",
                 "OTDR",
                 "Fibre inspection scope",
                 "Tier 1 and tier 2 testing",
             ]),
             "notes": "Follow a test plan (scope, approach, resources, schedule), then interpret results against manufacturer tolerances."},
            {"type": "compare", "title": "Why poor workmanship matters",
             "left": ("Network consequences", [
                 "Slower speeds and more interference",
                 "Harder maintenance and shorter cable life",
                 "Weaker security",
                 "Bad labelling slows every future fault-find",
             ]),
             "right": ("Business consequences", [
                 "Cost of revisits",
                 "SLA and warranty penalties",
                 "Reputational damage and delayed payment",
                 "Failed audits",
             ])},
        ],
        "quiz": [
            ("What is the difference between predictive and reactive maintenance?", "Predictive replaces before failure; reactive runs to failure."),
            ("Name two physical cabling failures.", "Any two, e.g. wrong pin-out, open circuit, bent pins."),
            ("What does NEXT stand for?", "Near-end crosstalk."),
            ("Which tool locates a break along a fibre?", "An OTDR."),
            ("Give one business consequence of failing certification.", "E.g. revisit costs, SLA penalties, reputational damage."),
        ],
        "activity": {
            "title": "Fault-find the patch leads",
            "time": "30 minutes",
            "format": "Pairs, practical",
            "steps": [
                "Test the six numbered patch leads your teacher provides.",
                "Record the wiremap and length result for each.",
                "Identify the fault in each failing lead.",
                "Write a short certification summary for the passing leads.",
            ],
            "success": [
                "Every lead tested and recorded",
                "Faults named correctly, e.g. split pair, open",
                "Results compared with tolerances",
            ],
            "notes": "Prepare leads with a split pair, a reversed pair, an open conductor and one good lead.",
        },
        "exit": [
            "Why must every cable be tested, not just a sample?",
            "What might cause a CRC error?",
            "Why does labelling matter?",
        ],
    },
    {
        "area": "nc",
        "file": "network-cabling/05-health-safety-and-compliance-for-cabling.pptx",
        "title": "Health, Safety and Compliance for Cabling",
        "unit": "Network Cabling Content Area 2",
        "spec": "2.19 to 2.24",
        "pages": [NC2],
        "objectives": [
            "Identify supporting media and how to protect it during installation.",
            "Describe the standards and legislation that govern cabling work.",
            "Respond correctly to suspected asbestos.",
            "Apply risk management to working at height and in confined spaces.",
        ],
        "starter": "You lift a ceiling tile and see old, crumbly grey board. What should you do?",
        "slides": [
            {"type": "bullets", "title": "Protecting supporting media",
             "bullets": [
                 "Supporting media: telecoms, CCTV, alarms, AV, wireless access points, IoT devices.",
                 "Avoid sharing containment routes with other services.",
                 "Label service cables.",
                 "Check local records before starting.",
                 "Apply change management.",
             ],
             "callout": "Segregate data cables from electrical cables in line with BS EN 50174."},
            {"type": "table", "title": "Key cabling standards",
             "header": ["Standard", "Covers"],
             "widths": [2.8, 5.8],
             "rows": [
                 ["BS EN 50173 / ISO/IEC 11801", "Generic cabling systems"],
                 ["BS EN 50174", "Installation specification and quality"],
                 ["BS EN 50310", "Bonding and earthing"],
                 ["BS EN 60825", "Optical fibre safety"],
                 ["BS 6701 and BS 7671", "Installation and wiring regulations"],
                 ["IEEE 802.3 / 802.16", "Ethernet / WiMAX"],
                 ["TIA/EIA-568-B, IEC 60364", "Cable categories; electrical installations"],
             ]},
            {"type": "cards", "title": "Legislation",
             "cards": [
                 ("HSWA 1974", "The general duty of care."),
                 ("Electricity at Work 1989", "Safe work near electrical systems."),
                 ("Work at Height 2005", "Planning and equipment for work at height."),
                 ("COSHH 2002", "Hazardous substances."),
                 ("Confined Spaces 1997", "Safe entry and rescue plans."),
                 ("PPE 2018 and Asbestos 2012", "Protective equipment; control of asbestos."),
             ]},
            {"type": "process", "title": "If you suspect asbestos",
             "steps": [
                 ("Stop", "Stop work immediately."),
                 ("Inform", "Tell the relevant people."),
                 ("Isolate", "Restrict access to the area."),
                 ("Investigate", "Use an asbestos-registered professional."),
                 ("Act", "Removal, sealing or air-quality checks."),
             ]},
            {"type": "compare", "title": "Working at height and in confined spaces",
             "left": ("At height", [
                 "Risk assess before starting",
                 "Use MEWPs safely",
                 "Assemble, inspect and dismantle towers per the manufacturer",
                 "Record findings",
             ]),
             "right": ("Confined spaces", [
                 "Same risk management process",
                 "Correct PPE, properly maintained",
                 "Plan for rescue",
                 "Record findings clearly",
             ])},
        ],
        "quiz": [
            ("Which standard covers segregation of data and power cables?", "BS EN 50174."),
            ("What is the first thing to do if you suspect asbestos?", "Stop work immediately."),
            ("Which regulations cover work in ceiling voids and ducts?", "Confined Spaces Regulations 1997."),
            ("Which standard covers optical fibre safety?", "BS EN 60825."),
        ],
        "activity": {
            "title": "Method statement",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "Scenario: run 20 new cables through a 1970s school corridor ceiling, 3.5 m high.",
                "Write a method statement with a risk assessment.",
                "Name the legislation and standards that apply at each step.",
                "Include what to do if ACM or live services are found.",
            ],
            "success": [
                "Height and asbestos risks covered",
                "Correct legislation named",
                "Clear stop and escalate steps",
            ],
        },
        "exit": [
            "Why must you check local records before drilling?",
            "Name one piece of access equipment and its main hazard.",
            "Who can investigate suspected asbestos?",
        ],
    },
]
