"""
Decks shared across specialisms.

Digital Infrastructure, Digital Support and Network Cabling share almost the
same Content Area 1 (security procedures and controls), so one set of decks
serves all three. Sources of knowledge is studied by all four specialisms.
"""

DI1 = "02-occupational-specialisms/digital-infrastructure/01-security-procedures-and-controls.md"
DI2 = "02-occupational-specialisms/digital-infrastructure/02-physical-and-virtual-infrastructure.md"
DS1 = "02-occupational-specialisms/digital-support/01-security-procedures-and-controls.md"
NC1 = "02-occupational-specialisms/network-cabling/01-security-procedures-and-controls.md"
SEC = [DS1, DI1, NC1]
SOK = [
    "02-occupational-specialisms/digital-support/03-sources-of-knowledge.md",
    "02-occupational-specialisms/digital-infrastructure/03-sources-of-knowledge.md",
    "02-occupational-specialisms/network-cabling/03-sources-of-knowledge.md",
    "02-occupational-specialisms/cyber-security/03-sources-of-knowledge.md",
    "01-core-component/01-core-paper-1.md",
]

# Shared decks send students to the specialisms overview, since the matching
# revision notes live on each specialism's own page.
REVISE = {
    "revise_title": "Security Procedures and Controls, on your specialism's page",
    "revise_page": "02-occupational-specialisms/00-overview.md",
}
REVISE_SOK = {
    "revise_title": "Sources of Knowledge, on your specialism's page",
    "revise_page": "02-occupational-specialisms/00-overview.md",
}

DECKS = [
    {
        "area": "shared",
        "file": "shared/01-business-security-controls.pptx",
        "title": "Business Security Controls",
        "unit": "Specialism Content Area 1",
        "spec": "1.1 to 1.7",
        "pages": SEC,
        **REVISE,
        "objectives": [
            "Describe the six types of business control and when each acts.",
            "Give physical, administrative and technical examples of each control.",
            "Select, apply and monitor a suitable control for an identified risk.",
            "Explain the NCSC Cyber Essentials controls.",
        ],
        "starter": "A burglar walks past an office at night. List everything that might stop them, "
                   "catch them, or limit the damage they do.",
        "slides": [
            {"type": "process", "title": "When each control acts",
             "steps": [
                 ("Directive", "Tells people what to do."),
                 ("Deterrent", "Discourages an attempt."),
                 ("Preventative", "Stops the incident happening."),
                 ("Detective", "Spots it while or after it happens."),
                 ("Corrective", "Limits damage and stops recurrence."),
                 ("Compensating", "Backup when a primary control fails."),
             ],
             "notes": "Link back to the starter: sort the class's ideas into these six columns."},
            {"type": "cards", "title": "Preventative controls",
             "cards": [
                 ("Physical", "Anti-pick locks, fences, bollards, gates, cages, flood defences, air conditioning."),
                 ("Combined or managed access", "Card readers, biometric readers, video verification, PINs."),
                 ("Administrative", "Separation of duties and role-based access, so no one person has too much privilege."),
                 ("Technical", "Allowlists and denylists, access control lists, sandboxing, device hardening, certificate authorities."),
             ]},
            {"type": "table", "title": "The other five controls",
             "header": ["Control", "Physical example", "Administrative example"],
             "widths": [1.8, 3.2, 4],
             "rows": [
                 ["Detective", "CCTV, motion sensors", "Temperature and error logs, audits of who entered the site"],
                 ["Corrective", "Fire and gas suppression", "SOPs for what to do when a fire is detected"],
                 ["Deterrent", "Guards, alarms, visible surveillance", "Fire drills, codes of conduct, acceptable use policies"],
                 ["Directive", "Signage, mandatory ID badges", "Security policies, compulsory 'human firewall' training"],
                 ["Compensating", "Environmental temperature controls", "Role-based awareness training, monitoring SOPs"],
             ]},
            {"type": "cards", "title": "NCSC Cyber Essentials: five controls",
             "cards": [
                 ("Boundary firewalls", "Control traffic between your network and the internet."),
                 ("Secure configuration", "Remove defaults and unneeded features; enable MFA."),
                 ("Access control", "Give users only the access they need."),
                 ("Malware protection", "Anti-malware kept up to date."),
                 ("Patch management", "Apply security updates promptly."),
             ],
             "notes": "Practical skills include setting up a domain with group policies and password rules, deploying a certificate authority, and applying access control methods (MAC, DAC, ABAC, RBAC)."},
            {"type": "process", "title": "Applying and monitoring controls",
             "steps": [
                 ("Review the risk", "Gather information from systems and users."),
                 ("Select", "Choose the right control type or types."),
                 ("Apply", "Put the control in place, following procedure."),
                 ("Monitor", "Check it keeps working and adjust."),
             ],
             "caption": "Always comply with regulation (e.g. data protection law) and organisational procedure."},
        ],
        "quiz": [
            ("Is CCTV a preventative or detective control?", "Detective (it can also deter when visible)."),
            ("Give an example of a corrective control.", "Fire or gas suppression, or a fire response SOP."),
            ("What is a compensating control?", "A safeguard used when a primary control is not available or fails."),
            ("Name three of the five Cyber Essentials controls.", "Any three of: boundary firewalls, secure configuration, access control, malware protection, patch management."),
            ("What does separation of duties prevent?", "One person holding excessive privilege."),
        ],
        "activity": {
            "title": "Control audit",
            "time": "25 minutes",
            "format": "Small groups",
            "steps": [
                "Walk around (or picture) the college IT areas.",
                "Find at least one control of each of the six types.",
                "Classify each as physical, administrative or technical.",
                "Identify one gap and recommend a control to fill it.",
            ],
            "success": [
                "All six control types found",
                "Classifications are correct",
                "Recommendation is realistic and justified",
            ],
        },
        "exit": [
            "Which control type would a 'Staff only' sign be?",
            "Why do organisations layer several controls?",
            "Which Cyber Essentials control would stop an unpatched laptop being exploited?",
        ],
    },
    {
        "area": "shared",
        "file": "shared/02-disaster-recovery-and-backup.pptx",
        "title": "Disaster Recovery, Continuity and Backup",
        "unit": "Specialism Content Area 1",
        "spec": "DRP, BCP, RTO/RPO/MTBF/MTTR, SLAs, backups (1.8 to 1.12, 1.22 to 1.23; DI 2.18 to 2.19)",
        "pages": SEC + [DI2],
        **REVISE,
        "objectives": [
            "Explain the difference between a disaster recovery plan and a business continuity plan.",
            "Describe how a DRP is built and tested.",
            "Define RTO, RPO, MTBF and MTTR and explain SLAs.",
            "Compare backup types and the criteria for a backup strategy.",
        ],
        "starter": "Ransomware has encrypted every file on your college's server. What do you need to get "
                   "working again, and in what order?",
        "slides": [
            {"type": "compare", "title": "DRP and BCP",
             "left": ("Disaster recovery plan (DRP)", [
                 "Restores IT systems after a disruption",
                 "Physical: backups, off-site server storage",
                 "Restores access and functionality",
                 "Replaces failed infrastructure",
             ]),
             "right": ("Business continuity plan (BCP)", [
                 "Keeps the whole business running during disruption",
                 "Alternative premises and processes",
                 "Users can work away from the main site",
                 "The DRP sits inside the wider BCP",
             ])},
            {"type": "process", "title": "Building a DRP",
             "steps": [
                 ("Scope", "Site, organisation, department or individual."),
                 ("Gather", "Past outages, inventories, contacts."),
                 ("Risk assess", "Assets, threats, likelihood and impact."),
                 ("Create", "Write the plan and identify resources."),
                 ("Sign off", "Get approval."),
                 ("Test and improve", "Test regularly, review, audit and amend."),
             ]},
            {"type": "cards", "title": "Measures that size resilience",
             "cards": [
                 ("RTO", "Recovery Time Objective: how quickly a system must be back."),
                 ("RPO", "Recovery Point Objective: how much data loss is tolerable, measured in time."),
                 ("MTBF", "Mean Time Between Failures: how reliable an asset is."),
                 ("MTTR", "Mean Time To Repair: average time to restore a failed system."),
             ],
             "notes": "Worked example: if the RPO is 4 hours, backups must run at least every 4 hours. Procedures that support these: SOPs (installation, backup, set-up) and SLAs (uptime, response and resolution times)."},
            {"type": "table", "title": "Backup types",
             "header": ["Type", "What is copied", "Backup speed", "Restore needs"],
             "widths": [1.6, 3.4, 1.6, 2.4],
             "rows": [
                 ["Full", "Everything", "Slowest", "Just the full backup"],
                 ["Incremental", "Changes since the last backup of any kind", "Fastest", "Full plus every incremental"],
                 ["Differential", "Changes since the last full backup", "Medium", "Full plus the latest differential"],
                 ["Mirror", "An exact live copy", "Continuous", "The mirror, but deletions are copied too"],
             ],
             "caption": "Criteria for a backup strategy: frequency, source, destination and storage medium (LTO tape, cloud, disk)."},
        ],
        "quiz": [
            ("What is the difference between a DRP and a BCP?", "A DRP restores IT systems; a BCP keeps the wider business running."),
            ("What does RPO measure?", "The maximum tolerable data loss, measured in time."),
            ("Which backup type is quickest to make but slowest to restore?", "Incremental."),
            ("What does an SLA define?", "Agreed uptime and response and resolution times."),
            ("Why must a DRP be tested?", "To prove it works and find gaps before a real disaster."),
        ],
        "activity": {
            "title": "Design a backup schedule",
            "time": "20 minutes",
            "format": "Pairs",
            "steps": [
                "A small online shop has an RPO of 1 hour and an RTO of 4 hours.",
                "Choose backup types and a weekly schedule that meets the RPO.",
                "Choose where each backup is stored and on what medium.",
                "Explain how the shop would restore on a Thursday afternoon.",
            ],
            "success": [
                "Schedule meets the RPO",
                "At least one copy stored off-site",
                "Restore steps are in the right order",
            ],
        },
        "exit": [
            "Define MTTR in your own words.",
            "Why keep one backup off-site?",
            "What is the risk of relying only on a mirror?",
        ],
    },
    {
        "area": "shared",
        "file": "shared/03-risk-management-and-threat-assessment.pptx",
        "title": "Risk Management and Threat Assessment",
        "unit": "Specialism Content Area 1",
        "spec": "Impacts, risk process, threat analysis, risk response, penetration testing (1.9 to 1.21)",
        "pages": SEC,
        **REVISE,
        "objectives": [
            "Describe the impacts of realised threats and common critical-system vulnerabilities.",
            "Apply the five-step risk management process.",
            "Use qualitative and quantitative threat analysis tools.",
            "Choose a risk response and describe the penetration testing process.",
        ],
        "starter": "Name three things that could stop a company's network working tomorrow. "
                   "Which is most likely? Which would hurt most?",
        "slides": [
            {"type": "cards", "title": "Impacts of realised threats",
             "cards": [
                 ("Danger to life", "Health and safety breaches."),
                 ("Privacy", "Data breaches and identity theft."),
                 ("Property and resources", "Physical damage."),
                 ("Economic", "Financial loss."),
                 ("Reputational", "Damage to the brand."),
                 ("Legal", "Fines and prosecution."),
             ],
             "notes": "Vulnerabilities in critical systems: unauthorised physical access to ports, weak account control, single points of failure, open USB and network ports, unsecured wireless."},
            {"type": "process", "title": "The risk management process",
             "steps": [
                 ("Identify", "Risks, threats and vulnerabilities."),
                 ("Probability", "How likely: high, medium or low."),
                 ("Impact", "Extent of possible damage, e.g. asset value."),
                 ("Prioritise", "Rank by probability x impact; assign an owner."),
                 ("Mitigate", "Reduce the probability or the impact."),
             ]},
            {"type": "compare", "title": "Analysing threats",
             "left": ("Qualitative (non-numeric)", [
                 "RAG rating",
                 "Red: high risk, act immediately",
                 "Amber: moderate, watch closely",
                 "Green: low, no immediate action",
             ]),
             "right": ("Quantitative (numeric) and tools", [
                 "Numbers for effects such as cost overrun",
                 "Annualised Loss Expectancy (ALE)",
                 "Fault tree and impact analysis, FMECA",
                 "CRAMM, SWOT analysis",
                 "Risk register with a RAG rating per risk",
             ])},
            {"type": "cards", "title": "Threat assessment factors",
             "cards": [
                 ("Environmental", "Extreme weather, natural disaster, pests, humidity, air quality."),
                 ("Manmade internal", "Malicious or accidental staff and contractor actions."),
                 ("Manmade external", "Malware, hacking, social engineering, third parties, terrorism."),
                 ("Technological", "Disk, RAM or power failure, misconfiguration, software corruption, change."),
                 ("Political", "Changes in legislation."),
             ],
             "notes": "Risk assessment in context: apply HSE guidance, run a PESTLE analysis of the project, identify internal and external risk, quantify impact on asset value, and record findings with correct technical terms."},
            {"type": "cards", "title": "Four risk responses",
             "cards": [
                 ("Accept", "The impact is judged acceptable."),
                 ("Avoid", "Change the scope to sidestep the risk."),
                 ("Mitigate", "Reduce the probability or impact."),
                 ("Transfer", "Contractually pass the risk to someone else, e.g. insurance or outsourcing."),
             ]},
            {"type": "process", "title": "The penetration testing process",
             "steps": [
                 ("Engage", "Agree scope with the customer."),
                 ("Gather", "Collect information about the target."),
                 ("Scan", "Discover hosts and services."),
                 ("Test", "Look for vulnerabilities."),
                 ("Exploit", "Attempt access, within agreed limits."),
                 ("Review and act", "Analyse results and fix."),
             ],
             "caption": "A mitigation strategy weighs the response, user profile, cost and benefit, owner, escalation route and contingency, then is monitored for continuous improvement."},
        ],
        "quiz": [
            ("Name the five steps of the risk management process.", "Identify, probability, impact, prioritise, mitigate."),
            ("What does a red RAG rating mean?", "High risk needing immediate action."),
            ("Buying cyber insurance is which risk response?", "Transfer."),
            ("Give one technological threat factor.", "E.g. disk failure, misconfiguration, software corruption."),
            ("What must happen before a penetration test starts?", "Customer engagement to agree scope and permission."),
        ],
        "activity": {
            "title": "Build a risk register",
            "time": "30 minutes",
            "format": "Small groups",
            "steps": [
                "Scenario: a company is introducing bring your own device (BYOD) for 50 staff.",
                "Identify at least six risks across the threat factor types.",
                "Rate each for probability and impact, then give a RAG rating.",
                "Choose a response and owner for each risk.",
            ],
            "success": [
                "At least four threat factor types covered",
                "RAG ratings follow from the scores",
                "Every risk has a response and an owner",
            ],
        },
        "exit": [
            "What is the difference between qualitative and quantitative analysis?",
            "When would you accept a risk?",
            "Why must a penetration tester have written permission?",
        ],
    },
    {
        "area": "shared",
        "file": "shared/04-technical-security-and-network-protection.pptx",
        "title": "Technical Security and Network Protection",
        "unit": "Specialism Content Area 1",
        "spec": "Technical controls, encryption, network security, access control, topologies and vulnerabilities (1.19 to 1.33)",
        "pages": SEC,
        **REVISE,
        "objectives": [
            "Describe technical security controls, including device hardening, RMM and vulnerability scanning.",
            "Explain encryption for data at rest and in transit.",
            "Explain access control models and methods of securing network traffic.",
            "Match common vulnerabilities to suitable controls.",
        ],
        "starter": "You are given a brand new laptop to set up for a manager. What would you change before handing it over, "
                   "to make it more secure?",
        "slides": [
            {"type": "cards", "title": "Technical security controls",
             "cards": [
                 ("Cyber Essentials", "Firewalls, secure configuration, access control, malware protection, patching."),
                 ("Device hardening", "Remove unneeded programs, accounts and ports; change default passwords."),
                 ("RMM", "Remote monitoring and management of devices across the network."),
                 ("Vulnerability scanning", "Port and device scans to find weak points."),
                 ("Segmentation and MFA", "Split the network to contain attacks; require more than one factor to log in."),
             ]},
            {"type": "compare", "title": "Encryption as risk mitigation",
             "left": ("Symmetric and asymmetric", [
                 "Symmetric: one shared key encrypts and decrypts, e.g. card payments",
                 "Asymmetric: public and private key pair, e.g. encrypted email",
             ]),
             "right": ("At rest and in transit", [
                 "At rest: full disk encryption",
                 "HSM: hardware security module safeguarding keys",
                 "TPM: chip storing device-specific keys",
                 "In transit: SSL and its successor TLS",
             ])},
            {"type": "table", "title": "Access control models",
             "header": ["Model", "How access is decided"],
             "widths": [1.5, 6.5],
             "rows": [
                 ["IDS / IPS", "Intrusion detection spots threats in traffic; intrusion prevention blocks them"],
                 ["NAC", "Network access control enforces policy on devices and users joining the network"],
                 ["MAC", "Mandatory: a hierarchy of security levels set centrally"],
                 ["DAC", "Discretionary: the owner of a resource decides"],
                 ["ABAC", "Attribute based: user, resource and environment attributes"],
                 ["RBAC / RuBAC", "Role based: by job role; rule based: by a list of rules"],
             ],
             "notes": "Principles behind all of these: the CIA triad and IAAA (identification, authentication, authorisation, accountability)."},
            {"type": "compare", "title": "Securing network traffic",
             "left": ("Physical", [
                 "Software-defined networking with TLS",
                 "DMZ: a buffer zone for public-facing servers",
                 "Air gapping: no connection at all",
             ]),
             "right": ("Virtual", [
                 "VLANs separate traffic on shared hardware",
                 "VPNs and IPSec encrypt traffic",
                 "VRF: separate routing tables on one router",
                 "Subnets and virtual air gaps",
             ]),
             "notes": "Connected devices: WPA2/WPA3, device authentication, encryption, patching, MFA, single logout. Minimum standard principles: identify, protect, detect, respond, recover."},
            {"type": "table", "title": "Common vulnerabilities and their controls",
             "header": ["Vulnerability", "Control"],
             "widths": [3.5, 5],
             "rows": [
                 ["Missing patches or firmware", "Patch management software and test devices"],
                 ["Weak or default passwords", "NCSC-aligned minimum password rules, lockout and reset policy"],
                 ["Insecure BIOS / UEFI", "Review and update settings, set a password"],
                 ["Misconfigured permissions", "Test and schedule audits, remove leavers' access"],
                 ["Insecure disposal", "Data wiping and WEEE compliance"],
                 ["DHCP spoofing, VLAN hopping", "DHCP snooping, network monitoring (DI)"],
             ]},
        ],
        "quiz": [
            ("What is device hardening?", "Removing unneeded programs, accounts and ports and changing defaults to reduce vulnerabilities."),
            ("Which type of encryption uses a public and private key?", "Asymmetric."),
            ("What is the difference between an IDS and an IPS?", "An IDS detects threats; an IPS also blocks them."),
            ("What is a DMZ?", "A buffer network between the internet and the internal network, for public-facing servers."),
            ("Which access control model gives access by job role?", "RBAC."),
        ],
        "activity": {
            "title": "Harden a device",
            "time": "30 minutes",
            "format": "Pairs, on a lab PC or VM",
            "steps": [
                "Record the current state: open ports, installed software, accounts, update status.",
                "Apply hardening: remove unneeded software, disable unused accounts, apply updates, set password rules.",
                "Install or configure anti-malware and the host firewall.",
                "Run a scan to confirm the changes and record the before and after.",
            ],
            "success": [
                "Before and after evidence recorded",
                "Each change linked to a vulnerability",
                "Configuration tested, not assumed",
            ],
            "notes": "Use a disposable VM so students cannot break a shared machine.",
        },
        "exit": [
            "What does a TPM store?",
            "Why put a web server in a DMZ?",
            "Name one control for misconfigured permissions.",
        ],
    },
    {
        "area": "shared",
        "file": "shared/05-security-law-standards-and-policy.pptx",
        "title": "Security Law, Standards and Policy",
        "unit": "Specialism Content Area 1",
        "spec": "Policies, legislation, standards and the importance of cyber security (1.23 to 1.31)",
        "pages": SEC,
        **REVISE,
        "objectives": [
            "Explain the purpose of organisational digital use and health and safety policies.",
            "Describe UK GDPR, the Data Protection Act 2018 and the Computer Misuse Act.",
            "Describe ISO 27001, PCI DSS, NCSC 10 Steps and OWASP.",
            "Explain why cyber security matters to organisations and society.",
        ],
        "starter": "Your company lets staff work from home on their own laptops. What rules would you want in place?",
        "slides": [
            {"type": "compare", "title": "Policies that reduce risk",
             "left": ("Digital use policy", [
                 "Network and internet usage and monitoring",
                 "Bring your own device (BYOD)",
                 "Working from home, with a DSE assessment",
                 "Password renewal",
                 "Software update discipline",
             ]),
             "right": ("Health and safety policy", [
                 "Lone working",
                 "Manual handling",
                 "Working at height",
                 "Fire safety",
                 "RIDDOR 2013 reporting",
             ]),
             "notes": "All changes should go through a change procedure: approved, documented and periodically audited. Students must explain the security impact of not following each policy."},
            {"type": "cards", "title": "Key legislation",
             "cards": [
                 ("UK GDPR", "Standardises how personal data is used, stored and transferred."),
                 ("Data Protection Act 2018", "The UK's implementation: fair, lawful, transparent, limited, accurate, secure."),
                 ("Computer Misuse Act 1990", "Unauthorised access; access with intent; acts impairing a computer's operation."),
             ]},
            {"type": "table", "title": "Standards and best practice",
             "header": ["Standard", "What it does"],
             "widths": [2.3, 6],
             "rows": [
                 ["ISO 27001", "Certifiable information security management standard"],
                 ["PCI DSS", "Protects card payments: secure network, cardholder data, access control, monitoring"],
                 ["NCSC 10 Steps", "User education, home working, secure config, removable media, privileges, incidents, monitoring, malware, network, risk"],
                 ["OWASP", "Shares security tools, education and a community to improve software security"],
             ]},
            {"type": "compare", "title": "Why cyber security matters",
             "left": ("To organisations", [
                 "Protect systems, devices and cloud availability",
                 "Protect personal and commercial data",
                 "Enforce password policy",
                 "Comply with the law",
                 "Defend against cybercrime",
             ]),
             "right": ("To society", [
                 "Protect privacy",
                 "Prevent prejudice and ensure equal opportunity",
                 "Prevent identity theft",
                 "DPA 2018 rights: be informed, access, correct, erase, restrict, port, object",
             ])},
        ],
        "quiz": [
            ("Which Act makes unauthorised access to a computer a crime?", "The Computer Misuse Act 1990."),
            ("Which standard protects card payments?", "PCI DSS."),
            ("What is ISO 27001?", "A certifiable information security management standard."),
            ("Name three rights individuals have under DPA 2018.", "Any three of: be informed, access, rectify, erase, restrict, portability, object."),
            ("What does RIDDOR cover?", "Reporting of injuries, diseases and dangerous occurrences."),
        ],
        "activity": {
            "title": "Write a BYOD policy",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Write a one-page BYOD policy for a 50-person company.",
                "Include at least six rules.",
                "Link each rule to a law, standard or NCSC step.",
                "State the security impact if staff ignore each rule.",
            ],
            "success": [
                "Rules are clear and enforceable",
                "Each rule is linked to legislation or a standard",
                "Impacts are specific",
            ],
        },
        "exit": [
            "Why does a company need a change procedure?",
            "Which standard would a web developer use to improve software security?",
            "Give one reason cyber security matters to society.",
        ],
    },
    {
        "area": "shared",
        "file": "shared/06-sources-of-knowledge.pptx",
        "title": "Researching and Evaluating Sources of Knowledge",
        "unit": "Specialism Content Area 3 and Core 2.11",
        "spec": "3.1 to 3.8 (all specialisms), Core Paper 1 2.11",
        "pages": SOK,
        **REVISE_SOK,
        "objectives": [
            "Identify types of sources of knowledge for a technical requirement.",
            "Apply reliability and validity factors to judge a source.",
            "Identify types of bias and how to reduce them.",
            "Use critical thinking, evaluation tools and communication methods to share findings.",
        ],
        "starter": "You search for how to fix an error and get a forum post, a vendor article and a YouTube video. "
                   "Which do you trust most, and why?",
        "slides": [
            {"type": "cards", "title": "Types of sources",
             "cards": [
                 ("Literature", "Textbooks, journals, manuals, supplier literature."),
                 ("Websites", "Wikis, forums, Stack Overflow, manufacturer sites."),
                 ("Media", "Social media, blogs, vlogs, podcasts, webinars."),
                 ("People", "Peers, managers, professional networks and conferences."),
                 ("Learning", "MOOCs and vendor qualifications such as Cisco or CompTIA."),
                 ("Specialist", "Professional bodies, regulators, standards and databases such as CVE."),
             ],
             "notes": "Cyber Security adds professional bodies (CIISec, CREST, ISACA, UK Cyber Security Council), the ICO, CIS Benchmarks and the CVE database. Observation (dashboards, inspection) also counts as a source."},
            {"type": "cards", "title": "Is the source reliable and valid?",
             "cards": [
                 ("Authority", "Is the author credible, qualified and linked to a recognised body?"),
                 ("Evidence", "Does it cite its sources?"),
                 ("Currency", "Is the version and date recent enough?"),
                 ("Relevance", "Does it fit the task, the context and the audience?"),
                 ("Corroboration", "Do other independent sources agree?"),
                 ("Bias", "Is opinion shaping the content?"),
             ]},
            {"type": "table", "title": "Types of bias",
             "header": ["Bias", "What it looks like"],
             "widths": [2.6, 6],
             "rows": [
                 ["Author or proprietary", "Personal opinion or a vendor promoting its own product"],
                 ["Confirmation", "Only accepting sources that support what you already think"],
                 ["Selection", "Choosing sources to fit a predetermined conclusion"],
                 ["Cultural", "Assumptions based on one society's norms"],
                 ["Availability (cyber)", "Opinion skewed by the most recent or memorable event"],
             ],
             "caption": "Indicators: partiality, prejudice, omission. Reduce bias with evidence and an inclusive, objective approach."},
            {"type": "process", "title": "Critical thinking process",
             "steps": [
                 ("Identify", "Relevant arguments, views and opinions."),
                 ("Analyse", "Spot bias; link the data together."),
                 ("Select tools", "Choose evaluation techniques and tools."),
                 ("Evaluate", "Assess findings and draw conclusions."),
                 ("Record", "Write up the conclusions."),
             ],
             "notes": "Techniques: formative and summative evaluation, qualitative and quantitative methods, corroboration, triangulation. Tools: gap analysis, KPI analysis, scorecards, user diaries, maturity assessments."},
            {"type": "compare", "title": "Sharing knowledge",
             "left": ("Recording issues", [
                 "Ticket systems track trends and satisfaction",
                 "Chatbots answer common questions",
                 "Record user, issue, resolution and time taken",
                 "Track status and escalation",
             ]),
             "right": ("Communication methods", [
                 "ITSM tools and knowledge bases",
                 "Wikis, shared documents and workspaces",
                 "Email, chat, video calls, forums",
                 "Project tools: issue logs, Gantt, Kanban, burndown",
                 "Cyber: CyBOK and MITRE ATT&CK",
             ])},
        ],
        "quiz": [
            ("Give three factors that make a source reliable.", "Any three of: authority, evidence, currency, relevance, corroboration, lack of bias."),
            ("What is confirmation bias?", "Favouring sources that support what you already believe."),
            ("What is triangulation?", "Checking a finding using three or more different sources or methods."),
            ("What does a gap analysis compare?", "The current state against the desired state."),
            ("Name one knowledge base used in cyber security.", "CyBOK or MITRE ATT&CK."),
        ],
        "activity": {
            "title": "Source showdown",
            "time": "25 minutes",
            "format": "Pairs",
            "steps": [
                "Research question: 'Is Wi-Fi 7 worth installing in a small office this year?'",
                "Find three different types of source.",
                "Score each for authority, currency, evidence and bias.",
                "Recommend which source to trust most and justify it in technical language.",
            ],
            "success": [
                "Three different source types",
                "Each factor scored with a reason",
                "Any bias identified and named",
                "Clear, justified recommendation",
            ],
        },
        "exit": [
            "Why is a vendor's own article possibly biased?",
            "How would you corroborate a forum answer?",
            "Which communication method would you use to share a fix with your team?",
        ],
    },
]
